import {Store,st,product,kpi,table,actions,esc,n,money,upper,monthKey,isoDate,toast,round2,calcInvoice,stockForProduct} from './context.js';

function checks(period=monthKey()){
  const all=st().invoices.filter(i=>i.date?.startsWith(period)&&i.status!=='draft');
  const nums=all.map(i=>i.number).filter(Boolean),duplicates=[...new Set(nums.filter((x,i)=>nums.indexOf(x)!==i))];
  const ints=nums.map(x=>Number(String(x).match(/(\d+)$/)?.[1])).filter(Number.isFinite).sort((a,b)=>a-b);const missing=[];if(ints.length){for(let x=ints[0];x<=ints.at(-1);x++)if(!ints.includes(x))missing.push(x)}
  const badVat=[];const badBoxes=[];const belowCost=[];
  for(const i of all.filter(x=>x.status!=='void'))for(const l of calcInvoice(i).lines){const p=product(l.productId);if(![0,4,10,21].includes(n(l.vat)))badVat.push(`${i.number} · ${l.product}`);if(l.mode==='caja_kg'&&!n(l.kgPerBox))badBoxes.push(`${i.number} · ${l.product}`);if(n(l.price)<n(l.buyPriceSnapshot??p?.buyPrice))belowCost.push(`${i.number} · ${l.product}`)}
  const negative=st().products.filter(p=>stockForProduct(st(),p.id).physical<-.001).map(p=>`${p.name}: ${stockForProduct(st(),p.id).physical}`);
  const unbilled=st().orders.filter(o=>o.date?.startsWith(period)&&o.status==='delivered'&&!o.invoiceId).map(o=>o.id);
  const unsent=all.filter(i=>!['void'].includes(i.status)&&!i.sentAt).length;
  return {all,duplicates,missing,badVat,badBoxes,belowCost,negative,unbilled,unsent,critical:duplicates.length+missing.length+badVat.length+badBoxes.length+negative.length+unbilled.length};
}
export function closeViewPlus(){const period=monthKey(),c=checks(period),closed=st().closures.find(x=>x.period===period);const issues=[['NÚMEROS DUPLICADOS',c.duplicates.length,c.duplicates.join(', ')],['SALTOS NUMERACIÓN',c.missing.length,c.missing.slice(0,20).join(', ')],['IVA A REVISAR',c.badVat.length,c.badVat.slice(0,10).join(' · ')],['CAJA×KG SIN KG/CAJA',c.badBoxes.length,c.badBoxes.slice(0,10).join(' · ')],['STOCK NEGATIVO',c.negative.length,c.negative.slice(0,10).join(' · ')],['ENTREGAS SIN FACTURAR',c.unbilled.length,''],['FACTURAS SIN ENVIAR',c.unsent,'AVISO'],['VENTAS BAJO COSTE',c.belowCost.length,c.belowCost.slice(0,10).join(' · ')]];return `<div class="section-head"><div><h2>CIERRE MENSUAL · ${period}</h2><p>REVISIÓN FISCAL Y OPERATIVA ANTES DE BLOQUEAR EL PERIODO.</p></div>${closed?'<span class="badge ok">PERIODO CERRADO</span>':actions([['REVISAR Y CERRAR','safeCloseMonth',c.critical?'':'primary']])}</div><div class="kpis">${kpi('FACTURAS',String(c.all.length))}${kpi('INCIDENCIAS CRÍTICAS',String(c.critical),'',c.critical?'warn':'')}${kpi('SIN ENVIAR',String(c.unsent))}</div>${table(['CONTROL','RESULTADO','DETALLE'],issues.map(([label,count,detail])=>`<tr><td>${label}</td><td>${count?`<span class="badge ${label==='FACTURAS SIN ENVIAR'||label==='VENTAS BAJO COSTE'?'warn':'bad'}">${count}</span>`:'<span class="badge ok">OK</span>'}</td><td>${esc(detail||'')}</td></tr>`))}`}
export async function safeCloseMonth(){const period=monthKey(),c=checks(period);if(c.critical)return toast(`NO SE PUEDE CERRAR: ${c.critical} INCIDENCIAS CRÍTICAS`,'bad');if(!confirm(`CERRAR Y BLOQUEAR ${period}?`))return;const snapshot=st().products.map(p=>({productId:p.id,qty:stockForProduct(st(),p.id).physical,value:round2(stockForProduct(st(),p.id).physical*n(p.buyPrice))}));await Store.save('closures',{id:period,period,date:isoDate(),stockSnapshot:snapshot,closedAt:new Date().toISOString(),checks:{invoiceCount:c.all.length,unsent:c.unsent,belowCost:c.belowCost.length}});await Store.saveSettings({lockedPeriods:[...new Set([...(st().settings.lockedPeriods||[]),period])]});toast(`${period} CERRADO Y BLOQUEADO`);window.ARW_RENDER?.()}
