import {Runtime} from './runtime.js';
import {section,table,kpi,toast,esc,badge} from './ui.js';
import {today,upper} from './domain.js';

const cfg=()=>Runtime.settings();
function data(){const s=cfg(),signed=Boolean(s.responsibleDeclarationSigned);return{signed,name:'ARW2026 PRO',code:String(s.verifactuSystemId||'AW').slice(0,2).toUpperCase(),version:String(s.version||Runtime.version||'7.0.0'),components:'APLICACIÓN WEB/PWA JAVASCRIPT, FIREBASE AUTHENTICATION, CLOUD FIRESTORE, FIREBASE STORAGE Y BACKEND FIREBASE FUNCTIONS PARA REMISIÓN VERI*FACTU CUANDO ESTÉ CONFIGURADO.',onlyVerifactu:s.verifactuEnabled?'SÍ EN EL MODO FISCAL ACTIVADO; LA APLICACIÓN NO MARCA PRODUCCIÓN COMO ACTIVA SIN BACKEND Y CERTIFICADO.':'NO ACTIVADO EN ESTA INSTALACIÓN.',multiTaxpayer:'NO. ESTA INSTALACIÓN ARW2026 GESTIONA UN ÚNICO OBLIGADO TRIBUTARIO EN companies/arw2026.',signatureType:s.verifactuEnabled?'NO APLICA MIENTRAS FUNCIONA COMO VERI*FACTU; LA IDENTIFICACIÓN PARA REMISIÓN SE REALIZA MEDIANTE CERTIFICADO VÁLIDO CONFIGURADO EN BACKEND.':'PENDIENTE DE DEFINIR SI SE UTILIZA COMO NO VERI*FACTU.',producerName:upper(s.verifactuProducerName||''),producerNif:upper(s.verifactuProducerNif||''),producerAddress:upper(s.verifactuProducerAddress||''),place:upper(s.responsibleDeclarationPlace||'BURGOS, ESPAÑA'),date:s.responsibleDeclarationDate||today(),contact:s.verifactuProducerContact||'',url:'https://shaniwaris80-crypto.github.io/aw9/'} }
export function declarationText(){const d=data(),claim=d.signed?'EL PRODUCTOR DECLARA QUE EL SISTEMA INFORMÁTICO, EN LA VERSIÓN INDICADA, CUMPLE CON EL ARTÍCULO 29.2.J) DE LA LEY 58/2003, EL REGLAMENTO APROBADO POR EL REAL DECRETO 1007/2023, LA ORDEN HAC/1177/2024 Y LAS ESPECIFICACIONES PUBLICADAS POR LA AEAT QUE LO COMPLETAN.':'BORRADOR PENDIENTE DE SUSCRIPCIÓN. ESTE DOCUMENTO NO CONSTITUYE TODAVÍA UNA DECLARACIÓN RESPONSABLE FIRMADA NI UNA AFIRMACIÓN DE CUMPLIMIENTO.';return `DECLARACIÓN RESPONSABLE DEL SISTEMA INFORMÁTICO DE FACTURACIÓN\n\na) Nombre del sistema informático: ${d.name}\nb) Código identificador del sistema informático: ${d.code}\nc) Identificador completo de la versión: ${d.version}\nd) Componentes, hardware y software, breve descripción y principales funcionalidades: ${d.components}\ne) Indicación de si solo puede funcionar exclusivamente como VERI*FACTU: ${d.onlyVerifactu}\nf) Indicación de si permite varios obligados tributarios: ${d.multiTaxpayer}\ng) Tipos de firma utilizados en modo NO VERI*FACTU: ${d.signatureType}\nh) Persona o entidad productora: ${d.producerName||'[PENDIENTE]'}\ni) NIF de la persona o entidad productora: ${d.producerNif||'[PENDIENTE]'}\nj) Dirección postal completa del productor: ${d.producerAddress||'[PENDIENTE]'}\nk) Declaración de cumplimiento: ${claim}\nl) Fecha y lugar de suscripción: ${d.date} · ${d.place}\n\nANEXO RECOMENDADO\nContacto adicional: ${d.contact||'[PENDIENTE]'}\nDirección de Internet: ${d.url}\nDescripción técnica: ARW2026 mantiene numeración correlativa, registros de alta/anulación, huella SHA-256, encadenamiento, exportación, auditoría, control de permisos y, cuando se habilita el modo VERI*FACTU, preparación de QR y remisión mediante backend con certificado. La conformidad definitiva debe verificarse contra la versión vigente de los XSD, WSDL y validaciones AEAT antes de suscribir esta declaración.\n`}
export function declarationView(){const d=data(),missing=[!d.producerName&&'PRODUCTOR',!d.producerNif&&'NIF PRODUCTOR',!d.producerAddress&&'DIRECCIÓN PRODUCTOR'].filter(Boolean);return `${section('DECLARACIÓN RESPONSABLE SIF','DOCUMENTO POR VERSIÓN · VISIBLE EN EL PROPIO SISTEMA',`<button class="btn" data-action="declaration-download">DESCARGAR ${d.signed?'DECLARACIÓN':'BORRADOR'}</button>`)}<div class="kpis">${kpi('VERSIÓN',esc(d.version))}${kpi('SISTEMA',esc(d.code))}${kpi('ESTADO',d.signed?'SUSCRITA':'BORRADOR')}${kpi('DATOS PENDIENTES',String(missing.length))}</div>${d.signed?'<div class="success"><b>DECLARACIÓN MARCADA COMO SUSCRITA.</b> CONSERVA LA COPIA FIRMADA DE ESTA VERSIÓN.</div>':'<div class="warning"><b>BORRADOR / PENDIENTE DE SUSCRIPCIÓN.</b> NO SE PRESENTA COMO CERTIFICACIÓN HASTA COMPLETAR VALIDACIÓN Y DATOS DEL PRODUCTOR.</div>'}${missing.length?`<div class="danger">FALTAN: ${missing.map(esc).join(' · ')}</div>`:''}<pre class="panel" style="white-space:pre-wrap;line-height:1.45">${esc(declarationText())}</pre>`}
export function downloadDeclaration(){const d=data(),blob=new Blob([declarationText()],{type:'text/plain;charset=utf-8'}),a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=`ARW2026_DECLARACION_RESPONSABLE_${d.version.replace(/[^A-Za-z0-9._-]/g,'_')}_${d.signed?'FIRMADA':'BORRADOR'}.txt`;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1500);toast(d.signed?'DECLARACIÓN DESCARGADA':'BORRADOR DESCARGADO',d.signed?'good':'warn')}
