import {Runtime} from './runtime.js';
import {section,table,kpi,badge,modal,closeModal,toast,money,esc,optionList} from './ui.js';
import {calcInvoice,calcLine,stockQuantity,stockText,round2,today,now,uid,upper,newLine} from './domain.js';
import {saveEntity,emitInvoice,zeroAllStockCloud,resetOperationalWeek} from './firebase.js';
import {parseOrderText,matchClient} from './importers.js';
import {operationalResetAt,operationalWeekStart,invoiceAfterReset,orderAfterReset,paymentAfterReset,resetLabel} from './period.js';
import {can} from './permissions.js';
import {submitFiscalRecord} from './backend.js';

const st=()=>Runtime.state,product=id=>Runtime.product(id),client=id=>Runtime.client(id);
const products=()=>st().products.filter(p=>p.active!==false&&!p.archived).sort((a,b)=>String(a.name).localeCompare(String(b.name)));
const clients=()=>st().clients.filter(c=>c.active!==false&&!c.archived).sort((a,b)=>String(a.name).localeCompare(String(b.name)));

export {operationalResetAt,operationalWeekStart,invoiceAfterReset,orderAfterReset,paymentAfterReset};

export function enhancedDashboardView(){
  const issued=st().invoices.filter(i=>invoiceAfterReset(i)&&!['draft','void'].includes(i.status)).map(calcInvoice),billed=round2(issued.reduce((s,i)=>s+i.total,0)),pending=round2(issued.reduce((s,i)=>s+i.pending,0)),paid=round2(st().payments.filter(paymentAfterReset).reduce((s,p)=>s+Number(p.amount||0),0)),delivered=st().orders.filter(o=>orderAfterReset(o)&&o.status==='delivered'&&!o.invoiceId).length;
  const badBoxes=products().filter(p=>p.mode==='caja_kg'&&!Number(p.kgPerBox)),zeroPrices=products().filter(p=>Number(p.sellPrice||0)<=0).length,alerts=[];if(delivered)alerts.push(`${delivered} ENTREGAS SIN FACTURAR`);if(badBoxes.length)alerts.push(`${badBoxes.length} PRODUCTOS CAJA × KG SIN PESO`);if(zeroPrices)alerts.push(`${zeroPrices} PRODUCTOS SIN PRECIO DE VENTA`);
  const actions=[can(Runtime.role,'invoiceWrite')?'<button class="btn primary" data-action="invoice-new">＋ FACTURA</button>':'',can(Runtime.role,'orderWrite')?'<button class="btn" data-action="paste-order">PEGAR PEDIDO</button>':'',can(Runtime.role,'invoiceWrite')?'<button class="btn" data-action="invoice-all-delivered">⚡ FACTURAR TODA LA RUTA</button>':'',can(Runtime.role,'weekReset')?'<button class="btn" data-action="week-reset">↻ PONER CONTADORES A 0</button>':''].join('');
  return `${section('CENTRO DE CONTROL',`PERIODO OPERATIVO DESDE ${resetLabel()} · PEDIDO → REPARTO REAL → FACTURA → COBRO`,actions)}<div class="kpis">${kpi('FACTURADO PERIODO',money(billed))}${kpi('COBRADO PERIODO',money(paid))}${kpi('DEUDA PERIODO',money(pending))}${kpi('ENTREGAS SIN FACTURA',String(delivered))}</div><div class="grid2"><div class="panel"><h3>REQUIERE ATENCIÓN</h3>${alerts.length?alerts.map(a=>`<div class="warning">⚠ ${esc(a)}</div>`).join(''):'<div class="success">TODO EN ORDEN</div>'}</div><div class="panel week-panel"><h3>PERIODO OPERATIVO</h3><p>CORTE: <b>${esc(resetLabel())}</b></p><p>FACTURAS NUEVAS: <b>${issued.length}</b></p><p>COBROS NUEVOS: <b>${st().payments.filter(paymentAfterReset).length}</b></p><p>EL RESET NO BORRA HISTÓRICO NI REINICIA NUMERACIÓN.</p>${can(Runtime.role,'invoiceRead')?'<button class="btn" data-action="invoice-history-toggle">VER HISTÓRICO</button>':''}</div></div>`;
}

export function enhancedOrdersView(){
  const all=[...st().orders].sort((a,b)=>String(b.date).localeCompare(String(a.date))),list=window.ARW_ORDER_HISTORY?all:all.filter(orderAfterReset),actions=[can(Runtime.role,'orderWrite')?'<button class="btn primary" data-action="order-new">＋ PEDIDO</button><button class="btn" data-action="paste-order">PEGAR PEDIDO</button><button class="btn" data-action="paste-multi-orders">PEGAR VARIOS CLIENTES</button><button class="btn good" data-action="quick-delivery">MODO REPARTO RÁPIDO</button>':'',can(Runtime.role,'invoiceWrite')?'<button class="btn primary" data-action="invoice-all-delivered">FACTURAR TODA LA RUTA</button>':'',can(Runtime.role,'orderWrite')?`<button class="btn" data-action="order-history-toggle">${window.ARW_ORDER_HISTORY?'SOLO PERIODO':'VER HISTÓRICO'}</button>`:''].join('');
  return `${section('PEDIDOS Y REPARTO',window.ARW_ORDER_HISTORY?'MOSTRANDO HISTÓRICO COMPLETO':`PERIODO DESDE ${resetLabel()}`,actions)}${table(['FECHA','CLIENTE','ESTADO','PRODUCTOS','PEDIDO','ENTREGADO','FACTURA','ACCIONES'],list.map(o=>{const c=client(o.clientId)||o.clientSnapshot||{},rq=(o.lines||[]).reduce((s,l)=>s+Number(l.requestedQty||0),0),dl=(o.lines||[]).reduce((s,l)=>s+Number(l.deliveredQty||0),0);return `<tr><td>${esc(o.date)}</td><td><b>${esc(c.name||'')}</b></td><td>${badge(o.status,o.status==='delivered'?'good':'')}</td><td>${o.lines?.length||0}</td><td>${rq}</td><td>${dl}</td><td>${o.invoiceId?badge('FACTURADO','good'):'—'}</td><td>${can(Runtime.role,'orderWrite')?`<button class="btn mini" data-order-edit="${o.id}">ABRIR</button>`:'—'}${!o.invoiceId&&can(Runtime.role,'invoiceWrite')?` <button class="btn mini good" data-order-invoice="${o.id}">FACTURAR ENTREGADO</button>`:''}</td></tr>`}))}`;
}

export function enhancedInvoicesView(){
  const all=[...st().invoices].sort((a,b)=>String(b.date).localeCompare(String(a.date))||String(b.number||'').localeCompare(String(a.number||''))),list=window.ARW_INVOICE_HISTORY?all:all.filter(invoiceAfterReset);
  const active=list.filter(i=>!['draft','void'].includes(i.status));
  return `${section('FACTURACIÓN',window.ARW_INVOICE_HISTORY?'HISTÓRICO COMPLETO · DOCUMENTOS Y DEUDA ORIGINAL CONSERVADOS':`PERIODO DESDE ${resetLabel()} · CAJA × KG · IVA · TRANSPORTE · R.E.`,`<button class="btn primary" data-action="invoice-new">＋ FACTURA</button><button class="btn" data-action="paste-order">PEGAR PEDIDO → FACTURA</button><button class="btn" data-action="bulk-drafts">PRECIOS MASIVOS BORRADORES</button><button class="btn" data-action="bulk-issued">RECTIFICAR PRECIOS EMITIDAS</button><button class="btn" data-action="invoice-history-toggle">${window.ARW_INVOICE_HISTORY?'SOLO PERIODO':'VER HISTÓRICO'}</button>${can(Runtime.role,'weekReset')?'<button class="btn" data-action="week-reset">↻ PONER CONTADORES A 0</button>':''}`)}
  <div class="kpis">${kpi('BORRADORES',String(list.filter(i=>i.status==='draft').length))}${kpi('EMITIDAS',String(list.filter(i=>i.status==='issued').length))}${kpi('TOTAL',money(active.reduce((s,i)=>s+calcInvoice(i).total,0)))}${kpi('DEUDA',money(active.reduce((s,i)=>s+calcInvoice(i).pending,0)))}</div>
  ${table(['SEL.','Nº','FECHA','CLIENTE','ESTADO','MERCANCÍA','TRANSP.','IVA','R.E.','TOTAL','PENDIENTE','ACCIONES'],list.map(i=>{const x=calcInvoice(i),c=client(i.clientId)||i.clientSnapshot||{},merch=round2(x.productBase-x.globalDiscount);return `<tr><td><input class="inv-check" type="checkbox" value="${i.id}"></td><td><b>${esc(i.number||'BORRADOR')}</b></td><td>${esc(i.date)}</td><td>${esc(c.name||'')}</td><td>${badge(i.status==='void'?'ANULADA':i.status==='draft'?'BORRADOR':x.pending<=0?'PAGADA':'PENDIENTE',i.status==='void'?'bad':x.pending<=0?'good':'warn')}</td><td>${money(merch)}</td><td><b>${money(x.transport)}</b></td><td>${money(x.vatTotal)}</td><td>${money(x.equivalenceTotal||0)}</td><td><b>${money(x.total)}</b></td><td>${money(x.pending)}</td><td><button class="btn mini" data-inv-open="${i.id}">${i.status==='draft'?'EDITAR':'VER'}</button> <button class="btn mini" data-inv-pdf="${i.id}">PDF</button>${i.status==='issued'&&!['credit','debit'].includes(i.type)?` <button class="btn mini" data-inv-rect="${i.id}">RECTIFICAR</button> <button class="btn mini bad" data-inv-void="${i.id}">ANULAR</button>`:''}</td></tr>`}))}`;
}

export function enhancedStockView(){
  const locations=['ALMACEN','FURGONETA','SAN PABLO','SAN LESMES','SANTIAGO'];
  const list=products().map(p=>{const qty=stockQuantity(st().stockMoves,p.id);return{p,qty,value:round2(qty*Number(p.buyPrice||0)),potential:round2(qty*Number(p.sellPrice||0))}}),total=round2(list.reduce((s,x)=>s+x.value,0)),potential=round2(list.reduce((s,x)=>s+x.potential,0)),negative=list.filter(({p})=>locations.some(l=>stockQuantity(st().stockMoves,p.id,l)<-.0001)).length;
  const cards=list.map(({p,qty,value,potential})=>{const boxes=p.mode==='caja_kg'&&Number(p.kgPerBox)>0?round2(qty/Number(p.kgPerBox)):null,hasNeg=locations.some(l=>stockQuantity(st().stockMoves,p.id,l)<-.0001),status=hasNeg?'stock-bad':qty===0?'stock-zero':'stock-ok',loc=locations.map(l=>({l,q:stockQuantity(st().stockMoves,p.id,l)})).filter(x=>Math.abs(x.q)>.0001).map(x=>`${x.l}: ${stockText(p,x.q)}`).join(' · ');return `<article class="stock-card ${status}" data-stock-card><div class="stock-card-head"><div><span class="stock-code">${esc(p.code)}</span><h3>${esc(p.name)}</h3></div><button class="btn mini" data-product-360="${p.id}">360º</button></div><div class="stock-main">${boxes!==null?`<strong>${boxes}</strong><span>CAJAS</span><small>${round2(qty)} KG · ${p.kgPerBox} KG/CAJA</small>`:`<strong>${round2(qty)}</strong><span>${esc(upper(p.mode))}</span>`}</div>${loc?`<small class="muted">${esc(loc)}</small>`:''}<div class="stock-values"><span>COSTE <b>${money(value)}</b></span><span>VENTA POT. <b>${money(potential)}</b></span></div></article>`}).join('');
  return `${section('STOCK','VISUAL · CAJAS + KG · UBICACIONES · VALOR · HISTÓRICO',`<button class="btn primary" data-action="stock-adjust">＋ AJUSTE</button>${can(Runtime.role,'stockReset')?'<button class="btn" data-action="stock-zero-all">PONER TODO A 0</button>':''}<button class="btn" data-action="stock-export">EXPORTAR</button>`)}<div class="kpis">${kpi('VALOR STOCK',money(total))}${kpi('VENTA POTENCIAL',money(potential))}${kpi('PRODUCTOS',String(list.length))}${kpi('NEGATIVOS',String(negative))}</div><div class="panel"><input id="stockSearch" placeholder="BUSCAR PRODUCTO O CÓDIGO" autocomplete="off"></div><div class="stock-grid">${cards}</div>`;
}

export function enhancedProduct360(p){
  if(!p)return toast('PRODUCTO NO ENCONTRADO','bad');
  const moves=st().stockMoves.filter(m=>m.productId===p.id).sort((a,b)=>String(b.createdAt||b.date||'').localeCompare(String(a.createdAt||a.date||''))),qty=stockQuantity(st().stockMoves,p.id),sales=[];
  for(const inv of st().invoices.filter(i=>!['draft','void'].includes(i.status))){const sign=inv.type==='credit'?-1:1;for(const raw of inv.lines||[])if(raw.productId===p.id)sales.push({invoice:inv,line:calcLine(raw),sign})}
  const byClient=new Map();for(const s of sales){const c=client(s.invoice.clientId)||s.invoice.clientSnapshot||{},key=c.name||s.invoice.clientId||'SIN CLIENTE',old=byClient.get(key)||{qty:0,sales:0,lastPrice:0,lastDate:''};old.qty=round2(old.qty+s.sign*s.line.billedQty);old.sales=round2(old.sales+s.sign*s.line.base);if(s.sign>0&&(!old.lastDate||String(s.invoice.date)>=old.lastDate)){old.lastDate=s.invoice.date;old.lastPrice=s.line.price}byClient.set(key,old)}
  const locations=['ALMACEN','FURGONETA','SAN PABLO','SAN LESMES','SANTIAGO'].map(l=>({name:l,qty:stockQuantity(st().stockMoves,p.id,l)}));
  modal(`STOCK 360º · ${p.code} · ${p.name}`,`<div class="kpis">${kpi('STOCK ACTUAL',stockText(p,qty))}${kpi('VALOR COSTE',money(qty*Number(p.buyPrice||0)))}${kpi('VENTA POTENCIAL',money(qty*Number(p.sellPrice||0)))}${kpi('MOVIMIENTOS',String(moves.length))}</div>${p.mode==='caja_kg'?`<div class="success"><b>1 CAJA = ${p.kgPerBox} KG</b> · ${round2(qty/Number(p.kgPerBox||1))} CAJAS EQUIVALENTES</div>`:''}<div class="grid2"><div><h3>POR UBICACIÓN</h3>${table(['UBICACIÓN','STOCK'],locations.map(x=>`<tr><td>${esc(x.name)}</td><td><b>${esc(stockText(p,x.qty))}</b></td></tr>`))}<h3>ÚLTIMOS MOVIMIENTOS</h3>${table(['FECHA','TIPO','UBICACIÓN','CANT.','NOTA'],moves.slice(0,30).map(m=>`<tr><td>${esc(m.date||'')}</td><td>${esc(upper(m.type||''))}</td><td>${esc(m.location||'')}</td><td><b>${Number(m.qty)>0?'+':''}${round2(m.qty)}</b></td><td>${esc(m.note||'')}</td></tr>`))}</div><div><h3>VENTA NETA POR CLIENTE</h3>${table(['CLIENTE','CANTIDAD NETA','VENTAS NETAS','ÚLT. PRECIO','FECHA'],[...byClient].map(([name,v])=>`<tr><td><b>${esc(name)}</b></td><td>${round2(v.qty)}</td><td>${money(v.sales)}</td><td>${money(v.lastPrice)}</td><td>${esc(v.lastDate)}</td></tr>`))}</div></div>`);
}

export async function zeroStockAction(){
  const locations=[...new Set(['ALMACEN','FURGONETA','SAN PABLO','SAN LESMES','SANTIAGO',...st().stockMoves.map(m=>m.location||'ALMACEN')])],nonZero=[];
  for(const p of products())for(const location of locations){const q=stockQuantity(st().stockMoves,p.id,location);if(Math.abs(q)>.0001)nonZero.push({p,location,q})}
  if(!nonZero.length)return toast('TODO EL STOCK, INCLUIDOS NEGATIVOS, YA ESTÁ A 0','good');
  if(!confirm(`SE PONDRÁ A 0 EL STOCK DE ${nonZero.length} PRODUCTO/UBICACIÓN. EL HISTÓRICO SE CONSERVARÁ. ¿CONTINUAR?`))return;
  const typed=prompt('ESCRIBE PONER STOCK A 0 PARA CONFIRMAR');if(upper(typed)!=='PONER STOCK A 0')return;
  try{const n=await zeroAllStockCloud(products(),st().stockMoves,Runtime.user,'REINICIO MANUAL DE STOCK');toast(`${n} AJUSTES CREADOS · POSITIVOS Y NEGATIVOS A 0`,'good')}catch(err){toast(err.message,'bad')}
}

export async function weekResetAction(){
  const active=st().invoices.filter(i=>invoiceAfterReset(i)&&!['draft','void'].includes(i.status)).map(calcInvoice),summary={from:operationalResetAt()||operationalWeekStart(),to:now(),invoices:active.length,total:round2(active.reduce((s,i)=>s+i.total,0)),vat:round2(active.reduce((s,i)=>s+i.vatTotal,0)),pending:round2(active.reduce((s,i)=>s+i.pending,0))};
  if(!confirm('PONER CONTADORES OPERATIVOS A 0 AHORA.\n\nFACTURADO Y DEUDA DEL NUEVO PERIODO EMPEZARÁN EN 0. EL HISTÓRICO Y LA NUMERACIÓN SE CONSERVAN.'))return;
  try{await resetOperationalWeek(summary,Runtime.user);window.ARW_INVOICE_HISTORY=false;window.ARW_ORDER_HISTORY=false;toast('NUEVO PERIODO INICIADO · HISTÓRICO CONSERVADO','good')}catch(e){toast(e.message,'bad')}
}
export function toggleInvoiceHistory(){window.ARW_INVOICE_HISTORY=!window.ARW_INVOICE_HISTORY;Runtime.render?.()}
export function toggleOrderHistory(){window.ARW_ORDER_HISTORY=!window.ARW_ORDER_HISTORY;Runtime.render?.()}

function blockClient(block){const first=String(block).split(/\r?\n/).map(x=>x.trim()).find(Boolean)||'',explicit=first.match(/^CLIENTE\s*[:=-]\s*(.+)$/i);return matchClient(explicit?.[1]||first,clients())}
export function pasteMultiOrders(){
  const m=modal('PEGAR PEDIDOS DE VARIOS CLIENTES',`<label class="field">PEGA LOS PEDIDOS<textarea id="multiOrderText" class="import-text" placeholder="ABBAS\nMACHO MADURO 2\nYUCA 3\n\nADNAN ASIF\nMACHO VERDE 4\nCILANTRO 20"></textarea></label><div class="actions"><button class="btn" id="multiParse">INTERPRETAR</button><button class="btn primary" id="multiSave" disabled>GUARDAR TODOS</button></div><div id="multiPreview"></div>`);
  let parsed=[];m.querySelector('#multiParse').onclick=()=>{const blocks=m.querySelector('#multiOrderText').value.split(/\n\s*\n+/).map(x=>x.trim()).filter(Boolean);parsed=blocks.map(block=>{const c=blockClient(block),body=block.split(/\r?\n/).slice(1).join('\n'),p=parseOrderText(body,products(),clients());return{client:c,lines:p.lines,unrecognized:p.unrecognized,raw:block}});m.querySelector('#multiPreview').innerHTML=parsed.map(x=>`<div class="panel multi-order-card"><h3>${esc(x.client?.name||'CLIENTE NO RECONOCIDO')}</h3><p>${x.lines.length} PRODUCTOS</p>${x.unrecognized.length?`<div class="danger">${x.unrecognized.map(esc).join(' · ')}</div>`:'<div class="success">OK</div>'}</div>`).join('');m.querySelector('#multiSave').disabled=!parsed.length||parsed.some(x=>!x.client||!x.lines.length||x.unrecognized.length)};
  m.querySelector('#multiSave').onclick=async()=>{try{for(const x of parsed)await saveEntity('orders',{id:uid('ord'),date:today(),clientId:x.client.id,clientSnapshot:{id:x.client.id,name:x.client.name,nif:x.client.nif||'',address:x.client.address||''},status:'pending',sourceText:x.raw,createdAt:now(),lines:x.lines.map(l=>({productId:l.productId,requestedQty:l.qty,preparedQty:0,deliveredQty:0}))},'ORDER_MULTI_PASTE',Runtime.user);toast(`${parsed.length} PEDIDOS CREADOS`,'good');closeModal()}catch(e){toast(e.message,'bad')}};
}

export async function invoiceAllDelivered(){
  const orders=st().orders.filter(o=>orderAfterReset(o)&&o.status==='delivered'&&!o.invoiceId&&(o.lines||[]).some(l=>Number(l.deliveredQty||0)>0));if(!orders.length)return toast('NO HAY ENTREGAS PENDIENTES DE FACTURAR','bad');
  if(!confirm(`SE VALIDARÁN Y EMITIRÁN ${orders.length} FACTURAS DESDE LO REALMENTE ENTREGADO. LAS INCORRECTAS NO SE EMITIRÁN.`))return;
  let ok=0,errors=[];for(const o of orders){try{const c=client(o.clientId)||o.clientSnapshot;if(!c)throw new Error('CLIENTE NO ENCONTRADO');const lines=(o.lines||[]).filter(l=>Number(l.deliveredQty||0)>0).map(l=>{const p=product(l.productId);if(!p)throw new Error('PRODUCTO NO ENCONTRADO');return newLine(p,c,{qty:Number(l.deliveredQty||0)})});const dueDate=(()=>{if(!Number(c.dueDays||0))return'';const d=new Date(`${o.date||today()}T12:00:00`);d.setDate(d.getDate()+Number(c.dueDays));return `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`})();const emitted=await emitInvoice({id:uid('inv'),clientId:o.clientId,clientSnapshot:{id:c.id,name:c.name,nif:c.nif||'',address:c.address||'',phone:c.phone||'',equivalenceSurcharge:Boolean(c.equivalenceSurcharge)},issuerSnapshot:{...Runtime.settings()},date:o.date||today(),stockLocation:Runtime.settings().routeStockLocation||'FURGONETA',seriesId:'FA',status:'draft',type:'invoice',transportType:'percent',transportValue:Number(c.transportPercent??Runtime.settings().defaultTransport??10),discount:0,paymentMethod:c.paymentMethod||'efectivo',paid:0,dueDate,equivalenceSurcharge:Boolean(c.equivalenceSurcharge),sourceOrderIds:[o.id],lines},Runtime.user);if(emitted.verifactuRecordId&&Runtime.settings().verifactuBackendReady)submitFiscalRecord(emitted.verifactuRecordId).catch(()=>{});ok++}catch(e){errors.push(`${(client(o.clientId)||o.clientSnapshot||{}).name||o.id}: ${e.message}`)}}toast(`${ok} FACTURAS EMITIDAS${errors.length?` · ${errors.length} REQUIEREN REVISIÓN`:''}`,errors.length?'':'good');if(errors.length)modal('INCIDENCIAS AL FACTURAR RUTA',`<div class="danger">${errors.map(esc).join('<br>')}</div>`,true)
}

export function quickDeliveryModal(){
  const orders=st().orders.filter(o=>orderAfterReset(o)&&!o.invoiceId&&!['cancelled','invoiced'].includes(o.status)).sort((a,b)=>String((client(a.clientId)||{}).name).localeCompare(String((client(b.clientId)||{}).name)));if(!orders.length)return toast('NO HAY PEDIDOS PENDIENTES','bad');
  const m=modal('MODO REPARTO RÁPIDO',`<div class="quick-route-list">${orders.map(o=>{const c=client(o.clientId)||o.clientSnapshot||{};return `<section class="quick-client" data-qorder="${o.id}"><h3>${esc(c.name||'CLIENTE')}</h3>${(o.lines||[]).map((l,i)=>{const p=product(l.productId),step=p?.mode?.startsWith('caja')?1:.1;return `<div class="quick-line"><div><b>${esc(p?.name||l.productId)}</b><small>PIDIÓ ${Number(l.requestedQty||0)}${p?.mode==='caja_kg'?` CAJAS · ${p.kgPerBox} KG/CAJA`:''}</small></div><button class="btn mini" type="button" data-qstep="-${step}" data-i="${i}">−</button><input type="number" step="${step}" data-qdel="${i}" value="${Number(l.deliveredQty||l.requestedQty||0)}"><button class="btn mini" type="button" data-qstep="${step}" data-i="${i}">＋</button></div>`}).join('')}<button class="btn good qsave" type="button">GUARDAR ENTREGA</button></section>`}).join('')}</div>`);
  m.addEventListener('click',async e=>{const step=e.target.dataset.qstep;if(step){const sec=e.target.closest('[data-qorder]'),inp=sec.querySelector(`[data-qdel="${e.target.dataset.i}"]`);inp.value=Math.max(0,round2(Number(inp.value||0)+Number(step)));return}if(e.target.matches('.qsave')){const sec=e.target.closest('[data-qorder]'),o=st().orders.find(x=>x.id===sec.dataset.qorder);if(!o)return;const lines=(o.lines||[]).map((l,i)=>({...l,deliveredQty:Number(sec.querySelector(`[data-qdel="${i}"]`).value||0)}));for(const l of lines){const p=product(l.productId);if(p?.mode?.startsWith('caja')&&!Number.isInteger(Number(l.deliveredQty||0)))return toast(`${p.name}: LAS CAJAS DEBEN SER ENTERAS`,'bad')}await saveEntity('orders',{...o,status:'delivered',lines,deliveredAt:now()},'QUICK_DELIVERY',Runtime.user);sec.classList.add('done');e.target.textContent='ENTREGADO ✓';e.target.disabled=true;toast(`${(client(o.clientId)||{}).name||'CLIENTE'} ENTREGADO`,'good')}});
}

function readInvoiceDom(){
  const form=document.querySelector('#invoiceForm');if(!form)return null;const c=client(form.querySelector('[name=clientId]')?.value);const lines=[...form.querySelectorAll('#invoiceRows tr')].map(tr=>{const pid=tr.querySelector('.i-prod')?.value;if(!pid)return null;const p=product(pid);if(!p)return null;return calcLine({...newLine(p,c),productId:pid,code:p.code,name:p.name,mode:p.mode,qty:Number(tr.querySelector('.i-qty')?.value||0),kgPerBox:Number(tr.querySelector('.i-kg')?.value||0),gross:Number(tr.querySelector('.i-gross')?.value||0),tare:Number(tr.querySelector('.i-tare')?.value||0),price:Number(tr.querySelector('.i-price')?.value||0),vat:Number(tr.querySelector('.i-vat')?.value||0)})}).filter(Boolean);
  return calcInvoice({lines,discount:Number(form.querySelector('[name=discount]')?.value||0),transportType:form.querySelector('[name=transportType]')?.value||'percent',transportValue:Number(form.querySelector('[name=transportValue]')?.value||0),equivalenceSurcharge:Boolean(c?.equivalenceSurcharge),paid:Number(form.querySelector('[name=paid]')?.value||0)})
}
function syncInvoiceFinalBox(){
  const summary=document.querySelector('#invoiceSummary'),form=document.querySelector('#invoiceForm');if(!summary||!form)return;const x=readInvoiceDom();if(!x)return;
  const merchandise=round2(x.productBase-x.globalDiscount),type=form.querySelector('[name=transportType]')?.value||'percent',value=Number(form.querySelector('[name=transportValue]')?.value||0),transportLabel=type==='percent'?`TRANSPORTE ${round2(value)}%`:'TRANSPORTE FIJO',discount=x.globalDiscount?`<div><span>DESCUENTO</span><b>− ${money(x.globalDiscount)}</b></div>`:'',re=x.equivalenceTotal?`<div><span>RECARGO EQUIVALENCIA</span><b>${money(x.equivalenceTotal)}</b></div>`:'';
  summary.innerHTML=`<div class="invoice-final-panel"><div><span>MERCANCÍA</span><b>${money(x.productBase)}</b></div>${discount}<div class="transport-live"><span>${transportLabel}</span><b>${money(x.transport)}</b></div><div><span>BASE IMPONIBLE</span><b>${money(x.base)}</b></div><div><span>IVA TOTAL</span><b>${money(x.vatTotal)}</b></div>${re}<div class="invoice-final-total"><span>TOTAL FACTURA</span><strong>${money(x.total)}</strong></div><small>MERCANCÍA NETA ${money(merchandise)} + TRANSPORTE ${money(x.transport)} + IVA ${money(x.vatTotal)}${x.equivalenceTotal?` + R.E. ${money(x.equivalenceTotal)}`:''} = <b>${money(x.total)}</b><br>PAGADO ${money(x.paid)} · PENDIENTE ${money(x.pending)}</small></div>`;
}

export function initEnhancements(){
  let raf=0;const schedule=()=>{if(raf)return;raf=requestAnimationFrame(()=>{raf=0;syncInvoiceFinalBox()})};
  document.addEventListener('input',e=>{if(e.target.closest?.('#invoiceForm'))schedule()},true);document.addEventListener('change',e=>{if(e.target.closest?.('#invoiceForm'))schedule()},true);
  const root=document.querySelector('#modalRoot');if(root)new MutationObserver(()=>schedule()).observe(root,{childList:true});
}
