import {calcInvoice,lineDescription,upper} from './domain.js';
import {money} from './ui.js';

function getJsPDF(){if(!window.jspdf?.jsPDF)throw new Error('JSPDF NO CARGADO');return window.jspdf.jsPDF;}
function numText(n){return String(Number(n||0)).replace('.',',');}
export function invoicePdfBlob(inv,client,settings={},internal=false){
  const jsPDF=getJsPDF(),doc=new jsPDF({unit:'mm',format:'a4'}),x=calcInvoice(inv),issuer=inv.issuerSnapshot||settings,C=s=>upper(s||'');
  doc.setProperties({title:`FACTURA ${inv.number||'BORRADOR'}`,subject:'ARW2026',author:C(issuer.companyName||'MOHAMMAD ARSLAN WARIS')});
  doc.setFont('helvetica','bold');doc.setFontSize(23);doc.text(['credit','debit'].includes(inv.type)?'FACTURA RECTIFICATIVA':'FACTURA',15,18);
  doc.setFontSize(11);doc.text(C(inv.number||'BORRADOR'),195,16,{align:'right'});doc.setFont('helvetica','normal');doc.text(C(inv.date||''),195,22,{align:'right'});
  doc.setDrawColor(30);doc.line(15,27,195,27);doc.setFontSize(8);doc.setFont('helvetica','bold');doc.text('PROVEEDOR',15,34);doc.text('CLIENTE',110,34);doc.setFont('helvetica','normal');
  const provider=[C(issuer.companyName),C(issuer.companyNif),C(issuer.companyAddress),C(issuer.companyPhone),C(issuer.companyEmail)].filter(Boolean),cust=[C(client?.name||inv.clientSnapshot?.name),C(client?.nif||inv.clientSnapshot?.nif),C(client?.address||inv.clientSnapshot?.address),C(client?.phone||inv.clientSnapshot?.phone)].filter(Boolean);
  provider.forEach((t,i)=>doc.text(t,15,40+i*5));cust.forEach((t,i)=>doc.text(t,110,40+i*5));if(x.equivalenceSurcharge){doc.setFont('helvetica','bold');doc.text('RECARGO DE EQUIVALENCIA',110,40+cust.length*5+2);doc.setFont('helvetica','normal')}
  const startY=Math.max(64,40+Math.max(provider.length,cust.length+(x.equivalenceSurcharge?1:0))*5+7);
  const body=x.lines.map(l=>[C(l.code),C(l.name),C(l.mode==='caja_kg'?'CAJA × KG':l.mode==='caja_fija'?'CAJA FIJA':l.mode),numText(l.qty),l.mode==='caja_kg'?numText(l.kgPerBox):'—',l.gross?numText(l.gross):'—',l.tare?numText(l.tare):'—',l.mode==='caja_kg'?numText(l.net):numText(l.billedQty),`${Number(l.price).toLocaleString('es-ES',{minimumFractionDigits:2,maximumFractionDigits:2})} €`,`${l.vat}%`,money(l.base)]);
  doc.autoTable({startY,head:[['CÓD.','PRODUCTO','MODO','CANT.','KG/CAJA','BRUTO','TARA','NETO','PRECIO','IVA','IMPORTE']],body,styles:{font:'helvetica',fontSize:7,cellPadding:1.7,overflow:'linebreak',lineColor:[226,232,240],lineWidth:.08},headStyles:{fontStyle:'bold',fillColor:[30,41,59],textColor:[255,255,255]},columnStyles:{1:{cellWidth:33},2:{cellWidth:18},8:{halign:'right'},9:{halign:'center'},10:{halign:'right'}},didParseCell:data=>{if(data.section==='body'){data.cell.styles.fillColor=data.row.index%2===0?[245,250,255]:[255,250,240];if(data.column.index===0)data.cell.styles.fontStyle='bold'}},didDrawPage:data=>{doc.setFontSize(7);doc.setTextColor(100);doc.text(`ARW2026 · ${C(inv.number||'BORRADOR')} · PÁGINA ${data.pageNumber}`,105,291,{align:'center'});doc.setTextColor(0)}});
  let y=doc.lastAutoTable.finalY+6;if(y>220){doc.addPage();y=18}const hasRE=Number(x.equivalenceTotal||0)!==0||x.equivalenceSurcharge,taxHead=hasRE?['TIPO','BASE','IVA','R.E.','CUOTA R.E.']:['TIPO','BASE','IVA'],taxBody=x.vatBreakdown.map(v=>hasRE?[`IVA ${v.rate}%`,money(v.base),money(v.vat),v.reRate?`${v.reRate}%`:'—',money(v.re||0)]:[`IVA ${v.rate}%`,money(v.base),money(v.vat)]);
  doc.autoTable({startY:y,head:[taxHead],body:taxBody,theme:'plain',styles:{fontSize:8,cellPadding:1.4},headStyles:{fontStyle:'bold',fillColor:[241,245,249],textColor:[30,41,59]},columnStyles:{1:{halign:'right'},2:{halign:'right'},3:{halign:'right'},4:{halign:'right'}},margin:{left:105,right:15}});
  y=doc.lastAutoTable.finalY+5;if(y>238){doc.addPage();y=22}const rows=[['MERCANCÍA',money(x.productBase)]];if(x.globalDiscount)rows.push(['DESCUENTO',`- ${money(x.globalDiscount)}`]);rows.push(['TRANSPORTE',money(x.transport)],['BASE IMPONIBLE',money(x.base)],['IVA TOTAL',money(x.vatTotal)]);if(hasRE)rows.push(['RECARGO EQUIVALENCIA',money(x.equivalenceTotal||0)]);
  const boxX=105,boxW=90,rowH=6.2,totalH=12,boxH=rows.length*rowH+totalH+4;doc.setDrawColor(30,41,59);doc.setLineWidth(.65);doc.rect(boxX,y,boxW,boxH);doc.setFontSize(8);doc.setFont('helvetica','normal');let ry=y+6;for(const [label,value] of rows){doc.text(label,boxX+5,ry);doc.setFont('helvetica','bold');doc.text(value,boxX+boxW-5,ry,{align:'right'});doc.setFont('helvetica','normal');ry+=rowH}const totalY=y+boxH-totalH;doc.setFillColor(30,41,59);doc.rect(boxX,totalY,boxW,totalH,'F');doc.setTextColor(255);doc.setFont('helvetica','bold');doc.setFontSize(12);doc.text('TOTAL FACTURA',boxX+5,totalY+7.8);doc.setFontSize(15);doc.text(money(x.total),boxX+boxW-5,totalY+8,{align:'right'});doc.setTextColor(0);y+=boxH+6;
  doc.setFont('helvetica','bold');doc.setFontSize(8);doc.text(`PAGADO: ${money(x.paid)}   ·   PENDIENTE: ${money(x.pending)}`,195,y,{align:'right'});doc.setFont('helvetica','normal');if(['credit','debit'].includes(inv.type)){doc.setFont('helvetica','bold');doc.text(`RECTIFICA: ${C(inv.originalInvoiceNumber||'')}`,15,y);doc.setFont('helvetica','normal');doc.text(`MOTIVO: ${C(inv.reason||'')}`,15,y+5,{maxWidth:85})}if(inv.notes){doc.setFontSize(8);doc.text(`OBSERVACIONES: ${C(inv.notes)}`,15,y+11,{maxWidth:85})}
  if(inv.verifactuQrUrl&&window.qrcode){try{const q=window.qrcode(0,'M');q.addData(inv.verifactuQrUrl);q.make();const img=q.createDataURL(5,0);let qy=Math.max(y+8,232);if(qy>253){doc.addPage();qy=20}doc.setFont('helvetica','bold');doc.setFontSize(8);doc.text('QR TRIBUTARIO:',15,qy);doc.addImage(img,'PNG',15,qy+3,32,32);doc.setFontSize(7);const testEnv=/prewww2\.aeat\.es/i.test(inv.verifactuQrUrl),label=testEnv?'VERI*FACTU · ENTORNO DE PRUEBAS AEAT':`VERI*FACTU · FACTURA VERIFICABLE EN LA SEDE ELECTRÓNICA DE LA AEAT${inv.verifactuStatus==='accepted'?'':' · REMISIÓN PENDIENTE'}`;doc.text(label,15,qy+39,{maxWidth:80});}catch(e){console.warn('QR VERI*FACTU',e)}}
  if(internal){let iy=Math.max(y+18,250);if(iy>270){doc.addPage();iy=20}doc.setFont('helvetica','bold');doc.text('COPIA INTERNA · NO ENTREGAR AL CLIENTE',15,iy);iy+=5;doc.setFont('helvetica','normal');for(const l of x.lines){const cost=(l.mode==='caja_kg'?l.net:l.qty)*Number(l.buyPriceSnapshot||0);doc.text(`${C(l.name)} · COSTE ${money(cost)} · BASE ${money(l.base)} · ${lineDescription(l)}`,15,iy,{maxWidth:180});iy+=4;if(iy>280){doc.addPage();iy=20}}}
  return doc.output('blob');
}
export function saveBlob(blob,name){const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),2000)}
export function invoiceFilename(inv,client){const n=upper(client?.name||inv.clientSnapshot?.name||'CLIENTE').replace(/[^A-Z0-9ÁÉÍÓÚÜÑ]+/g,'_').replace(/^_|_$/g,'');return `FACTURA_${n}_${inv.date}_${inv.number||'BORRADOR'}.pdf`}
export function downloadInvoice(inv,client,settings,internal=false){const run=()=>{const blob=invoicePdfBlob(inv,client,inv.issuerSnapshot||settings,internal);saveBlob(blob,invoiceFilename(inv,client))};if(window.matchMedia?.('(max-width:760px)').matches){if('requestIdleCallback'in window)requestIdleCallback(run,{timeout:500});else setTimeout(run,20)}else run()}
export async function downloadDayZip(invoices,clients,settings,date){if(!window.JSZip)throw new Error('JSZIP NO CARGADO');const zip=new window.JSZip();let summary=`ARW2026 · FACTURAS ${date}\n\n`;for(const inv of invoices){const c=clients.find(x=>x.id===inv.clientId)||inv.clientSnapshot||{},blob=invoicePdfBlob(inv,c,inv.issuerSnapshot||settings);zip.file(invoiceFilename(inv,c),blob);const x=calcInvoice(inv);summary+=`${inv.number}\t${upper(c.name)}\t${money(x.total)}\tIVA ${money(x.vatTotal)}\tTRANSPORTE ${money(x.transport)}\tRE ${money(x.equivalenceTotal||0)}\n`}zip.file('RESUMEN.txt',summary);const out=await zip.generateAsync({type:'blob'});saveBlob(out,`ARW2026_FACTURAS_${date}.zip`)}
export function statementPdf(client,invoices,payments){const jsPDF=getJsPDF(),doc=new jsPDF();doc.setFont('helvetica','bold');doc.setFontSize(18);doc.text(`ESTADO DE CUENTA · ${upper(client.name)}`,15,18);const invRows=invoices.filter(i=>i.status!=='void').map(i=>{const x=calcInvoice(i);return[i.date,i.number||'',upper(i.type==='credit'?'RECTIFICATIVA':i.status),money(x.total),money(x.paid),money(x.pending)]});doc.autoTable({startY:28,head:[['FECHA','FACTURA','ESTADO','TOTAL','PAGADO','PENDIENTE']],body:invRows,styles:{fontSize:8}});let y=doc.lastAutoTable.finalY+8;doc.setFont('helvetica','bold');doc.setFontSize(11);doc.text('MOVIMIENTOS DE COBRO',15,y);y+=4;const payRows=payments.sort((a,b)=>String(a.date).localeCompare(String(b.date))).map(p=>[p.date,upper(p.method||''),money(p.amount),String(p.note||'')]);doc.autoTable({startY:y,head:[['FECHA','MÉTODO','IMPORTE','NOTA']],body:payRows,styles:{fontSize:8}});const outstanding=invoices.filter(i=>i.status!=='void'&&i.status!=='draft').reduce((s,i)=>s+calcInvoice(i).pending,0),paid=payments.reduce((s,p)=>s+Number(p.amount||0),0);y=doc.lastAutoTable.finalY+8;doc.setFont('helvetica','bold');doc.text(`COBROS NETOS: ${money(paid)}   ·   PENDIENTE: ${money(outstanding)}`,195,y,{align:'right'});saveBlob(doc.output('blob'),`ESTADO_CUENTA_${upper(client.name).replace(/\W+/g,'_')}.pdf`)}
