import {Runtime} from './runtime.js';
import {now} from './domain.js';

const MAX_ERRORS=50;
export function connectionInfo(){const c=navigator.connection||navigator.mozConnection||navigator.webkitConnection;return{online:navigator.onLine,effectiveType:c?.effectiveType||'',downlink:Number(c?.downlink||0),rtt:Number(c?.rtt||0),saveData:Boolean(c?.saveData)}}
export function syncLabel(){const m=Runtime.syncMeta||{};if(!navigator.onLine)return'OFFLINE';if(m.pendingWrites)return`${m.pendingWrites} CAMBIOS PENDIENTES`;if(m.fromCache)return'CACHÉ LOCAL';return Runtime.syncReady?'SINCRONIZADO':'CONECTANDO'}
export function recordLocalError(error,context='APP',extra={}){const item={id:`err_${Date.now()}_${Math.random().toString(36).slice(2,7)}`,at:now(),context:String(context||'APP').toUpperCase(),message:String(error?.message||error||'ERROR'),code:String(error?.code||''),stack:String(error?.stack||'').slice(0,2000),view:Runtime.view,online:navigator.onLine,userEmail:Runtime.user?.email||'',role:Runtime.role,...extra};Runtime.clientErrors=[item,...(Runtime.clientErrors||[])].slice(0,MAX_ERRORS);try{localStorage.setItem('arw2026_client_errors',JSON.stringify(Runtime.clientErrors.slice(0,20)))}catch{}return item}
export function restoreLocalErrors(){try{const v=JSON.parse(localStorage.getItem('arw2026_client_errors')||'[]');Runtime.clientErrors=Array.isArray(v)?v.slice(0,MAX_ERRORS):[]}catch{Runtime.clientErrors=[]}}
export function clearLocalErrors(){Runtime.clientErrors=[];try{localStorage.removeItem('arw2026_client_errors')}catch{}}
export function updateSyncMeta(meta={}){Runtime.syncMeta={...(Runtime.syncMeta||{}),...meta,lastEventAt:now()};if(!meta.fromCache&&!meta.pendingWrites)Runtime.lastCloudSyncAt=now()}
export function installConnectivityMonitor(onChange=()=>{}){restoreLocalErrors();const fn=()=>{Runtime.syncMeta={...(Runtime.syncMeta||{}),online:navigator.onLine};onChange(connectionInfo())};addEventListener('online',fn);addEventListener('offline',fn);fn();return()=>{removeEventListener('online',fn);removeEventListener('offline',fn)}}
export function installGlobalErrorMonitor(reporter=null){const send=item=>{if(typeof reporter==='function'&&navigator.onLine)Promise.resolve(reporter(item)).catch(()=>{})};addEventListener('error',e=>send(recordLocalError(e.error||e.message,'WINDOW',{source:e.filename||'',line:e.lineno||0,column:e.colno||0})));addEventListener('unhandledrejection',e=>send(recordLocalError(e.reason,'PROMISE')))}
export function systemSnapshot(){const conn=connectionInfo(),m=Runtime.syncMeta||{};return{at:now(),version:Runtime.version||'7.0.0',view:Runtime.view,role:Runtime.role,online:conn.online,network:conn.effectiveType,downlink:conn.downlink,rtt:conn.rtt,fromCache:Boolean(m.fromCache),pendingWrites:Number(m.pendingWrites||0),lastCloudSyncAt:Runtime.lastCloudSyncAt||Runtime.lastSyncAt||'',clientErrors:(Runtime.clientErrors||[]).length,serviceWorker:Boolean(navigator.serviceWorker?.controller)}}
