import {Store,st,product,client,refresh,esc,n,money,num,upper,isoDate,toast,modal,closeModal,calcInvoice,makeStockMove,buildInvoicePdf} from './context.js';

function rectNo(original){const count=st().invoices.filter(i=>i.type==='credit'&&i.originalInvoiceId===original.id).length+1;return `R-${original.number||'FACTURA'}-${count}`}
export function rectificationModal(original){
  if(!original||['draft','void'].includes(original.status)||original.type==='credit')return toast('ESTA FACTURA NO SE PUEDE RECTIFICAR','bad');
  const x=calcInvoice(original),c=client(original.clientId);
  const m=modal(`RECTIFICAR · ${upper(original.number||'')}`,`<form id="rectForm"><div class="warning-box">LA FACTURA ORIGINAL SE CONSERVA. LA RECTIFICATIVA TENDRÁ IMPORTES NEGATIVOS Y QUEDARÁ VINCULADA A ELLA.</div><div class="form-grid"><label>FECHA<input name="date" type="date" value="${isoDate()}"></label><label>MOTIVO<input name="reason" required placeholder="DEVOLUCIÓN, ERROR DE CANTIDAD, PRECIO..."></label><label class="check"><input name="returnStock" type="checkbox"> DEVOLVER MERCANCÍA AL STOCK</label></div><h3>LÍNEAS A RECTIFICAR</h3><div class="table-wrap"><table><thead><tr><th>INCLUIR</th><th>PRODUCTO</th><th>ORIGINAL</th><th>CANTIDAD A RECTIFICAR</th><th>PRECIO</th><th>IVA</th></tr></thead><tbody>${x.lines.map(l=>`<tr data-line="${l.id}"><td><input class="rect-use" type="checkbox" checked></td><td>${esc(l.product)}</td><td>${l.mode==='caja_kg'?`${num(l.qty)} CAJAS · ${num(l.net)} KG`:`${num(l.qty)} ${upper(l.unit)}`}</td><td><input class="rect-qty" type="number" min="0" max="${n(l.qty)}" step=".01" value="${n(l.qty)}"></td><td>${money(l.price)}</td><td>${n(l.vat)}%</td></tr>`).join('')}</tbody></table></div><label class="check"><input name="includeTransport" type="checkbox"> RECTIFICAR TAMBIÉN EL TRANSPORTE DE LA FACTURA ORIGINAL</label><div id="rectPreview" class="invoice-summary"></div><div class="modal-actions"><button class="btn primary">EMITIR RECTIFICATIVA</button></div></form>`,{wide:true});
  const preview=()=>{const lines=x.lines.map(l=>{const row=m.querySelector(`[data-line="${CSS.escape(l.id)}"]`);if(!row?.querySelector('.rect-use').checked)return null;return {...l,qty:Math.min(n(l.qty),n(row.querySelector('.rect-qty').value))}}).filter(l=>l&&n(l.qty)>0);const inv=calcInvoice({type:'credit',lines,transportType:original.transportType,transportValue:m.querySelector('[name=includeTransport]').checked?n(original.transportValue):0,discount:0,paid:0});m.querySelector('#rectPreview').innerHTML=`<div><span>BASE RECTIFICADA</span><b>${money(inv.base)}</b></div><div><span>IVA RECTIFICADO</span><b>${money(inv.vatTotal)}</b></div><div class="grand"><span>TOTAL RECTIFICATIVA</span><b>${money(inv.total)}</b></div>`};
  m.querySelectorAll('input').forEach(i=>i.addEventListener('input',preview));preview();
  m.querySelector('#rectForm').onsubmit=async e=>{e.preventDefault();const f=new FormData(e.currentTarget);const lines=x.lines.map(l=>{const row=m.querySelector(`[data-line="${CSS.escape(l.id)}"]`);if(!row?.querySelector('.rect-use').checked)return null;const qty=Math.min(n(l.qty),n(row.querySelector('.rect-qty').value));return qty>0?{...l,id:Store.uid('line'),qty,base:0,vatAmount:0,total:0}:null}).filter(Boolean);if(!lines.length)return toast('SELECCIONA ALGUNA LÍNEA','bad');let credit=calcInvoice({id:Store.uid('inv'),type:'credit',status:'issued',number:rectNo(original),date:f.get('date'),clientId:original.clientId,originalInvoiceId:original.id,originalInvoiceNumber:original.number,reason:upper(f.get('reason')),lines,transportType:original.transportType,transportValue:f.get('includeTransport')?n(original.transportValue):0,discount:0,paid:0,issuedAt:new Date().toISOString()});await Store.save('invoices',credit,'credit_note');if(f.get('returnStock')){for(const l of credit.lines){const q=l.mode==='caja_kg'?n(l.net):n(l.qty);await Store.save('stockMovements',makeStockMove({productId:l.productId,qty:q,location:'ALMACEN',type:'credit_return',sourceId:credit.id,note:credit.number}),'credit_stock_return')}}await Store.save('invoices',{...original,hasRectification:true},'mark_rectified');toast('RECTIFICATIVA EMITIDA');buildInvoicePdf(credit,c);closeModal();refresh()};
}
