import {st,client,esc,money,upper,monthKey,calcInvoice,invoiceStatus,summaryPdf} from './context.js';
import {reportsViewPlus as baseReports} from './admin-extra.js';

function selectedMonth(){return document.getElementById('reportMonthSelect')?.value||monthKey()}
function invoicesFor(period){return st().invoices.filter(i=>i.date?.startsWith(period)&&!['draft','void'].includes(i.status)).map(calcInvoice)}
export function reportsViewAdvanced(){return `${baseReports()}<section class="panel" style="margin-top:15px"><h3>HISTÓRICO POR PERIODO</h3><div class="form-grid"><label>MES<input id="reportMonthSelect" type="month" value="${monthKey()}"></label></div><div class="actions"><button class="btn primary" data-act="reportSelectedMonth">PDF FACTURAS + IVA</button><button class="btn" data-act="salesBook">LIBRO VENTAS EXCEL</button><button class="btn" data-act="purchaseBook">LIBRO COMPRAS EXCEL</button></div></section>`}
export function reportSelectedMonth(){const p=selectedMonth(),list=invoicesFor(p);summaryPdf(`FACTURAS E IVA ${p}`,['Nº','FECHA','CLIENTE','BASE','IVA','TOTAL','COBRADO','SALDO','ESTADO'],list.map(i=>[i.number||'',i.date||'',upper(client(i.clientId)?.name||''),money(i.base),money(i.vatTotal),money(i.total),money(i.paid),money(i.pending),invoiceStatus(i)]),`FACTURAS_IVA_${p}.pdf`)}
export function salesBook(){const p=selectedMonth(),rows=invoicesFor(p).map(i=>({NUMERO:i.number,FECHA:i.date,CLIENTE:client(i.clientId)?.name||'',NIF:client(i.clientId)?.nif||'',BASE:i.base,IVA:i.vatTotal,TOTAL:i.total,COBRADO:i.paid,SALDO:i.pending,TIPO:i.type==='credit'?'RECTIFICATIVA':'FACTURA'}));const ws=XLSX.utils.json_to_sheet(rows),wb=XLSX.utils.book_new();XLSX.utils.book_append_sheet(wb,ws,'LIBRO VENTAS');XLSX.writeFile(wb,`LIBRO_VENTAS_${p}.xlsx`)}
export function purchaseBook(){const p=selectedMonth(),rows=st().purchases.filter(x=>x.date?.startsWith(p)).map(x=>({FECHA:x.date,PROVEEDOR:st().suppliers.find(s=>s.id===x.supplierId)?.name||'',NIF:st().suppliers.find(s=>s.id===x.supplierId)?.nif||'',FACTURA:x.number||'',BASE:x.base||0,IVA:x.vatTotal||0,TOTAL:x.total||0}));const ws=XLSX.utils.json_to_sheet(rows),wb=XLSX.utils.book_new();XLSX.utils.book_append_sheet(wb,ws,'LIBRO COMPRAS');XLSX.writeFile(wb,`LIBRO_COMPRAS_${p}.xlsx`)}
