import {calcInvoice,round2,upper} from './domain.js';

export const VERIFACTU_SPEC={
  schemaVersion:'1.0',
  hashAlgorithm:'01',
  qrSpecVersion:'0.5.0',
  hashSpecVersion:'0.1.2',
  testQrBase:'https://prewww2.aeat.es/wlpl/TIKE-CONT/ValidarQR',
  prodQrBase:'https://www2.agenciatributaria.gob.es/wlpl/TIKE-CONT/ValidarQR',
  testSoap:'https://prewww1.aeat.es/wlpl/TIKE-CONT/ws/SistemaFacturacion/VerifactuSOAP',
  prodSoap:'https://www1.agenciatributaria.gob.es/wlpl/TIKE-CONT/ws/SistemaFacturacion/VerifactuSOAP'
};

export const VERIFACTU_TYPES={
  F1:'FACTURA',F2:'FACTURA SIMPLIFICADA',F3:'SUSTITUCIÓN DE SIMPLIFICADAS',
  R1:'RECTIFICATIVA ART. 80.1/80.2 O ERROR FUNDADO EN DERECHO',
  R2:'RECTIFICATIVA ART. 80.3',R3:'RECTIFICATIVA ART. 80.4',R4:'RECTIFICATIVA RESTO',R5:'RECTIFICATIVA DE FACTURA SIMPLIFICADA'
};

const pad=n=>String(n).padStart(2,'0');
export function ddmmyyyy(iso){const m=String(iso||'').match(/^(\d{4})-(\d{2})-(\d{2})$/);return m?`${m[3]}-${m[2]}-${m[1]}`:String(iso||'')}
export function localIsoWithOffset(date=new Date()){const off=-date.getTimezoneOffset(),sign=off>=0?'+':'-',hh=pad(Math.floor(Math.abs(off)/60)),mm=pad(Math.abs(off)%60);return `${date.getFullYear()}-${pad(date.getMonth()+1)}-${pad(date.getDate())}T${pad(date.getHours())}:${pad(date.getMinutes())}:${pad(date.getSeconds())}${sign}${hh}:${mm}`}
export function aeatAmount(v){let s=round2(Number(v||0)).toFixed(2);s=s.replace(/\.00$/,'').replace(/(\.\d)0$/,'$1');return s}
export function xmlAmount(v){return round2(Number(v||0)).toFixed(2)}
export function xmlEscape(v){return String(v??'').replace(/&/g,'&amp;').replace(/</g,'&lt;').replace(/>/g,'&gt;').replace(/"/g,'&quot;').replace(/'/g,'&apos;')}
export async function sha256Hex(text){const bytes=new TextEncoder().encode(String(text));const hash=await globalThis.crypto.subtle.digest('SHA-256',bytes);return [...new Uint8Array(hash)].map(b=>b.toString(16).padStart(2,'0')).join('').toUpperCase()}

export function altaHashInput(r){return `IDEmisorFactura=${String(r.issuerNif||'').trim()}&NumSerieFactura=${String(r.invoiceNumber||'').trim()}&FechaExpedicionFactura=${String(r.invoiceDate||'').trim()}&TipoFactura=${String(r.invoiceType||'').trim()}&CuotaTotal=${String(r.vatTotalText??xmlAmount(r.vatTotal)).trim()}&ImporteTotal=${String(r.totalText??xmlAmount(r.total)).trim()}&Huella=${String(r.previousHash||'').trim()}&FechaHoraHusoGenRegistro=${String(r.generatedAt||'').trim()}`}
export function anulacionHashInput(r){return `IDEmisorFacturaAnulada=${String(r.issuerNif||'').trim()}&NumSerieFacturaAnulada=${String(r.invoiceNumber||'').trim()}&FechaExpedicionFacturaAnulada=${String(r.invoiceDate||'').trim()}&Huella=${String(r.previousHash||'').trim()}&FechaHoraHusoGenRegistro=${String(r.generatedAt||'').trim()}`}
export async function hashAlta(r){const input=altaHashInput(r);return{input,hash:await sha256Hex(input)}}
export async function hashAnulacion(r){const input=anulacionHashInput(r);return{input,hash:await sha256Hex(input)}}

export function buildQrUrl({issuerNif,invoiceNumber,date,total,environment='test'}){const base=environment==='production'?VERIFACTU_SPEC.prodQrBase:VERIFACTU_SPEC.testQrBase,q=new URLSearchParams();q.set('nif',String(issuerNif||'').trim().toUpperCase());q.set('numserie',String(invoiceNumber||'').trim());q.set('fecha',ddmmyyyy(date));q.set('importe',aeatAmount(total));return `${base}?${q.toString()}`}

export function fiscalInvoiceType(inv){if(inv?.verifactuType&&VERIFACTU_TYPES[inv.verifactuType])return inv.verifactuType;if(['credit','debit'].includes(inv?.type))return'';return'F1'}
function validNif(v){return /^[A-Z0-9]{9}$/i.test(String(v||'').trim())}
export function verifactuReadiness(inv,client,settings={}){const x=calcInvoice(inv),errors=[],warnings=[],type=fiscalInvoiceType(inv),issuerNif=String(settings.companyNif||'').trim().toUpperCase();if(!settings.verifactuEnabled)warnings.push('VERI*FACTU ESTÁ DESACTIVADO EN CONFIGURACIÓN');if(!validNif(issuerNif))errors.push('NIF DEL EMISOR DEBE TENER 9 CARACTERES');if(!inv?.number)errors.push('FACTURA SIN NÚMERO');if(!/^\d{4}-\d{2}-\d{2}$/.test(String(inv?.date||'')))errors.push('FECHA DE FACTURA INVÁLIDA');if(!type)errors.push('FACTURA RECTIFICATIVA SIN TIPO VERI*FACTU R1-R5');if(!Number.isFinite(Number(x.total)))errors.push('TOTAL DE FACTURA INVÁLIDO');if(String(inv?.number||'').length>60)errors.push('NÚMERO/SERIE SUPERA 60 CARACTERES');if(client?.nif&&!validNif(client.nif))warnings.push('NIF DEL CLIENTE NO TIENE FORMATO NIF ESPAÑOL DE 9 CARACTERES');if(!client?.nif)warnings.push('CLIENTE SIN NIF: REVISAR SI EL TIPO DE FACTURA Y LA IDENTIFICACIÓN SON CORRECTOS');if((x.vatBreakdown||[]).length>12)errors.push('MÁS DE 12 DESGLOSES FISCALES');for(const v of x.vatBreakdown||[])if(![0,4,10,21].includes(Number(v.rate)))warnings.push(`TIPO IVA ${v.rate}% REQUIERE REVISIÓN DE DESGLOSE`);return{ok:!errors.length,errors,warnings,type,issuerNif,total:x.total,vatTotal:x.vatTotal}}

export async function buildAltaRecord(inv,client,settings={},previous=null){const x=calcInvoice(inv),ready=verifactuReadiness(inv,client,settings);if(!ready.ok)throw new Error(ready.errors.join(' · '));const generatedAt=localIsoWithOffset(),record={kind:'alta',schemaVersion:'1.0',issuerNif:ready.issuerNif,issuerName:upper(settings.companyName||''),invoiceNumber:String(inv.number),invoiceDate:ddmmyyyy(inv.date),invoiceType:ready.type,rectificationType:['credit','debit'].includes(inv.type)?(inv.verifactuRectificationType||'I'):'',description:upper(inv.verifactuDescription||inv.notes||'VENTA DE MERCANCÍAS'),clientName:upper(client?.name||inv.clientSnapshot?.name||''),clientNif:String(client?.nif||inv.clientSnapshot?.nif||'').trim().toUpperCase(),vatTotal:round2(x.vatTotal),vatTotalText:xmlAmount(x.vatTotal),total:round2(x.total),totalText:xmlAmount(x.total),breakdown:(x.vatBreakdown||[]).map(v=>({tax:'01',regime:'01',qualification:'S1',rate:Number(v.rate),base:round2(v.base),vat:round2(v.vat),reRate:Number(v.reRate||0),re:round2(v.re||0)})),previousHash:previous?.hash||'',previousInvoiceNumber:previous?.invoiceNumber||'',previousInvoiceDate:previous?.invoiceDate||'',generatedAt,system:{producerName:upper(settings.verifactuProducerName||settings.companyName||''),producerNif:String(settings.verifactuProducerNif||settings.companyNif||'').trim().toUpperCase(),name:String(settings.verifactuSystemName||'ARW2026').slice(0,30),id:String(settings.verifactuSystemId||'AW').slice(0,2),version:String(settings.version||'7.0.0'),installation:String(settings.verifactuInstallation||'ARW2026-01').slice(0,100),onlyVerifactu:'S',multiOT:'N',multipleOT:'N'}};const {input,hash}=await hashAlta(record);record.hashInput=input;record.hash=hash;record.qrUrl=buildQrUrl({issuerNif:record.issuerNif,invoiceNumber:record.invoiceNumber,date:inv.date,total:record.total,environment:settings.verifactuEnvironment||'test'});return record}

export async function buildAnulacionRecord(inv,settings={},previous=null){const issuerNif=String(settings.companyNif||'').trim().toUpperCase();if(!validNif(issuerNif)||!inv?.number)throw new Error('DATOS INSUFICIENTES PARA REGISTRO DE ANULACIÓN');const record={kind:'anulacion',schemaVersion:'1.0',issuerNif,invoiceNumber:String(inv.number),invoiceDate:ddmmyyyy(inv.date),previousHash:previous?.hash||'',previousInvoiceNumber:previous?.invoiceNumber||'',previousInvoiceDate:previous?.invoiceDate||'',generatedAt:localIsoWithOffset(),system:{producerName:upper(settings.verifactuProducerName||settings.companyName||''),producerNif:String(settings.verifactuProducerNif||settings.companyNif||'').trim().toUpperCase(),name:String(settings.verifactuSystemName||'ARW2026').slice(0,30),id:String(settings.verifactuSystemId||'AW').slice(0,2),version:String(settings.version||'7.0.0'),installation:String(settings.verifactuInstallation||'ARW2026-01').slice(0,100),onlyVerifactu:'S',multiOT:'N',multipleOT:'N'}};const {input,hash}=await hashAnulacion(record);record.hashInput=input;record.hash=hash;return record}

function previousXml(r){if(!r.previousHash)return'<sf:PrimerRegistro>S</sf:PrimerRegistro>';return `<sf:RegistroAnterior><sf:IDEmisorFactura>${xmlEscape(r.issuerNif)}</sf:IDEmisorFactura><sf:NumSerieFactura>${xmlEscape(r.previousInvoiceNumber)}</sf:NumSerieFactura><sf:FechaExpedicionFactura>${xmlEscape(r.previousInvoiceDate)}</sf:FechaExpedicionFactura><sf:Huella>${xmlEscape(r.previousHash)}</sf:Huella></sf:RegistroAnterior>`}
function systemXml(s){return `<sf:SistemaInformatico><sf:NombreRazon>${xmlEscape(s.producerName)}</sf:NombreRazon><sf:NIF>${xmlEscape(s.producerNif)}</sf:NIF><sf:NombreSistemaInformatico>${xmlEscape(s.name)}</sf:NombreSistemaInformatico><sf:IdSistemaInformatico>${xmlEscape(s.id)}</sf:IdSistemaInformatico><sf:Version>${xmlEscape(s.version)}</sf:Version><sf:NumeroInstalacion>${xmlEscape(s.installation)}</sf:NumeroInstalacion><sf:TipoUsoPosibleSoloVerifactu>${s.onlyVerifactu}</sf:TipoUsoPosibleSoloVerifactu><sf:TipoUsoPosibleMultiOT>${s.multiOT}</sf:TipoUsoPosibleMultiOT><sf:IndicadorMultiplesOT>${s.multipleOT}</sf:IndicadorMultiplesOT></sf:SistemaInformatico>`}
function breakdownXml(r){return r.breakdown.map(v=>`<sf:DetalleDesglose><sf:Impuesto>${v.tax}</sf:Impuesto><sf:ClaveRegimen>${v.regime}</sf:ClaveRegimen><sf:CalificacionOperacion>${v.qualification}</sf:CalificacionOperacion><sf:TipoImpositivo>${xmlAmount(v.rate)}</sf:TipoImpositivo><sf:BaseImponibleOimporteNoSujeto>${xmlAmount(v.base)}</sf:BaseImponibleOimporteNoSujeto><sf:CuotaRepercutida>${xmlAmount(v.vat)}</sf:CuotaRepercutida>${v.reRate?`<sf:TipoRecargoEquivalencia>${xmlAmount(v.reRate)}</sf:TipoRecargoEquivalencia><sf:CuotaRecargoEquivalencia>${xmlAmount(v.re)}</sf:CuotaRecargoEquivalencia>`:''}</sf:DetalleDesglose>`).join('')}
export function buildSoapEnvelope(record,settings={}){if(record.kind!=='alta')throw new Error('EL GENERADOR SOAP CLIENTE SOLO SOPORTA ALTAS; ANULACIONES SE ENVÍAN DESDE EL BACKEND');const client=record.clientNif?`<sf:Destinatarios><sf:IDDestinatario><sf:NombreRazon>${xmlEscape(record.clientName||'CLIENTE')}</sf:NombreRazon><sf:NIF>${xmlEscape(record.clientNif)}</sf:NIF></sf:IDDestinatario></sf:Destinatarios>`:'';const rect=record.invoiceType.startsWith('R')?`<sf:TipoRectificativa>${xmlEscape(record.rectificationType||'I')}</sf:TipoRectificativa>`:'';return `<?xml version="1.0" encoding="UTF-8"?><soapenv:Envelope xmlns:soapenv="http://schemas.xmlsoap.org/soap/envelope/" xmlns:sfLR="https://www2.agenciatributaria.gob.es/static_files/common/internet/dep/aplicaciones/es/aeat/tike/cont/ws/SuministroLR.xsd" xmlns:sf="https://www2.agenciatributaria.gob.es/static_files/common/internet/dep/aplicaciones/es/aeat/tike/cont/ws/SuministroInformacion.xsd"><soapenv:Header/><soapenv:Body><sfLR:RegFactuSistemaFacturacion><sfLR:Cabecera><sf:ObligadoEmision><sf:NombreRazon>${xmlEscape(record.issuerName)}</sf:NombreRazon><sf:NIF>${xmlEscape(record.issuerNif)}</sf:NIF></sf:ObligadoEmision></sfLR:Cabecera><sfLR:RegistroFactura><sf:RegistroAlta><sf:IDVersion>1.0</sf:IDVersion><sf:IDFactura><sf:IDEmisorFactura>${xmlEscape(record.issuerNif)}</sf:IDEmisorFactura><sf:NumSerieFactura>${xmlEscape(record.invoiceNumber)}</sf:NumSerieFactura><sf:FechaExpedicionFactura>${xmlEscape(record.invoiceDate)}</sf:FechaExpedicionFactura></sf:IDFactura><sf:NombreRazonEmisor>${xmlEscape(record.issuerName)}</sf:NombreRazonEmisor><sf:TipoFactura>${xmlEscape(record.invoiceType)}</sf:TipoFactura>${rect}<sf:DescripcionOperacion>${xmlEscape(record.description)}</sf:DescripcionOperacion>${client}<sf:Desglose>${breakdownXml(record)}</sf:Desglose><sf:CuotaTotal>${record.vatTotalText}</sf:CuotaTotal><sf:ImporteTotal>${record.totalText}</sf:ImporteTotal><sf:Encadenamiento>${previousXml(record)}</sf:Encadenamiento>${systemXml(record.system)}<sf:FechaHoraHusoGenRegistro>${xmlEscape(record.generatedAt)}</sf:FechaHoraHusoGenRegistro><sf:TipoHuella>01</sf:TipoHuella><sf:Huella>${record.hash}</sf:Huella></sf:RegistroAlta></sfLR:RegistroFactura></sfLR:RegFactuSistemaFacturacion></soapenv:Body></soapenv:Envelope>`}

export function verifyChainRecords(records=[]){const sorted=[...records].sort((a,b)=>String(a.sequence||a.createdAt||'').localeCompare(String(b.sequence||b.createdAt||''))),issues=[];let prev='';for(const r of sorted){if((r.previousHash||'')!==prev)issues.push(`CADENA ROTA EN ${r.invoiceNumber||r.id||'REGISTRO'}`);prev=r.hash||''}return{ok:!issues.length,issues,count:sorted.length,lastHash:prev}}
