import {Runtime} from './runtime.js';
import {section,table,kpi,badge,modal,closeModal,toast,optionList,money,esc,exportXlsx} from './ui.js';
import {calcInvoice,round2,today,now,uid,upper,normalize} from './domain.js';
import {saveEntity,forceMasterData} from './firebase.js';
const st=()=>Runtime.state, client=id=>Runtime.client(id), product=id=>Runtime.product(id), settings=()=>Runtime.settings();
const activeClients=()=>st().clients.filter(c=>c.active!==false&&!c.archived).sort((a,b)=>String(a.name).localeCompare(String(b.name)));
const activeProducts=()=>st().products.filter(p=>p.active!==false&&!p.archived).sort((a,b)=>String(a.name).localeCompare(String(b.name)));
const productOpts=(sel='')=>`<option value="">SELECCIONAR</option>${optionList(activeProducts(),sel,p=>`${p.code} · ${p.name}`)}`;

export function reportsView(){const month=window.ARW_REPORT_MONTH||today().slice(0,7),invs=st().invoices.filter(i=>i.date?.startsWith(month)&&!['draft','void'].includes(i.status)).map(calcInvoice),purchases=st().purchases.filter(p=>p.date?.startsWith(month)),expenses=st().expenses.filter(e=>e.date?.startsWith(month));const vat={};for(const i of invs)for(const v of i.vatBreakdown||[]){vat[v.rate]??={base:0,vat:0,re:0,reRate:v.reRate||0};vat[v.rate].base+=v.base;vat[v.rate].vat+=v.vat;vat[v.rate].re+=Number(v.re||0)}const billed=invs.reduce((s,i)=>s+i.total,0),base=invs.reduce((s,i)=>s+i.base,0),vatTotal=invs.reduce((s,i)=>s+i.vatTotal,0),reTotal=invs.reduce((s,i)=>s+Number(i.equivalenceTotal||0),0),paid=invs.reduce((s,i)=>s+i.paid,0),purchaseTotal=purchases.reduce((s,p)=>s+Number(p.total||0),0),expenseTotal=expenses.reduce((s,e)=>s+Number(e.amount||0),0);return `${section('REPORTES','MENSUAL · TRIMESTRAL · IVA · RECARGO EQUIVALENCIA · LIBROS · EXPORTACIONES',`<button class="btn" data-action="report-sales">LIBRO VENTAS</button><button class="btn" data-action="report-purchases">LIBRO COMPRAS</button>`)}<div class="panel"><label class="field">MES<input id="reportMonth" type="month" value="${month}"></label></div><br><div class="kpis">${kpi('FACTURADO',money(billed))}${kpi('BASE',money(base))}${kpi('IVA',money(vatTotal))}${kpi('RECARGO EQ.',money(reTotal))}</div><div class="grid2"><div class="panel"><h3>IVA Y RECARGO REPERCUTIDO</h3>${Object.entries(vat).sort((a,b)=>Number(a[0])-Number(b[0])).map(([r,v])=>`<p>IVA ${r}% · BASE <b>${money(v.base)}</b> · IVA <b>${money(v.vat)}</b>${v.re?` · R.E. ${v.reRate}% <b>${money(v.re)}</b>`:''}</p>`).join('')||'<p>SIN DATOS</p>'}</div><div class="panel"><h3>COMPRAS Y GASTOS</h3><p>COMPRAS: <b>${money(purchaseTotal)}</b></p><p>GASTOS: <b>${money(expenseTotal)}</b></p><p>COBRADO: <b>${money(paid)}</b></p><p>RESULTADO BRUTO SIMPLE: <b>${money(billed-purchaseTotal-expenseTotal)}</b></p></div></div><br>${table(['FACTURA','FECHA','CLIENTE','BASE','IVA','R.E.','TOTAL','PAGADO','PENDIENTE'],invs.map(i=>`<tr><td>${esc(i.number)}</td><td>${i.date}</td><td>${esc((client(i.clientId)||i.clientSnapshot||{}).name||'')}</td><td>${money(i.base)}</td><td>${money(i.vatTotal)}</td><td>${money(i.equivalenceTotal||0)}</td><td>${money(i.total)}</td><td>${money(i.paid)}</td><td>${money(i.pending)}</td></tr>`))}`}
export function reportSales(){const month=window.ARW_REPORT_MONTH||today().slice(0,7),rows=st().invoices.filter(i=>i.date?.startsWith(month)&&!['draft','void'].includes(i.status)).map(i=>{const x=calcInvoice(i),c=client(i.clientId)||i.clientSnapshot||{};return{NUMERO:i.number,FECHA:i.date,CLIENTE:c.name,NIF:c.nif,BASE:x.base,IVA:x.vatTotal,RECARGO_EQUIVALENCIA:x.equivalenceTotal||0,TOTAL:x.total,PAGADO:x.paid,PENDIENTE:x.pending,TIPO:i.type||'invoice'}});exportXlsx(rows,`ARW2026_LIBRO_VENTAS_${month}.xlsx`)}
export function reportPurchases(){const month=window.ARW_REPORT_MONTH||today().slice(0,7),rows=st().purchases.filter(p=>p.date?.startsWith(month)).map(p=>({FECHA:p.date,PROVEEDOR:p.supplierName,FACTURA:p.number,BASE:p.base||0,IVA:p.vatTotal||0,TRANSPORTE:p.transport||0,TOTAL:p.total}));exportXlsx(rows,`ARW2026_LIBRO_COMPRAS_${month}.xlsx`)}

export function expensesView(){const list=[...st().expenses].sort((a,b)=>String(b.date).localeCompare(String(a.date)));return `${section('GASTOS','COMBUSTIBLE · PEAJES · PARKING · ALQUILER · GESTORÍA · OTROS',`<button class="btn primary" data-action="expense-new">＋ GASTO</button>`)}<div class="kpis">${kpi('MES',money(list.filter(e=>e.date?.startsWith(today().slice(0,7))).reduce((s,e)=>s+Number(e.amount||0),0)))}${kpi('HOY',money(list.filter(e=>e.date===today()).reduce((s,e)=>s+Number(e.amount||0),0)))}${kpi('REGISTROS',String(list.length))}${kpi('AÑO',money(list.filter(e=>e.date?.startsWith(today().slice(0,4))).reduce((s,e)=>s+Number(e.amount||0),0)))}</div>${table(['FECHA','CATEGORÍA','CONCEPTO','IMPORTE'],list.map(e=>`<tr><td>${e.date}</td><td>${esc(e.category)}</td><td>${esc(e.concept)}</td><td>${money(e.amount)}</td></tr>`))}`}
export function expenseModal(){const m=modal('NUEVO GASTO',`<form id="ef"><div class="form-grid three"><label>FECHA<input name="date" type="date" value="${today()}"></label><label>CATEGORÍA<select name="category"><option>COMBUSTIBLE</option><option>PEAJES</option><option>PARKING</option><option>ALQUILER</option><option>GESTORÍA</option><option>SEGUROS</option><option>TELÉFONO</option><option>OTROS</option></select></label><label>IMPORTE<input name="amount" type="number" step=".01"></label></div><label class="field">CONCEPTO<input name="concept"></label><button class="btn primary">GUARDAR</button></form>`,true);m.querySelector('#ef').onsubmit=async e=>{e.preventDefault();const f=new FormData(e.currentTarget);await saveEntity('expenses',{id:uid('exp'),date:f.get('date'),category:f.get('category'),concept:upper(f.get('concept')),amount:Number(f.get('amount')||0)},'EXPENSE',Runtime.user);toast('GASTO GUARDADO','good');closeModal()}}

export function priceManagerView(){return `${section('PRECIOS MASIVOS','TARIFAS FUTURAS POR CLIENTE · SIMULACIÓN ANTES DE GUARDAR',`<button class="btn primary" data-action="price-mass">NUEVO CAMBIO MASIVO</button>`)}${table(['PRODUCTO','GENERAL','RECOMENDADO','CLIENTES CON PRECIO ESPECIAL','ACCIONES'],activeProducts().map(p=>{const count=activeClients().filter(c=>c.prices?.[p.id]!=null).length;return `<tr><td><b>${esc(p.code)} · ${esc(p.name)}</b></td><td>${money(p.sellPrice)}</td><td>${money(p.recommended)}</td><td>${count}</td><td><button class="btn mini" data-mass-product="${p.id}">CAMBIAR</button></td></tr>`}))}`}
export function massPriceModal(pid=''){const m=modal('CAMBIO MASIVO DE TARIFAS DE CLIENTES',`<div class="form-grid three"><label>PRODUCTO<select id="mpProd">${productOpts(pid)}</select></label><label>OPERACIÓN<select id="mpMode"><option value="delta">SUMAR / RESTAR €</option><option value="percent">PORCENTAJE %</option><option value="fixed">FIJAR PRECIO</option></select></label><label>VALOR<input id="mpVal" type="number" step=".01" value="0.10"></label></div><label class="check"><input id="mpAll" type="checkbox" checked> APLICAR A TODOS LOS CLIENTES ACTIVOS</label><div id="mpPreview"></div><button class="btn primary" id="mpApply">APLICAR CAMBIO</button>`);const preview=()=>{const p=product(m.querySelector('#mpProd').value);if(!p)return;const mode=m.querySelector('#mpMode').value,val=Number(m.querySelector('#mpVal').value||0);m.querySelector('#mpPreview').innerHTML=table(['CLIENTE','ACTUAL','NUEVO'],activeClients().map(c=>{const old=Number(c.prices?.[p.id]?.price??c.prices?.[p.id]??p.sellPrice),nw=mode==='fixed'?val:mode==='percent'?round2(old*(1+val/100)):round2(old+val);return `<tr><td>${esc(c.name)}</td><td>${money(old)}</td><td>${money(nw)}</td></tr>`}))};m.querySelectorAll('select,input').forEach(x=>x.oninput=preview);m.querySelector('#mpApply').onclick=async()=>{try{const p=product(m.querySelector('#mpProd').value),mode=m.querySelector('#mpMode').value,val=Number(m.querySelector('#mpVal').value||0);for(const c of activeClients()){const old=Number(c.prices?.[p.id]?.price??c.prices?.[p.id]??p.sellPrice),nw=mode==='fixed'?val:mode==='percent'?round2(old*(1+val/100)):round2(old+val);await saveEntity('clients',{...c,prices:{...(c.prices||{}),[p.id]:{price:nw,since:today()}}},'MASS_PRICE_CLIENT',Runtime.user);await saveEntity('priceHistory',{id:uid('ph'),clientId:c.id,productId:p.id,date:today(),oldPrice:old,newPrice:nw,source:'MASIVO',at:now()},'PRICE_HISTORY',Runtime.user)}toast('TARIFAS ACTUALIZADAS','good');closeModal()}catch(e){toast(e.message,'bad')}};preview()}

export function routesView(){const list=[...st().routes].sort((a,b)=>String(b.date).localeCompare(String(a.date)));return `${section('RUTAS','COSTES · CARGA · REPARTO · RENTABILIDAD',`<button class="btn primary" data-action="route-new">＋ RUTA</button>`)}${table(['FECHA','NOMBRE','ESTADO','COMBUSTIBLE','PEAJES','OTROS','COSTE'],list.map(r=>`<tr><td>${r.date}</td><td><b>${esc(r.name||'RUTA')}</b></td><td>${badge(r.status||'ABIERTA')}</td><td>${money(r.fuel)}</td><td>${money(r.tolls)}</td><td>${money(r.other)}</td><td>${money(Number(r.fuel||0)+Number(r.tolls||0)+Number(r.other||0))}</td></tr>`))}`}
export function routeModal(){const m=modal('NUEVA RUTA',`<form id="rf"><div class="form-grid three"><label>FECHA<input name="date" type="date" value="${today()}"></label><label>NOMBRE<input name="name" value="RUTA MADRID"></label><label>ESTADO<select name="status"><option>ABIERTA</option><option>CERRADA</option></select></label><label>COMBUSTIBLE<input name="fuel" type="number" step=".01"></label><label>PEAJES<input name="tolls" type="number" step=".01"></label><label>OTROS<input name="other" type="number" step=".01"></label></div><button class="btn primary">GUARDAR</button></form>`,true);m.querySelector('#rf').onsubmit=async e=>{e.preventDefault();const f=new FormData(e.currentTarget);await saveEntity('routes',{id:uid('route'),date:f.get('date'),name:upper(f.get('name')),status:f.get('status').toLowerCase(),fuel:Number(f.get('fuel')||0),tolls:Number(f.get('tolls')||0),other:Number(f.get('other')||0)},'ROUTE',Runtime.user);toast('RUTA GUARDADA','good');closeModal()}}

export function auditView(){return `${section('AUDITORÍA','QUIÉN HIZO QUÉ Y CUÁNDO')}${table(['FECHA/HORA','USUARIO','ACCIÓN','ENTIDAD','ID'],st().audit.slice(0,300).map(a=>`<tr><td>${String(a.at||'').slice(0,19).replace('T',' ')}</td><td>${esc(a.userEmail||'')}</td><td>${esc(a.action||'')}</td><td>${esc(a.entity||'')}</td><td>${esc(a.entityId||'')}</td></tr>`))}`}

export function settingsView(){const s=settings();return `${section('CONFIGURACIÓN Y SINCRONIZACIÓN','FIREBASE CLOUD · CATÁLOGO MAESTRO · ESTADO DEL SISTEMA',`<button class="btn" data-action="master-reload">RECARGAR CATÁLOGO MAESTRO</button>`)}<div class="grid2"><div class="panel"><h3>EMPRESA</h3><p><b>${esc(s.companyName||'MOHAMMAD ARSLAN WARIS')}</b></p><p>${esc(s.companyNif||'')}</p><p>${esc(s.companyAddress||'')}</p><p>${esc(s.companyEmail||'')}</p><p>SERIE: <b>${esc(s.invoiceSeries||'FA')}</b></p></div><div class="panel"><h3>FIREBASE</h3><p>USUARIO: <b>${esc(Runtime.user?.email||'')}</b></p><p>PRODUCTOS CLOUD: <b>${activeProducts().length}</b></p><p>CLIENTES CLOUD: <b>${activeClients().length}</b></p><p>VERSIÓN MAESTRA: <b>${esc(s.masterVersion||'PENDIENTE')}</b></p><p>LOS CAMBIOS SE RECIBEN CON LISTENERS EN TIEMPO REAL EN TODOS LOS DISPOSITIVOS AUTENTICADOS.</p></div></div><br><div class="warning">SI UN SEGUNDO DISPOSITIVO NO VE LOS DATOS, COMPRUEBA QUE ESTÉ CON EL MISMO PROYECTO FIREBASE, EL MISMO USUARIO Y QUE LAS REGLAS DE FIRESTORE DEL REPOSITORIO ESTÉN PUBLICADAS EN FIREBASE.</div>`}
export async function masterReload(){if(!confirm('¿REAPLICAR EL CATÁLOGO Y CARTERA MAESTRA? SE RESPETAN PRECIOS ESPECIALES DE CLIENTE.'))return;try{await forceMasterData(Runtime.user);toast('CATÁLOGO MAESTRO RECARGADO EN FIRESTORE','good')}catch(e){toast(e.message,'bad')}}
