import {Runtime} from './runtime.js';
import {section,table,kpi,badge,money,esc,exportXlsx} from './ui.js';
import {today,stockText,round2,upper} from './domain.js';
import {operationalResetAt} from './period.js';
import {financialAnalysis} from './finance.js';
import {zeroAllStockCloud} from './firebase.js';

const st=()=>Runtime.state;
const n=v=>Number(v||0);
const activeProducts=()=>st().products.filter(p=>p.active!==false&&!p.archived);
function financeMode(){return window.ARW_FIN_MODE||'operational'}
function defaultQuarter(){const d=new Date(),q=Math.floor(d.getMonth()/3)+1;return `${d.getFullYear()}-Q${q}`}
function financeValue(){return window.ARW_FIN_VALUE||(financeMode()==='quarter'?defaultQuarter():financeMode()==='year'?today().slice(0,4):today().slice(0,7))}
function eventStamp(x){return String(x?.issuedAt||x?.createdAt||x?.updatedAt||(x?.date?`${x.date}T23:59:59.999Z`:''))}
function periodMatch(x){const mode=financeMode(),d=String(x?.date||''),v=financeValue();if(mode==='all')return true;if(mode==='operational'){const cut=operationalResetAt();return !cut||eventStamp(x)>=cut}if(mode==='year')return d.startsWith(v.slice(0,4));if(mode==='quarter'){const m=Number(d.slice(5,7)),q=Number((v.match(/Q([1-4])$/i)||[])[1]||0);return q>0&&d.startsWith(v.slice(0,4))&&m>=q*3-2&&m<=q*3}return d.startsWith(v.slice(0,7))}
function selected(){return{invoices:st().invoices.filter(i=>periodMatch(i)),purchases:st().purchases.filter(periodMatch),expenses:st().expenses.filter(periodMatch)}}
function analysis(){const s=selected();return financialAnalysis({invoices:s.invoices,products:activeProducts(),clients:st().clients,priceHistory:st().priceHistory,stockMoves:st().stockMoves,purchases:s.purchases,expenses:s.expenses})}
function qualityBadge(q){return q==='snapshot'?badge('COSTE CONGELADO','good'):q==='history'?badge('COSTE HISTÓRICO','warn'):badge('COSTE ESTIMADO','bad')}
function marginClass(v){return n(v)<10?'neg':n(v)<20?'':'pos'}
function controls(){const mode=financeMode(),value=financeValue();return `<div class="panel"><div class="form-grid three"><label>PERIODO<select id="financeMode"><option value="operational" ${mode==='operational'?'selected':''}>PERIODO OPERATIVO</option><option value="month" ${mode==='month'?'selected':''}>MES</option><option value="quarter" ${mode==='quarter'?'selected':''}>TRIMESTRE</option><option value="year" ${mode==='year'?'selected':''}>AÑO</option><option value="all" ${mode==='all'?'selected':''}>TODO EL HISTÓRICO</option></select></label><label>VALOR<input id="financeValue" value="${esc(value)}" ${['operational','all'].includes(mode)?'disabled':''} placeholder="2026-08 / 2026-Q3 / 2026"></label></div></div>`}
function tabs(){const tab=window.ARW_FIN_TAB||'summary',items=[['summary','RESUMEN'],['invoices','FACTURAS'],['products','PRODUCTOS'],['clients','CLIENTES'],['stock','STOCK']];return `<div class="actions finance-tabs">${items.map(([id,label])=>`<button class="btn ${tab===id?'primary':''}" data-fin-tab="${id}">${label}</button>`).join('')}</div>`}
function summaryView(a){const t=a.totals,topProducts=[...a.products].filter(x=>Math.abs(x.revenue)>.001).sort((x,y)=>y.profit-x.profit).slice(0,10),topClients=[...a.clients].sort((x,y)=>y.profit-x.profit).slice(0,10);return `<div class="kpis">${kpi('VENTA MERCANCÍA S/IVA',money(t.merchandise))}${kpi('TRANSPORTE COBRADO',money(t.transport))}${kpi('COSTE VENDIDO',money(t.cogs))}${kpi('BENEFICIO BRUTO',money(t.grossProfit))}${kpi('MARGEN BRUTO',`${t.marginPct}%`)}${kpi('GASTOS REGISTRADOS',money(t.expenses))}${kpi('BENEFICIO OPERATIVO',money(t.operatingProfit))}${kpi('DEUDA PENDIENTE',money(t.pending))}</div>
<div class="panel finance-formula"><b>${money(t.merchandise)}</b> VENTA MERCANCÍA + <b>${money(t.transport)}</b> TRANSPORTE − <b>${money(t.cogs)}</b> COSTE VENDIDO = <strong>${money(t.grossProfit)} BENEFICIO BRUTO</strong><br><small>IVA Y RECARGO DE EQUIVALENCIA NO SE CONSIDERAN INGRESO NI BENEFICIO.</small></div>
<div class="kpis">${kpi('COMPRAS BASE',money(t.purchaseBase))}${kpi('COMPRAS TOTAL CON IVA',money(t.purchaseTotal))}${kpi('VALOR STOCK ACTUAL · ÚLTIMO COSTE',money(t.stockCostValue))}${kpi('VENTA POTENCIAL STOCK ACTUAL',money(t.stockPotentialSales))}${kpi('MARGEN POTENCIAL STOCK',money(t.stockPotentialProfit))}${kpi('BENEFICIO BRUTO + STOCK',money(t.totalPotentialGrossProfit))}${kpi('FACTURADO CON IMPUESTOS',money(t.invoiceTotal))}${kpi('STOCK NEGATIVO',String(t.negativeStockCount))}</div>
<div class="grid2"><div class="panel"><h3>PRODUCTOS QUE MÁS BENEFICIO APORTAN</h3>${table(['PRODUCTO','VENTA','COSTE','TRANSP.','BENEFICIO','MARGEN'],topProducts.map(x=>`<tr><td><b>${esc(x.product.code)} · ${esc(x.product.name)}</b></td><td>${money(x.merchandise)}</td><td>${money(x.cogs)}</td><td>${money(x.transport)}</td><td class="${x.profit>=0?'pos':'neg'}"><b>${money(x.profit)}</b></td><td class="${marginClass(x.marginPct)}">${x.marginPct}%</td></tr>`))}</div><div class="panel"><h3>CLIENTES QUE MÁS BENEFICIO APORTAN</h3>${table(['CLIENTE','VENTA','TRANSP.','COSTE','BENEFICIO','MARGEN'],topClients.map(x=>`<tr><td><b>${esc(x.client.name||'')}</b></td><td>${money(x.merchandise)}</td><td>${money(x.transport)}</td><td>${money(x.cogs)}</td><td class="${x.profit>=0?'pos':'neg'}"><b>${money(x.profit)}</b></td><td class="${marginClass(x.marginPct)}">${x.marginPct}%</td></tr>`))}</div></div>`}
function invoiceView(a){return table(['Nº','FECHA','CLIENTE','MERCANCÍA','TRANSP.','COSTE','MARGEN MERC.','BENEFICIO','MARGEN %','TOTAL FACTURA','PENDIENTE','COSTE'],[...a.invoices].sort((x,y)=>String(y.invoice.date).localeCompare(String(x.invoice.date))).map(r=>{const c=st().clients.find(x=>x.id===r.invoice.clientId)||r.invoice.clientSnapshot||{};return `<tr><td><button class="btn mini" data-inv-open="${r.invoice.id}">${esc(r.invoice.number||'')}</button></td><td>${esc(r.invoice.date||'')}</td><td><b>${esc(c.name||'')}</b></td><td>${money(r.merchandise)}</td><td>${money(r.transport)}</td><td>${money(r.cogs)}</td><td>${money(r.merchandiseMargin)}</td><td class="${r.grossProfit>=0?'pos':'neg'}"><b>${money(r.grossProfit)}</b></td><td class="${marginClass(r.marginPct)}">${r.marginPct}%</td><td>${money(r.total)}</td><td>${money(r.pending)}</td><td>${qualityBadge(r.costQuality)}</td></tr>`}))}
function productView(a){const rows=[...a.products].sort((x,y)=>y.profit-x.profit);return table(['PRODUCTO','COMPRADO','GASTO COMPRA','VENDIDO NETO','VENTA MERC.','TRANSP. IMP.','COSTE VENDIDO','BENEFICIO','MARGEN','STOCK','VALOR STOCK','VENTA POT.','MARGEN POT.'],rows.map(x=>`<tr><td><b>${esc(x.product.code)} · ${esc(x.product.name)}</b></td><td>${round2(x.purchasedQty)}</td><td>${money(x.purchaseSpend)}</td><td>${round2(x.qtySold)}</td><td>${money(x.merchandise)}</td><td>${money(x.transport)}</td><td>${money(x.cogs)}</td><td class="${x.profit>=0?'pos':'neg'}"><b>${money(x.profit)}</b></td><td class="${marginClass(x.marginPct)}">${x.marginPct}%</td><td>${esc(stockText(x.product,x.stockQty))}</td><td>${money(x.stockCost)}</td><td>${money(x.stockPotentialSales)}</td><td>${money(x.stockPotentialProfit)}</td></tr>`))}
function clientView(a){const rows=[...a.clients].sort((x,y)=>y.profit-x.profit);return table(['CLIENTE','FACTURAS','MERCANCÍA','TRANSPORTE','COSTE VENDIDO','BENEFICIO','MARGEN','TOTAL FACTURADO','PENDIENTE','TICKET MEDIO'],rows.map(x=>`<tr><td><b>${esc(x.client.name||'')}</b></td><td>${x.invoices}</td><td>${money(x.merchandise)}</td><td>${money(x.transport)}</td><td>${money(x.cogs)}</td><td class="${x.profit>=0?'pos':'neg'}"><b>${money(x.profit)}</b></td><td class="${marginClass(x.marginPct)}">${x.marginPct}%</td><td>${money(x.total)}</td><td>${money(x.pending)}</td><td>${money(x.avgTicket)}</td></tr>`))}
function stockView(a){const rows=[...a.products].sort((x,y)=>y.stockCost-x.stockCost);return `<div class="kpis">${kpi('VALOR STOCK',money(a.totals.stockCostValue))}${kpi('VENTA POTENCIAL',money(a.totals.stockPotentialSales))}${kpi('MARGEN POTENCIAL',money(a.totals.stockPotentialProfit))}${kpi('NEGATIVOS',String(a.totals.negativeStockCount))}</div>${table(['PRODUCTO','STOCK','COSTE ACTUAL','VENTA ACTUAL','VALOR A COSTE','VENTA POTENCIAL','MARGEN POTENCIAL'],rows.map(x=>`<tr class="${x.stockQty<0?'stock-negative-row':''}"><td><b>${esc(x.product.code)} · ${esc(x.product.name)}</b></td><td>${esc(stockText(x.product,x.stockQty))}</td><td>${money(x.currentBuy)}</td><td>${money(x.currentSell)}</td><td>${money(x.stockCost)}</td><td>${money(x.stockPotentialSales)}</td><td>${money(x.stockPotentialProfit)}</td></tr>`))}`}
export function financialView(){const a=analysis(),tab=window.ARW_FIN_TAB||'summary';const body=tab==='invoices'?invoiceView(a):tab==='products'?productView(a):tab==='clients'?clientView(a):tab==='stock'?stockView(a):summaryView(a);return `${section('CENTRO FINANCIERO','COMPRAS · VENTAS · MÁRGENES · TRANSPORTE · BENEFICIO · VALOR DE STOCK',`<button class="btn" data-action="finance-export">EXPORTAR ANÁLISIS</button>`)}${controls()}<br>${tabs()}<br>${body}<div class="panel" style="margin-top:14px"><small><b>CRITERIO:</b> BENEFICIO BRUTO = VENTA DE MERCANCÍA SIN IMPUESTOS + TRANSPORTE COBRADO − COSTE DE LA MERCANCÍA VENDIDA. BENEFICIO OPERATIVO = BENEFICIO BRUTO − GASTOS REGISTRADOS. EL STOCK MOSTRADO ES EL STOCK ACTUAL VALORADO AL ÚLTIMO COSTE Y LA VENTA POTENCIAL USA EL PRECIO GENERAL ACTUAL Y NO INCLUYE IVA NI TRANSPORTE FUTURO.</small></div>`}
export function exportFinancial(){const a=analysis(),rows=a.invoices.map(r=>{const c=st().clients.find(x=>x.id===r.invoice.clientId)||r.invoice.clientSnapshot||{};return{FACTURA:r.invoice.number,FECHA:r.invoice.date,CLIENTE:c.name,MERCANCIA:r.merchandise,TRANSPORTE:r.transport,COSTE_VENDIDO:r.cogs,MARGEN_MERCANCIA:r.merchandiseMargin,BENEFICIO_BRUTO:r.grossProfit,MARGEN_PCT:r.marginPct,TOTAL_FACTURA:r.total,PENDIENTE:r.pending,CALIDAD_COSTE:upper(r.costQuality)}});exportXlsx(rows,`ARW2026_FINANZAS_${financeMode()}_${financeValue()}.xlsx`)}
export async function zeroStockFully(){const products=activeProducts(),moves=st().stockMoves,locations=[...new Set(['ALMACEN','FURGONETA','SAN PABLO','SAN LESMES','SANTIAGO',...moves.map(m=>m.location||'ALMACEN')])],nonZero=[];for(const p of products)for(const location of locations){const q=moves.filter(m=>m.productId===p.id&&(m.location||'ALMACEN')===location).reduce((s,m)=>s+n(m.qty),0);if(Math.abs(q)>.0001)nonZero.push({p,location,q:round2(q)})}if(!nonZero.length)return alert('TODO EL STOCK, INCLUIDOS LOS NEGATIVOS, YA ESTÁ A 0');if(!confirm(`SE CREARÁN ${nonZero.length} AJUSTES PARA DEJAR TODAS LAS UBICACIONES EXACTAMENTE A 0, INCLUIDOS LOS STOCK NEGATIVOS.\nEL HISTÓRICO NO SE BORRA. ¿CONTINUAR?`))return;const typed=prompt('ESCRIBE PONER STOCK A 0 PARA CONFIRMAR');if(upper(typed)!=='PONER STOCK A 0')return;const count=await zeroAllStockCloud(products,moves,Runtime.user,'REINICIO TOTAL INCLUYE NEGATIVOS');alert(`${count} AJUSTES CREADOS. STOCK POSITIVO Y NEGATIVO LLEVADO A 0.`)}
