import {Runtime} from './runtime.js';
import {section,table,kpi,badge,modal,closeModal,toast,optionList,money,esc} from './ui.js';
import {newLine,calcLine,calcInvoice,validateInvoice,invoiceStatus,lineDescription,round2,today,now,uid,upper} from './domain.js';
import {saveEntity,deleteEntity,saveDraft,emitInvoice,recordPayment,voidInvoice,createRectification} from './firebase.js';
import {downloadInvoice,downloadDayZip,statementPdf} from './pdf.js';

const st=()=>Runtime.state, product=id=>Runtime.product(id), client=id=>Runtime.client(id);
const activeProducts=()=>st().products.filter(p=>p.active!==false&&!p.archived).sort((a,b)=>String(a.name).localeCompare(String(b.name)));
const activeClients=()=>st().clients.filter(c=>c.active!==false&&!c.archived).sort((a,b)=>String(a.name).localeCompare(String(b.name)));
const settings=()=>Runtime.settings();

function clientSnapshot(c){return c?{id:c.id,name:c.name,nif:c.nif||'',address:c.address||'',phone:c.phone||'',email:c.email||''}:null}
function quickProducts(){return activeProducts().filter(p=>['MM','MV','GU','YU','BN','CL','LM','NZ','CR','PA','AV','MG'].includes(p.code)).map(p=>`<button type="button" class="product-chip" data-quick="${p.id}">${esc(p.code)} · ${esc(p.name)}</button>`).join('')}
function productOpts(selected=''){return `<option value="">SELECCIONAR...</option>${optionList(activeProducts(),selected,p=>`${p.code} · ${p.name}`)}`}
function clientOpts(selected=''){return `<option value="">SELECCIONAR...</option>${optionList(activeClients(),selected)}`}

export function dashboardView(){
  const month=today().slice(0,7),issued=st().invoices.filter(i=>i.date?.startsWith(month)&&!['draft','void'].includes(i.status)).map(calcInvoice);
  const billed=issued.reduce((s,i)=>s+i.total,0),paid=issued.reduce((s,i)=>s+i.paid,0),pending=issued.reduce((s,i)=>s+i.pending,0);
  const delivered=st().orders.filter(o=>o.status==='delivered'&&!o.invoiceId).length;
  const alerts=[];if(delivered)alerts.push(`${delivered} ENTREGAS SIN FACTURAR`);const badBoxes=activeProducts().filter(p=>p.mode==='caja_kg'&&!Number(p.kgPerBox));if(badBoxes.length)alerts.push(`${badBoxes.length} PRODUCTOS CAJA × KG SIN PESO CONFIGURADO`);
  const pendingSend=st().invoices.filter(i=>i.date===today()&&!['draft','void'].includes(i.status)&&!i.sentAt).length;if(pendingSend)alerts.push(`${pendingSend} FACTURAS DE HOY PENDIENTES DE ENVÍO`);
  return `${section('CENTRO DE CONTROL','PEDIDO → PREPARACIÓN → REPARTO REAL → FACTURA → COBRO',`<button class="btn primary" data-action="invoice-new">＋ FACTURA</button><button class="btn" data-view="orders">＋ PEDIDO</button>`)}
  <div class="flow"><span>PEDIDO</span>→<span>COMPRA / PREPARACIÓN</span>→<span>REPARTO REAL</span>→<span>REVISIÓN</span>→<span>FACTURA</span>→<span>COBRO</span></div>
  <div class="kpis">${kpi('FACTURADO MES',money(billed))}${kpi('COBRADO',money(paid))}${kpi('PENDIENTE',money(pending))}${kpi('ENTREGAS SIN FACTURA',String(delivered))}</div>
  <div class="grid2"><div class="panel"><h3>REQUIERE ATENCIÓN</h3>${alerts.length?alerts.map(a=>`<div class="warning">⚠ ${esc(a)}</div>`).join(''):'<div class="success">TODO EN ORDEN</div>'}</div><div class="panel"><h3>SINCRONIZACIÓN</h3><p>PRODUCTOS: <b>${activeProducts().length}</b></p><p>CLIENTES: <b>${activeClients().length}</b></p><p>FACTURAS HOY: <b>${st().invoices.filter(i=>i.date===today()&&i.status!=='draft').length}</b></p><p>LOS DATOS SE LEEN EN TIEMPO REAL DESDE FIRESTORE.</p></div></div>`;
}

export function ordersView(){
  const list=[...st().orders].sort((a,b)=>String(b.date).localeCompare(String(a.date)));
  return `${section('PEDIDOS Y REPARTO','LO SOLICITADO NO SE FACTURA HASTA REGISTRAR LO REALMENTE ENTREGADO',`<button class="btn primary" data-action="order-new">＋ PEDIDO</button>`)}
  ${table(['FECHA','CLIENTE','ESTADO','PRODUCTOS','PEDIDO','ENTREGADO','FACTURA','ACCIONES'],list.map(o=>{const c=client(o.clientId),rq=(o.lines||[]).reduce((s,l)=>s+Number(l.requestedQty||0),0),dl=(o.lines||[]).reduce((s,l)=>s+Number(l.deliveredQty||0),0);return `<tr><td>${esc(o.date)}</td><td><b>${esc(c?.name||o.clientSnapshot?.name||'')}</b></td><td>${badge(o.status,o.status==='delivered'?'good':'')}</td><td>${o.lines?.length||0}</td><td>${rq}</td><td>${dl}</td><td>${o.invoiceId?badge('FACTURADO','good'):'—'}</td><td><button class="btn mini" data-order-edit="${o.id}">ABRIR</button>${!o.invoiceId?` <button class="btn mini good" data-order-invoice="${o.id}">FACTURAR ENTREGADO</button>`:''}</td></tr>`}))}`;
}

function orderLineRow(line={}){return `<tr><td><select class="o-prod">${productOpts(line.productId)}</select></td><td><input class="o-req" type="number" step=".01" value="${Number(line.requestedQty||0)}"></td><td><input class="o-prep" type="number" step=".01" value="${Number(line.preparedQty||0)}"></td><td><input class="o-del" type="number" step=".01" value="${Number(line.deliveredQty||0)}"></td><td><button type="button" class="btn mini bad" data-remove-row>×</button></td></tr>`}
export function orderModal(existing=null){
  const o=existing?structuredClone(existing):{id:uid('ord'),date:today(),clientId:'',status:'pending',lines:Array.from({length:6},()=>({productId:'',requestedQty:0,preparedQty:0,deliveredQty:0}))};
  const m=modal(existing?'PEDIDO / ENTREGA':'NUEVO PEDIDO',`<form id="orderForm"><div class="form-grid"><label>CLIENTE<select name="clientId" required>${clientOpts(o.clientId)}</select></label><label>FECHA<input name="date" type="date" value="${o.date}"></label><label>ESTADO<select name="status"><option value="pending">PENDIENTE</option><option value="preparing">PREPARANDO</option><option value="prepared">PREPARADO</option><option value="loaded">CARGADO</option><option value="delivered">ENTREGADO</option><option value="cancelled">CANCELADO</option></select></label></div><div class="table-wrap"><table><thead><tr><th>PRODUCTO</th><th>PEDIDO</th><th>PREPARADO</th><th>ENTREGADO REAL</th><th></th></tr></thead><tbody id="orderRows">${o.lines.map(orderLineRow).join('')}</tbody></table></div><div class="actions" style="margin-top:10px"><button type="button" class="btn" id="addOrderLine">＋ LÍNEA</button><button class="btn primary">GUARDAR</button></div></form>`);
  const form=m.querySelector('#orderForm');form.status.value=o.status;
  m.querySelector('#addOrderLine').onclick=()=>m.querySelector('#orderRows').insertAdjacentHTML('beforeend',orderLineRow());
  m.addEventListener('click',e=>{if(e.target.matches('[data-remove-row]'))e.target.closest('tr').remove()});
  form.onsubmit=async e=>{e.preventDefault();try{const fd=new FormData(form),cid=fd.get('clientId'),c=client(cid),lines=[...m.querySelectorAll('#orderRows tr')].map(tr=>({productId:tr.querySelector('.o-prod').value,requestedQty:Number(tr.querySelector('.o-req').value||0),preparedQty:Number(tr.querySelector('.o-prep').value||0),deliveredQty:Number(tr.querySelector('.o-del').value||0)})).filter(l=>l.productId&&l.requestedQty>0);if(!lines.length)throw new Error('AÑADE AL MENOS UN PRODUCTO');await saveEntity('orders',{...o,clientId:cid,clientSnapshot:clientSnapshot(c),date:fd.get('date'),status:fd.get('status'),lines},existing?'ORDER_UPDATE':'ORDER_CREATE',Runtime.user);toast('PEDIDO GUARDADO','good');closeModal()}catch(err){toast(err.message,'bad')}};
}

function blankInvoice(){return {id:uid('inv'),clientId:'',date:today(),seriesId:'FA',status:'draft',type:'invoice',transportType:'percent',transportValue:Number(settings().defaultTransport??10),discount:0,paymentMethod:'efectivo',paid:0,dueDate:'',notes:'',lines:Array.from({length:10},()=>({productId:'',qty:0,kgPerBox:0,gross:0,tare:0,price:0,vat:4,discount:0}))}}
function invoiceRow(line={},idx=0){const p=product(line.productId);const l=p?calcLine({...newLine(p,null),...line}):calcLine(line);return `<tr data-line="${idx}"><td>${idx+1}</td><td><select class="prod-select i-prod">${productOpts(line.productId)}</select><div class="line-info">${p?`${esc(p.code)} · ${esc(p.mode)} · IVA ${p.vat}%`:''}</div></td><td class="i-mode">${esc(upper(p?.mode||line.mode||''))}</td><td><input class="i-qty" type="number" min="0" step=".01" value="${Number(line.qty||0)}"><div class="line-info i-qty-unit">${p?.mode==='caja_kg'||p?.mode==='caja_fija'?'CAJAS':p?.mode==='manojo'?'MANOJOS':upper(p?.mode||'')}</div></td><td><input class="i-kg" type="number" min="0" step=".01" value="${Number(line.kgPerBox??p?.kgPerBox??0)}"></td><td><input class="i-gross" type="number" min="0" step=".01" value="${Number(line.gross||0)}"></td><td><input class="i-tare" type="number" min="0" step=".01" value="${Number(line.tare||0)}"></td><td class="i-net"><b>${l.net||0}</b></td><td><div class="price-step"><button type="button" class="btn mini" data-price-step="-.05">−</button><input class="i-price" type="number" step=".01" value="${Number(line.price??p?.sellPrice??0)}"><button type="button" class="btn mini" data-price-step=".05">＋</button></div><div class="line-info">COMPRA ${Number(p?.buyPrice||0).toFixed(2)} · REC. ${Number(p?.recommended||0).toFixed(2)}</div></td><td><select class="i-vat">${[0,4,10,21].map(v=>`<option value="${v}" ${Number(line.vat??p?.vat??4)===v?'selected':''}>${v}%</option>`).join('')}</select></td><td class="i-base money">${money(l.base||0)}</td><td><button type="button" class="btn mini bad" data-remove-inv>×</button></td></tr>`}

function collectInvoice(m,base){
  const cid=m.querySelector('[name=clientId]').value,c=client(cid);
  const lines=[...m.querySelectorAll('#invoiceRows tr')].map(tr=>{const pid=tr.querySelector('.i-prod').value;if(!pid)return null;const p=product(pid);return calcLine({...newLine(p,c),productId:pid,code:p.code,name:p.name,mode:p.mode,qty:Number(tr.querySelector('.i-qty').value||0),kgPerBox:Number(tr.querySelector('.i-kg').value||0),gross:Number(tr.querySelector('.i-gross').value||0),tare:Number(tr.querySelector('.i-tare').value||0),price:Number(tr.querySelector('.i-price').value||0),vat:Number(tr.querySelector('.i-vat').value||0),buyPriceSnapshot:Number(p.buyPrice||0)});}).filter(Boolean);
  return {...base,clientId:cid,clientSnapshot:clientSnapshot(c),date:m.querySelector('[name=date]').value,transportType:m.querySelector('[name=transportType]').value,transportValue:Number(m.querySelector('[name=transportValue]').value||0),discount:Number(m.querySelector('[name=discount]').value||0),paymentMethod:m.querySelector('[name=paymentMethod]').value,paid:Number(m.querySelector('[name=paid]').value||0),dueDate:m.querySelector('[name=dueDate]').value,notes:upper(m.querySelector('[name=notes]').value),lines};
}
function updateInvoiceUI(m,base){
  const inv=collectInvoice(m,base),v=validateInvoice(inv,activeProducts(),activeClients()),x=v.invoice;
  m.querySelector('#invoiceSummary').innerHTML=`<div class="kpis">${kpi('BASE',money(x.base))}${kpi('IVA',money(x.vatTotal))}${kpi('TOTAL',money(x.total))}${kpi('PENDIENTE',money(x.pending))}</div>${v.errors.length?`<div class="danger">${v.errors.map(esc).join('<br>')}</div>`:''}${v.warnings.length?`<div class="warning">${v.warnings.map(esc).join('<br>')}</div>`:''}`;
  [...m.querySelectorAll('#invoiceRows tr')].forEach(tr=>{const pid=tr.querySelector('.i-prod').value;if(!pid)return;const p=product(pid),c=client(m.querySelector('[name=clientId]').value);const l=calcLine({...newLine(p,c),qty:Number(tr.querySelector('.i-qty').value||0),kgPerBox:Number(tr.querySelector('.i-kg').value||0),gross:Number(tr.querySelector('.i-gross').value||0),tare:Number(tr.querySelector('.i-tare').value||0),price:Number(tr.querySelector('.i-price').value||0),vat:Number(tr.querySelector('.i-vat').value||0)});tr.querySelector('.i-net').innerHTML=`<b>${l.mode==='caja_kg'?`${l.net} KG`:l.net}</b><div class="line-info">${esc(lineDescription(l))}</div>`;tr.querySelector('.i-base').textContent=money(l.base);});
  return {inv,v};
}

export function invoiceModal(existing=null,preset=null){
  const locked=existing&&existing.status!=='draft';let inv=existing?structuredClone(existing):{...blankInvoice(),...(preset||{})};while((inv.lines||[]).length<10)inv.lines.push({productId:'',qty:0,kgPerBox:0,gross:0,tare:0,price:0,vat:4});
  const initialClient=client(inv.clientId);if(!existing&&initialClient){inv.transportValue=Number(initialClient.transportPercent??inv.transportValue??0);inv.paymentMethod=initialClient.paymentMethod||inv.paymentMethod;if(Number(initialClient.dueDays||0)>0&&!inv.dueDate){const d=new Date(`${inv.date}T12:00:00`);d.setDate(d.getDate()+Number(initialClient.dueDays));inv.dueDate=d.toISOString().slice(0,10)}}
  const m=modal(`${locked?'VER':'FACTURA'} · ${inv.number||'BORRADOR'}`,`<form id="invoiceForm"><div class="form-grid"><label>CLIENTE<select name="clientId" ${locked?'disabled':''}>${clientOpts(inv.clientId)}</select></label><label>FECHA<input name="date" type="date" value="${inv.date}" ${locked?'disabled':''}></label><label>TRANSPORTE<select name="transportType" ${locked?'disabled':''}><option value="percent">PORCENTAJE %</option><option value="fixed">FIJO €</option></select></label><label>VALOR TRANSPORTE<input name="transportValue" type="number" step=".01" value="${Number(inv.transportValue||0)}" ${locked?'disabled':''}></label><label>DESCUENTO GENERAL %<input name="discount" type="number" step=".01" value="${Number(inv.discount||0)}" ${locked?'disabled':''}></label><label>FORMA DE PAGO<select name="paymentMethod" ${locked?'disabled':''}><option value="efectivo">EFECTIVO</option><option value="transferencia">TRANSFERENCIA</option><option value="tarjeta">TARJETA</option><option value="bizum">BIZUM</option><option value="pendiente">PENDIENTE</option></select></label><label>PAGADO €<input name="paid" type="number" step=".01" value="${Number(inv.paid||0)}" ${locked?'disabled':''}></label><label>VENCIMIENTO<input name="dueDate" type="date" value="${inv.dueDate||''}" ${locked?'disabled':''}></label></div>${locked?'':`<div class="toolbar">${quickProducts()}<button class="btn" id="add5" type="button">＋ 5 LÍNEAS</button><button class="btn" id="lastInvoice" type="button">REPETIR ÚLTIMA</button></div>`}<div class="table-wrap"><table class="invoice-lines"><thead><tr><th>#</th><th>PRODUCTO</th><th>MODO</th><th>CANT.</th><th>KG/CAJA</th><th>BRUTO</th><th>TARA</th><th>NETO</th><th>PRECIO</th><th>IVA</th><th>IMPORTE</th><th></th></tr></thead><tbody id="invoiceRows">${inv.lines.map(invoiceRow).join('')}</tbody></table></div><label class="field">OBSERVACIONES<textarea name="notes" ${locked?'disabled':''}>${esc(inv.notes||'')}</textarea></label><div id="invoiceSummary"></div><div class="modal-actions">${locked?`<button type="button" class="btn" id="pdfClient">PDF CLIENTE</button><button type="button" class="btn" id="pdfInternal">PDF INTERNO</button>`:`<button type="button" class="btn" id="saveDraft">GUARDAR BORRADOR</button><button type="button" class="btn primary" id="emit">REVISAR Y EMITIR</button>`}</div></form>`);
  m.querySelector('[name=transportType]').value=inv.transportType||'percent';m.querySelector('[name=paymentMethod]').value=inv.paymentMethod||'efectivo';
  if(locked){m.querySelector('#pdfClient').onclick=()=>downloadInvoice(inv,client(inv.clientId)||inv.clientSnapshot,settings());m.querySelector('#pdfInternal').onclick=()=>downloadInvoice(inv,client(inv.clientId)||inv.clientSnapshot,settings(),true);updateInvoiceUI(m,inv);return;}
  const fillRow=(tr,pid)=>{const p=product(pid);if(!p)return;const c=client(m.querySelector('[name=clientId]').value),l=newLine(p,c);tr.querySelector('.i-mode').textContent=upper(p.mode);tr.querySelector('.i-kg').value=l.kgPerBox;tr.querySelector('.i-price').value=l.price;tr.querySelector('.i-vat').value=l.vat;tr.querySelector('.line-info').textContent=`${p.code} · ${p.mode} · IVA ${p.vat}%`;tr.querySelector('.i-qty-unit').textContent=p.mode==='caja_kg'||p.mode==='caja_fija'?'CAJAS':p.mode==='manojo'?'MANOJOS':upper(p.mode);updateInvoiceUI(m,inv)};
  m.addEventListener('change',e=>{if(e.target.matches('.i-prod'))fillRow(e.target.closest('tr'),e.target.value);if(e.target.name==='clientId'){const cc=client(e.target.value);if(cc){m.querySelector('[name=transportValue]').value=Number(cc.transportPercent||0);m.querySelector('[name=paymentMethod]').value=cc.paymentMethod||'efectivo';if(Number(cc.dueDays||0)>0){const d=new Date(`${m.querySelector('[name=date]').value}T12:00:00`);d.setDate(d.getDate()+Number(cc.dueDays));m.querySelector('[name=dueDate]').value=d.toISOString().slice(0,10)}}[...m.querySelectorAll('#invoiceRows tr')].forEach(tr=>{const pid=tr.querySelector('.i-prod').value;if(pid){const p=product(pid),cp=newLine(p,cc);tr.querySelector('.i-price').value=cp.price}});updateInvoiceUI(m,inv)}});
  m.addEventListener('input',e=>{if(e.target.closest('#invoiceForm'))updateInvoiceUI(m,inv)});
  m.addEventListener('click',e=>{const step=e.target.dataset.priceStep;if(step){const tr=e.target.closest('tr'),inp=tr.querySelector('.i-price');inp.value=round2(Number(inp.value||0)+Number(step));updateInvoiceUI(m,inv)}if(e.target.matches('[data-remove-inv]')){e.target.closest('tr').remove();updateInvoiceUI(m,inv)}});
  const addProduct=pid=>{let tr=[...m.querySelectorAll('#invoiceRows tr')].find(r=>!r.querySelector('.i-prod').value);if(!tr){const tb=m.querySelector('#invoiceRows');tb.insertAdjacentHTML('beforeend',invoiceRow({},tb.children.length));tr=tb.lastElementChild}tr.querySelector('.i-prod').value=pid;fillRow(tr,pid)};
  m.querySelectorAll('[data-quick]').forEach(b=>b.onclick=()=>addProduct(b.dataset.quick));m.querySelector('#add5').onclick=()=>{const tb=m.querySelector('#invoiceRows');for(let i=0;i<5;i++)tb.insertAdjacentHTML('beforeend',invoiceRow({},tb.children.length));};
  m.querySelector('#lastInvoice').onclick=()=>{const cid=m.querySelector('[name=clientId]').value,last=st().invoices.filter(i=>i.clientId===cid&&!['draft','void'].includes(i.status)&&!['credit','debit'].includes(i.type)).sort((a,b)=>String(b.date).localeCompare(String(a.date)))[0];if(!last)return toast('NO HAY FACTURA ANTERIOR','bad');m.querySelector('#invoiceRows').innerHTML=last.lines.map((l,i)=>invoiceRow({...l,id:undefined},i)).join('');updateInvoiceUI(m,inv)};
  m.querySelector('#saveDraft').onclick=async()=>{try{const {inv:tmp}=updateInvoiceUI(m,inv);tmp.id=inv.id;await saveDraft(tmp,Runtime.user);toast('BORRADOR GUARDADO EN FIRESTORE','good');closeModal()}catch(err){toast(err.message,'bad')}};
  m.querySelector('#emit').onclick=async()=>{const btn=m.querySelector('#emit');try{const {inv:tmp,v}=updateInvoiceUI(m,inv);tmp.id=inv.id;if(v.errors.length)throw new Error(v.errors.join(' · '));if(!confirm(`EMITIR FACTURA\n\nCLIENTE: ${client(tmp.clientId)?.name||''}\nBASE: ${money(v.invoice.base)}\nIVA: ${money(v.invoice.vatTotal)}\nTOTAL: ${money(v.invoice.total)}\n\n¿CONFIRMAR?`))return;btn.disabled=true;btn.textContent='EMITIENDO…';const emitted=await emitInvoice(tmp,Runtime.user);toast(`FACTURA ${emitted.number} EMITIDA Y SINCRONIZADA`,'good');closeModal();downloadInvoice(emitted,client(emitted.clientId)||emitted.clientSnapshot,settings())}catch(err){console.error(err);toast(`NO SE PUDO EMITIR: ${err.message||err}`,'bad');btn.disabled=false;btn.textContent='REVISAR Y EMITIR'}};
  updateInvoiceUI(m,inv);
}

export function invoiceFromOrder(order){const c=client(order.clientId),lines=(order.lines||[]).filter(l=>Number(l.deliveredQty||0)>0).map(l=>{const p=product(l.productId);return newLine(p,c,{qty:Number(l.deliveredQty||0)});});invoiceModal(null,{clientId:order.clientId,clientSnapshot:clientSnapshot(c),sourceOrderIds:[order.id],lines});}

export function invoicesView(){
  const list=[...st().invoices].sort((a,b)=>String(b.date).localeCompare(String(a.date))||String(b.number||'').localeCompare(String(a.number||'')));
  return `${section('FACTURACIÓN','10 LÍNEAS · IVA POR PRODUCTO · CAJA × KG · RECTIFICATIVAS · ZIP DEL DÍA',`<button class="btn primary" data-action="invoice-new">＋ FACTURA</button><button class="btn" data-action="bulk-drafts">CAMBIO MASIVO BORRADORES</button><button class="btn" data-action="bulk-issued">CORREGIR PRECIOS EMITIDAS</button>`)}
  <div class="kpis">${kpi('BORRADORES',String(list.filter(i=>i.status==='draft').length))}${kpi('EMITIDAS',String(list.filter(i=>i.status==='issued').length))}${kpi('PENDIENTE',money(list.filter(i=>!['draft','void'].includes(i.status)).reduce((s,i)=>s+calcInvoice(i).pending,0)))}${kpi('RECTIFICATIVAS',String(list.filter(i=>['credit','debit'].includes(i.type)).length))}</div>
  ${table(['SEL.','Nº','FECHA','CLIENTE','ESTADO','BASE','IVA','TOTAL','PENDIENTE','ACCIONES'],list.map(i=>{const x=calcInvoice(i),c=client(i.clientId)||i.clientSnapshot||{};return `<tr><td><input class="inv-check" type="checkbox" value="${i.id}"></td><td><b>${esc(i.number||'BORRADOR')}</b></td><td>${esc(i.date)}</td><td>${esc(c.name||'')}</td><td>${badge(invoiceStatus(i),i.status==='void'?'bad':x.pending<=0?'good':'warn')}</td><td>${money(x.base)}</td><td>${money(x.vatTotal)}</td><td>${money(x.total)}</td><td>${money(x.pending)}</td><td><button class="btn mini" data-inv-open="${i.id}">${i.status==='draft'?'EDITAR':'VER'}</button> <button class="btn mini" data-inv-pdf="${i.id}">PDF</button>${i.status==='issued'&&!['credit','debit'].includes(i.type)?` <button class="btn mini" data-inv-rect="${i.id}">RECTIFICAR</button> <button class="btn mini bad" data-inv-void="${i.id}">ANULAR</button>`:''}</td></tr>`}))}`;
}

export function bulkDraftPrices(){
  const ids=[...document.querySelectorAll('.inv-check:checked')].map(x=>x.value),drafts=st().invoices.filter(i=>ids.includes(i.id)&&i.status==='draft');if(!drafts.length)return toast('SELECCIONA BORRADORES','bad');
  const m=modal('CAMBIO MASIVO DE PRECIOS · BORRADORES',`<div class="form-grid three"><label>PRODUCTO<select id="bpProd">${productOpts()}</select></label><label>OPERACIÓN<select id="bpMode"><option value="delta">SUMAR / RESTAR €</option><option value="percent">PORCENTAJE %</option><option value="fixed">FIJAR PRECIO</option></select></label><label>VALOR<input id="bpValue" type="number" step=".01" value="0.10"></label></div><div id="bpPreview"></div><button class="btn primary" id="bpApply">APLICAR A ${drafts.length} BORRADORES</button>`);
  const preview=()=>{const pid=m.querySelector('#bpProd').value,mode=m.querySelector('#bpMode').value,val=Number(m.querySelector('#bpValue').value||0);const rows=[];for(const inv of drafts){for(const l of inv.lines||[]){if(l.productId!==pid)continue;const np=mode==='fixed'?val:mode==='percent'?round2(Number(l.price||0)*(1+val/100)):round2(Number(l.price||0)+val);rows.push(`<tr><td>${esc(inv.number||'BORRADOR')}</td><td>${esc((client(inv.clientId)||inv.clientSnapshot||{}).name||'')}</td><td>${money(l.price)}</td><td>${money(np)}</td></tr>`)}}m.querySelector('#bpPreview').innerHTML=table(['FACTURA','CLIENTE','ANTES','DESPUÉS'],rows)};m.querySelectorAll('select,input').forEach(x=>x.oninput=preview);m.querySelector('#bpApply').onclick=async()=>{try{const pid=m.querySelector('#bpProd').value,mode=m.querySelector('#bpMode').value,val=Number(m.querySelector('#bpValue').value||0);for(const inv of drafts){const lines=(inv.lines||[]).map(l=>{if(l.productId!==pid)return l;const np=mode==='fixed'?val:mode==='percent'?round2(Number(l.price||0)*(1+val/100)):round2(Number(l.price||0)+val);return {...l,price:np}});await saveDraft({...inv,lines},Runtime.user)}toast('BORRADORES ACTUALIZADOS','good');closeModal()}catch(e){toast(e.message,'bad')}};preview();
}

export function bulkIssuedPrices(){
  const ids=[...document.querySelectorAll('.inv-check:checked')].map(x=>x.value),issued=st().invoices.filter(i=>ids.includes(i.id)&&i.status==='issued'&&!['credit','debit'].includes(i.type));if(!issued.length)return toast('SELECCIONA FACTURAS EMITIDAS','bad');
  const m=modal('CORRECCIÓN MASIVA DE PRECIOS · FACTURAS EMITIDAS',`<div class="warning">LAS FACTURAS EMITIDAS NO SE REESCRIBEN. ARW2026 GENERARÁ RECTIFICATIVAS LIGADAS A CADA FACTURA ORIGINAL.</div><div class="form-grid three"><label>PRODUCTO<select id="biProd">${productOpts()}</select></label><label>OPERACIÓN<select id="biMode"><option value="delta">SUMAR / RESTAR €</option><option value="percent">PORCENTAJE %</option><option value="fixed">FIJAR PRECIO</option></select></label><label>VALOR<input id="biValue" type="number" step=".01" value="0.10"></label></div><div id="biPreview"></div><button class="btn primary" id="biApply">GENERAR RECTIFICATIVAS</button>`);
  const changes=()=>{const pid=m.querySelector('#biProd').value,mode=m.querySelector('#biMode').value,val=Number(m.querySelector('#biValue').value||0),out=[];for(const inv of issued){for(const l of inv.lines||[]){if(l.productId!==pid)continue;const old=Number(l.price||0),np=mode==='fixed'?val:mode==='percent'?round2(old*(1+val/100)):round2(old+val),diff=round2(np-old);if(Math.abs(diff)<.001)continue;out.push({inv,line:l,newPrice:np,diff})}}return out};
  const preview=()=>{m.querySelector('#biPreview').innerHTML=table(['FACTURA','CLIENTE','ANTES','NUEVO','DIF.'],changes().map(x=>`<tr><td>${esc(x.inv.number)}</td><td>${esc((client(x.inv.clientId)||x.inv.clientSnapshot||{}).name||'')}</td><td>${money(x.line.price)}</td><td>${money(x.newPrice)}</td><td>${money(x.diff)}</td></tr>`))};m.querySelectorAll('select,input').forEach(x=>x.oninput=preview);
  m.querySelector('#biApply').onclick=async()=>{try{const grouped=new Map();for(const x of changes()){const direction=x.diff>0?'debit':'credit',key=`${x.inv.id}:${direction}`,a=grouped.get(key)||{inv:x.inv,lines:[],direction};a.lines.push({...x.line,id:uid('line'),price:Math.abs(x.diff)});grouped.set(key,a)}for(const g of grouped.values())await createRectification(g.inv,g.lines,'CORRECCIÓN MASIVA DE PRECIO',Runtime.user,g.direction);toast(`${grouped.size} RECTIFICATIVAS GENERADAS`,'good');closeModal()}catch(e){toast(e.message,'bad')}};preview();
}

export function rectificationModal(inv){const x=calcInvoice(inv);const m=modal(`RECTIFICAR ${inv.number}`,`<label class="field">MOTIVO<input id="rReason" value="CORRECCIÓN DE FACTURA"></label>${table(['SEL.','PRODUCTO','CANTIDAD','PRECIO'],x.lines.map((l,i)=>`<tr><td><input type="checkbox" class="rSel" data-i="${i}" checked></td><td>${esc(l.name)}</td><td><input class="rQty" data-i="${i}" type="number" step=".01" value="${l.qty}"></td><td>${money(l.price)}</td></tr>`))}<button class="btn primary" id="rApply">EMITIR RECTIFICATIVA NEGATIVA</button>`);m.querySelector('#rApply').onclick=async()=>{try{const lines=x.lines.filter((_,i)=>m.querySelector(`.rSel[data-i="${i}"]`)?.checked).map((l)=>{const i=x.lines.indexOf(l);return {...l,id:uid('line'),qty:Number(m.querySelector(`.rQty[data-i="${i}"]`).value||0)}}).filter(l=>l.qty>0);const r=await createRectification(inv,lines,m.querySelector('#rReason').value,Runtime.user,'credit');toast(`RECTIFICATIVA ${r.number} EMITIDA`,'good');closeModal();downloadInvoice(r,client(r.clientId)||r.clientSnapshot,settings())}catch(e){toast(e.message,'bad')}}}

export async function handleVoid(inv){const reason=prompt(`MOTIVO DE ANULACIÓN DE ${inv.number}`);if(!reason)return;const returnStock=confirm('¿DEVOLVER LA MERCANCÍA AL STOCK?');try{await voidInvoice(inv,{reason,returnStock},Runtime.user);toast('FACTURA ANULADA CON TRAZABILIDAD','good')}catch(e){toast(e.message,'bad')}}

export function sendView(){const date=window.ARW_SEND_DATE||today(),list=st().invoices.filter(i=>i.date===date&&!['draft','void'].includes(i.status));return `${section('ENVÍO DEL DÍA','DESCARGA ZIP CON TODAS LAS FACTURAS Y CONTROL DE ENVÍO',`<button class="btn primary" data-action="zip-day">DESCARGAR ZIP DEL DÍA</button>`)}<div class="panel"><label class="field">FECHA<input id="sendDate" type="date" value="${date}"></label></div><br>${table(['FACTURA','CLIENTE','TOTAL','ESTADO','ACCIONES'],list.map(i=>{const c=client(i.clientId)||i.clientSnapshot||{},x=calcInvoice(i);return `<tr><td>${esc(i.number)}</td><td>${esc(c.name||'')}</td><td>${money(x.total)}</td><td>${i.sentAt?badge('ENVIADA','good'):badge('PENDIENTE','warn')}</td><td><button class="btn mini" data-inv-pdf="${i.id}">PDF</button> <button class="btn mini" data-wa="${i.id}">WHATSAPP</button></td></tr>`}))}`}
export async function zipDay(){const date=window.ARW_SEND_DATE||today(),list=st().invoices.filter(i=>i.date===date&&!['draft','void'].includes(i.status));if(!list.length)return toast('NO HAY FACTURAS PARA ESA FECHA','bad');try{await downloadDayZip(list,activeClients(),settings(),date);toast(`ZIP CON ${list.length} FACTURAS GENERADO`,'good')}catch(e){toast(e.message,'bad')}}

export function paymentsView(){const list=[...st().payments].sort((a,b)=>String(b.date).localeCompare(String(a.date)));const pending=st().invoices.filter(i=>!['draft','void'].includes(i.status)).reduce((s,i)=>s+calcInvoice(i).pending,0);return `${section('COBROS','PAGOS PARCIALES · VARIAS FACTURAS · SALDOS',`<button class="btn primary" data-action="payment-new">＋ COBRO</button>`)}<div class="kpis">${kpi('DEUDA TOTAL',money(pending))}${kpi('COBROS HOY',money(list.filter(p=>p.date===today()).reduce((s,p)=>s+Number(p.amount||0),0)))}${kpi('MOVIMIENTOS',String(list.length))}${kpi('CLIENTES CON DEUDA',String(new Set(st().invoices.filter(i=>calcInvoice(i).pending>0).map(i=>i.clientId)).size))}</div>${table(['FECHA','CLIENTE','IMPORTE','MÉTODO','FACTURAS'],list.map(p=>`<tr><td>${p.date}</td><td>${esc(client(p.clientId)?.name||'')}</td><td>${money(p.amount)}</td><td>${esc(upper(p.method))}</td><td>${(p.allocations||[]).map(a=>st().invoices.find(i=>i.id===a.invoiceId)?.number||'').join(', ')}</td></tr>`))}`}
export function paymentModal(){const m=modal('REGISTRAR COBRO',`<label class="field">CLIENTE<select id="payClient">${clientOpts()}</select></label><div id="payInvoices"></div>`);m.querySelector('#payClient').onchange=()=>{const cid=m.querySelector('#payClient').value,invs=st().invoices.filter(i=>i.clientId===cid&&!['draft','void'].includes(i.status)&&calcInvoice(i).pending>0).sort((a,b)=>String(a.date).localeCompare(String(b.date)));m.querySelector('#payInvoices').innerHTML=`<div class="form-grid three"><label>IMPORTE RECIBIDO<input id="payAmount" type="number" step=".01"></label><label>MÉTODO<select id="payMethod"><option>efectivo</option><option>transferencia</option><option>tarjeta</option><option>bizum</option></select></label><label>FECHA<input id="payDate" type="date" value="${today()}"></label></div>${table(['SEL.','FACTURA','PENDIENTE','APLICAR'],invs.map(i=>`<tr><td><input class="pSel" type="checkbox" value="${i.id}" checked></td><td>${i.number}</td><td>${money(calcInvoice(i).pending)}</td><td><input class="pApply" data-id="${i.id}" type="number" step=".01" value="${calcInvoice(i).pending}"></td></tr>`))}<button class="btn primary" id="paySave">REGISTRAR COBRO</button>`;m.querySelector('#paySave').onclick=async()=>{try{const amount=Number(m.querySelector('#payAmount').value||0);if(amount<=0)throw new Error('INDICA EL IMPORTE RECIBIDO');let remaining=amount,alloc=[];for(const s of m.querySelectorAll('.pSel:checked')){if(remaining<=0)break;const inv=invs.find(i=>i.id===s.value),max=Math.min(calcInvoice(inv).pending,Number(m.querySelector(`.pApply[data-id="${s.value}"]`).value||0),remaining);if(max>0){alloc.push({invoiceId:s.value,amount:round2(max)});remaining=round2(remaining-max)}}await recordPayment({clientId:cid,date:m.querySelector('#payDate').value,amount:round2(amount-remaining),method:m.querySelector('#payMethod').value,allocations:alloc},Runtime.user);toast('COBRO REGISTRADO','good');closeModal()}catch(e){toast(e.message,'bad')}}};}

export function clientStatement(c){const invs=st().invoices.filter(i=>i.clientId===c.id&&!['draft'].includes(i.status)),pays=st().payments.filter(p=>p.clientId===c.id);statementPdf(c,invs,pays)}
