import {Runtime} from './runtime.js';
import {section,table,kpi,badge,modal,closeModal,toast,optionList,money,esc,exportXlsx} from './ui.js';
import {calcInvoice,stockQuantity,stockText,round2,today,now,uid,upper,normalize,calcLine} from './domain.js';
import {saveEntity} from './firebase.js';
import {clientStatement} from './views-sales.js';
import {parsePurchaseText,purchaseCalculatedTotals,chatGptPurchaseInstruction} from './importers.js';
const st=()=>Runtime.state, product=id=>Runtime.product(id), client=id=>Runtime.client(id), settings=()=>Runtime.settings();
const products=()=>st().products.filter(p=>p.active!==false&&!p.archived).sort((a,b)=>String(a.code).localeCompare(String(b.code)));
const clients=()=>st().clients.filter(c=>c.active!==false&&!c.archived).sort((a,b)=>String(a.name).localeCompare(String(b.name)));
const suppliers=()=>st().suppliers.filter(s=>s.active!==false&&!s.archived).sort((a,b)=>String(a.name).localeCompare(String(b.name)));
const productOpts=(sel='')=>`<option value="">SELECCIONAR</option>${optionList(products(),sel,p=>`${p.code} · ${p.name}`)}`;
const supplierOpts=(sel='')=>`<option value="">SIN PROVEEDOR</option>${optionList(suppliers(),sel)}`;

export function productsView(){const q=window.ARW_PRODUCT_Q||'',list=products();const dupeNames=new Map();for(const p of products()){const k=normalize(p.name);dupeNames.set(k,(dupeNames.get(k)||0)+1)}return `${section('PRODUCTOS','CATÁLOGO MAESTRO · MODO · KG/CAJA · COMPRA · VENTA · RECOMENDADO · IVA',`<button class="btn primary" data-action="product-new">＋ PRODUCTO</button><button class="btn" data-action="products-export">EXPORTAR EXCEL</button>`)}<div class="panel"><input id="productSearch" placeholder="BUSCAR CÓDIGO, PRODUCTO O ALIAS" value="${esc(q)}" autocomplete="off"></div><br>${table(['CÓDIGO','PRODUCTO','MODO','KG/CAJA','COMPRA','VENTA','RECOMENDADO','IVA','PROVEEDOR','ESTADO','ACCIONES'],list.map(p=>{const bad=p.mode==='caja_kg'&&!Number(p.kgPerBox),dup=dupeNames.get(normalize(p.name))>1;return `<tr><td><b>${esc(p.code)}</b></td><td><b>${esc(p.name)}</b><br><small>${esc(p.aliases||'')}</small></td><td>${badge(p.mode,bad?'bad':'')}</td><td>${Number(p.kgPerBox||0)}</td><td>${money(p.buyPrice)}</td><td>${money(p.sellPrice)}</td><td>${money(p.recommended)}</td><td><b>${p.vat}%</b></td><td>${esc(p.supplier||'')}</td><td>${bad?badge('FALTA KG/CAJA','bad'):dup?badge('NOMBRE DUPLICADO','warn'):badge('OK','good')}</td><td><button class="btn mini" data-product-edit="${p.id}">EDITAR</button><button class="btn mini" data-product-360="${p.id}">360º</button></td></tr>`}))}`}
export function productModal(existing=null){const p=existing?structuredClone(existing):{id:uid('p'),code:'',name:'',aliases:'',mode:'kg',kgPerBox:0,buyPrice:0,sellPrice:0,recommended:0,vat:4,supplier:'',active:true};const m=modal(existing?'EDITAR PRODUCTO':'NUEVO PRODUCTO',`<form id="pf"><div class="form-grid"><label>CÓDIGO<input name="code" value="${esc(p.code)}" required></label><label>NOMBRE<input name="name" value="${esc(p.name)}" required></label><label>MODO<select name="mode"><option value="caja_kg">CAJA × KG</option><option value="caja_fija">CAJA FIJA</option><option value="kg">KG</option><option value="ud">UD</option><option value="manojo">MANOJO</option></select></label><label>KG/CAJA<input name="kg" type="number" step=".01" value="${Number(p.kgPerBox||0)}"></label><label>COMPRA<input name="buy" type="number" step=".01" value="${Number(p.buyPrice||0)}"></label><label>VENTA<input name="sell" type="number" step=".01" value="${Number(p.sellPrice||0)}"></label><label>RECOMENDADO<input name="rec" type="number" step=".01" value="${Number(p.recommended||0)}"></label><label>IVA<select name="vat">${[0,4,10,21].map(v=>`<option value="${v}" ${Number(p.vat)===v?'selected':''}>${v}%</option>`).join('')}</select></label><label>PROVEEDOR<input name="supplier" value="${esc(p.supplier||'')}"></label></div><label class="field">ALIAS<input name="aliases" value="${esc(p.aliases||'')}"></label><button class="btn primary">GUARDAR</button></form>`);m.querySelector('[name=mode]').value=p.mode;m.querySelector('#pf').onsubmit=async e=>{e.preventDefault();try{const f=new FormData(e.currentTarget),next={...p,code:upper(f.get('code')).replace(/\s/g,''),name:upper(f.get('name')),aliases:f.get('aliases'),mode:f.get('mode'),kgPerBox:Number(f.get('kg')||0),buyPrice:Number(f.get('buy')||0),sellPrice:Number(f.get('sell')||0),recommended:Number(f.get('rec')||0),vat:Number(f.get('vat')||0),supplier:f.get('supplier'),active:true};if(next.mode==='caja_kg'&&!next.kgPerBox)throw new Error('UN PRODUCTO CAJA × KG NECESITA KG/CAJA');await saveEntity('products',next,'PRODUCT_SAVE',Runtime.user);toast('PRODUCTO GUARDADO Y SINCRONIZADO','good');closeModal()}catch(err){toast(err.message,'bad')}}}
export function product360(p){const moves=st().stockMoves.filter(m=>m.productId===p.id),qty=stockQuantity(moves,p.id),sales=[];for(const i of st().invoices.filter(i=>!['draft','void'].includes(i.status))){for(const l of i.lines||[])if(l.productId===p.id)sales.push({invoice:i,line:calcLine(l)})}const byClient=new Map();for(const s of sales){const c=client(s.invoice.clientId)||s.invoice.clientSnapshot||{};const k=c.name||s.invoice.clientId,old=byClient.get(k)||{qty:0,sales:0,prices:[]};old.qty+=s.line.billedQty;old.sales+=s.line.base;old.prices.push(s.line.price);byClient.set(k,old)}modal(`PRODUCTO 360º · ${p.code} · ${p.name}`,`<div class="kpis">${kpi('STOCK',stockText(p,qty))}${kpi('VALOR COSTE',money(qty*Number(p.buyPrice||0)))}${kpi('VENTA POTENCIAL',money(qty*Number(p.sellPrice||0)))}${kpi('FACTURAS',String(sales.length))}</div>${p.mode==='caja_kg'?`<div class="success">REGLA DE FACTURACIÓN: 1 CAJA = ${p.kgPerBox} KG · LAS CAJAS SE MULTIPLICAN AUTOMÁTICAMENTE.</div>`:''}${table(['CLIENTE','CANTIDAD FACTURADA','VENTAS','ÚLTIMO PRECIO'],[...byClient].map(([name,v])=>`<tr><td>${esc(name)}</td><td>${round2(v.qty)}</td><td>${money(v.sales)}</td><td>${money(v.prices.at(-1)||0)}</td></tr>`))}`)}

function clientStats(c){const inv=st().invoices.filter(i=>i.clientId===c.id&&!['draft','void'].includes(i.status)).map(calcInvoice);return{billed:inv.reduce((s,i)=>s+i.total,0),pending:inv.reduce((s,i)=>s+i.pending,0),vat:inv.reduce((s,i)=>s+i.vatTotal,0),re:inv.reduce((s,i)=>s+Number(i.equivalenceTotal||0),0),count:inv.length}}
export function clientsView(){const q=window.ARW_CLIENT_Q||'',list=clients();return `${section('CLIENTES 360º','CARTERA MAESTRA · PRECIOS PERSONALIZADOS · HISTORIAL · DEUDA · RECARGO DE EQUIVALENCIA',`<button class="btn primary" data-action="client-new">＋ CLIENTE</button><button class="btn" data-action="clients-export">EXPORTAR EXCEL</button>`)}<div class="panel"><input id="clientSearch" placeholder="BUSCAR CLIENTE, NIF O DIRECCIÓN" value="${esc(q)}" autocomplete="off"></div><br>${table(['CLIENTE','NIF/CIF','DIRECCIÓN','R.E.','TRANSPORTE','COMISIÓN','FACTURADO','PENDIENTE','ACCIONES'],list.map(c=>{const s=clientStats(c);return `<tr><td><b>${esc(c.name)}</b></td><td>${esc(c.nif||'')}</td><td>${esc(c.address||'')}</td><td>${c.equivalenceSurcharge?badge('SÍ','warn'):'NO'}</td><td>${Number(c.transportPercent||0)?c.transportPercent+'%':'NO'}</td><td>${Number(c.commissionPercent||0)?c.commissionPercent+'%':'NO'}</td><td>${money(s.billed)}</td><td>${money(s.pending)}</td><td><button class="btn mini" data-client-edit="${c.id}">EDITAR</button><button class="btn mini primary" data-client-360="${c.id}">360º</button></td></tr>`}))}`}
export function clientModal(existing=null){const c=existing?structuredClone(existing):{id:uid('c'),name:'',nif:'',address:'',transportPercent:10,commissionPercent:0,paymentMethod:'efectivo',phone:'',whatsapp:'',email:'',prices:{},dueDays:0,creditLimit:0,classification:'C',equivalenceSurcharge:false,active:true};const m=modal(existing?'EDITAR CLIENTE':'NUEVO CLIENTE',`<form id="cf"><div class="form-grid"><label>NOMBRE / RAZÓN SOCIAL<input name="name" value="${esc(c.name)}" required></label><label>NIF/CIF<input name="nif" value="${esc(c.nif||'')}"></label><label>DIRECCIÓN<input name="address" value="${esc(c.address||'')}"></label><label>TELÉFONO<input name="phone" value="${esc(c.phone||'')}"></label><label>WHATSAPP<input name="whatsapp" value="${esc(c.whatsapp||'')}"></label><label>EMAIL<input name="email" value="${esc(c.email||'')}"></label><label>TRANSPORTE %<input name="transport" type="number" step=".01" value="${Number(c.transportPercent||0)}"></label><label>COMISIÓN %<input name="commission" type="number" step=".01" value="${Number(c.commissionPercent||0)}"></label><label>FORMA PAGO<select name="payment"><option>efectivo</option><option>transferencia</option><option>tarjeta</option><option>pendiente</option></select></label><label>DÍAS CRÉDITO<input name="dueDays" type="number" value="${Number(c.dueDays||0)}"></label><label>LÍMITE CRÉDITO<input name="creditLimit" type="number" step=".01" value="${Number(c.creditLimit||0)}"></label><label class="check re-check"><input name="equivalence" type="checkbox" ${c.equivalenceSurcharge?'checked':''}> RECARGO DE EQUIVALENCIA</label></div><div class="muted" style="margin:8px 0 14px">ACTÍVALO SOLO SI EL CLIENTE TE HA COMUNICADO QUE ESTÁ EN RECARGO DE EQUIVALENCIA. ARW2026 APLICARÁ 0,5% / 1,4% / 5,2% SEGÚN IVA 4% / 10% / 21%.</div><button class="btn primary">GUARDAR</button></form>`);m.querySelector('[name=payment]').value=c.paymentMethod||'efectivo';m.querySelector('#cf').onsubmit=async e=>{e.preventDefault();try{const f=new FormData(e.currentTarget),next={...c,name:upper(f.get('name')),nif:upper(f.get('nif')),address:upper(f.get('address')),phone:f.get('phone'),whatsapp:f.get('whatsapp'),email:f.get('email'),transportPercent:Number(f.get('transport')||0),commissionPercent:Number(f.get('commission')||0),paymentMethod:f.get('payment'),dueDays:Number(f.get('dueDays')||0),creditLimit:Number(f.get('creditLimit')||0),equivalenceSurcharge:f.get('equivalence')==='on',active:true};await saveEntity('clients',next,'CLIENT_SAVE',Runtime.user);toast('CLIENTE GUARDADO Y SINCRONIZADO','good');closeModal()}catch(err){toast(err.message,'bad')}}}
export function client360(c){const s=clientStats(c),invs=st().invoices.filter(i=>i.clientId===c.id).sort((a,b)=>String(b.date).localeCompare(String(a.date))),orders=st().orders.filter(o=>o.clientId===c.id).sort((a,b)=>String(b.date).localeCompare(String(a.date)));const m=modal(`CLIENTE 360º · ${c.name}`,`<div class="kpis">${kpi('FACTURADO',money(s.billed))}${kpi('PENDIENTE',money(s.pending))}${kpi('IVA',money(s.vat))}${kpi('RECARGO EQ.',money(s.re))}</div>${c.equivalenceSurcharge?'<div class="warning"><b>RECARGO DE EQUIVALENCIA ACTIVO</b></div>':''}<div class="actions"><button class="btn" id="statement">ESTADO DE CUENTA PDF</button><button class="btn primary" id="newSpecial">＋ PRECIO ESPECIAL</button></div><br><div class="grid2"><div><h3>FACTURAS</h3>${table(['Nº','FECHA','TOTAL','PENDIENTE'],invs.map(i=>{const x=calcInvoice(i);return `<tr><td>${esc(i.number||'BORRADOR')}</td><td>${i.date}</td><td>${money(x.total)}</td><td>${money(x.pending)}</td></tr>`}))}</div><div><h3>PRECIOS ESPECIALES</h3>${table(['PRODUCTO','PRECIO','ACCIONES'],Object.entries(c.prices||{}).map(([pid,v])=>`<tr><td>${esc(product(pid)?.name||pid)}</td><td>${money(typeof v==='number'?v:v.price)}</td><td><button class="btn mini" data-price-edit="${pid}">EDITAR</button></td></tr>`))}</div></div>`);m.querySelector('#statement').onclick=()=>clientStatement(c);m.querySelector('#newSpecial').onclick=()=>specialPriceModal(c);m.querySelectorAll('[data-price-edit]').forEach(b=>b.onclick=()=>specialPriceModal(c,b.dataset.priceEdit));}
export function specialPriceModal(c,pid=''){const cur=pid?(c.prices?.[pid]?.price??c.prices?.[pid]??product(pid)?.sellPrice):0;const m=modal(`PRECIO ESPECIAL · ${c.name}`,`<form id="sp"><label class="field">PRODUCTO<select name="pid">${productOpts(pid)}</select></label><label class="field">PRECIO<input name="price" type="number" step=".01" value="${Number(cur||0)}"></label><button class="btn primary">GUARDAR</button></form>`,true);m.querySelector('[name=pid]').onchange=e=>m.querySelector('[name=price]').value=Number(c.prices?.[e.target.value]?.price??c.prices?.[e.target.value]??product(e.target.value)?.sellPrice??0);m.querySelector('#sp').onsubmit=async e=>{e.preventDefault();const f=new FormData(e.currentTarget),p=f.get('pid'),price=Number(f.get('price')||0),old=Number(c.prices?.[p]?.price??c.prices?.[p]??product(p)?.sellPrice??0);await saveEntity('clients',{...c,prices:{...(c.prices||{}),[p]:{price,since:today()}}},'CLIENT_PRICE',Runtime.user);await saveEntity('priceHistory',{id:uid('ph'),clientId:c.id,productId:p,date:today(),oldPrice:old,newPrice:price,at:now()},'PRICE_HISTORY',Runtime.user);toast('PRECIO PERSONALIZADO GUARDADO','good');closeModal()}}

export function stockView(){const list=products().map(p=>{const qty=stockQuantity(st().stockMoves,p.id);return{p,qty,value:qty*Number(p.buyPrice||0),potential:qty*Number(p.sellPrice||0)}});return `${section('STOCK','FÍSICO · CAJAS + KG · VALOR DE COSTE · MOVIMIENTOS',`<button class="btn primary" data-action="stock-adjust">＋ AJUSTE</button><button class="btn" data-action="stock-export">EXPORTAR</button>`)}<div class="kpis">${kpi('VALOR STOCK',money(list.reduce((s,x)=>s+x.value,0)))}${kpi('PRODUCTOS',String(list.length))}${kpi('STOCK NEGATIVO',String(list.filter(x=>x.qty<0).length))}${kpi('MOVIMIENTOS',String(st().stockMoves.length))}</div>${table(['CÓDIGO','PRODUCTO','STOCK','COMPRA','VALOR','VENTA POTENCIAL','ACCIONES'],list.map(({p,qty,value,potential})=>`<tr><td>${p.code}</td><td><b>${esc(p.name)}</b></td><td>${qty<0?badge(stockText(p,qty),'bad'):`<b>${esc(stockText(p,qty))}</b>`}</td><td>${money(p.buyPrice)}</td><td>${money(value)}</td><td>${money(potential)}</td><td><button class="btn mini" data-product-360="${p.id}">360º</button></td></tr>`))}`}
export function stockAdjustModal(){const m=modal('AJUSTE DE STOCK',`<form id="sa"><div class="form-grid three"><label>PRODUCTO<select name="pid">${productOpts()}</select></label><label>CANTIDAD FÍSICA (+/-)<input name="qty" type="number" step=".01"></label><label>UBICACIÓN<select name="location"><option>ALMACEN</option><option>FURGONETA</option><option>SAN PABLO</option><option>SAN LESMES</option><option>SANTIAGO</option></select></label></div><label class="field">MOTIVO<input name="note" required></label><button class="btn primary">REGISTRAR MOVIMIENTO</button></form>`,true);m.querySelector('#sa').onsubmit=async e=>{e.preventDefault();const f=new FormData(e.currentTarget),pid=f.get('pid'),qty=Number(f.get('qty')||0);if(!pid||!qty)return toast('PRODUCTO Y CANTIDAD OBLIGATORIOS','bad');await saveEntity('stockMoves',{id:uid('sm'),productId:pid,qty,type:'adjustment',location:f.get('location'),note:upper(f.get('note')),date:today(),createdAt:now()},'STOCK_ADJUST',Runtime.user);toast('STOCK ACTUALIZADO','good');closeModal()}}

export function suppliersView(){return `${section('PROVEEDORES','COMPRAS · COSTES · HISTÓRICO',`<button class="btn primary" data-action="supplier-new">＋ PROVEEDOR</button>`)}${table(['PROVEEDOR','COMPRAS','TOTAL','ÚLTIMA COMPRA','ACCIONES'],suppliers().map(s=>{const ps=st().purchases.filter(p=>p.supplierId===s.id),total=ps.reduce((a,p)=>a+Number(p.total||0),0),last=[...ps].sort((a,b)=>String(b.date).localeCompare(String(a.date)))[0];return `<tr><td><b>${esc(s.name)}</b></td><td>${ps.length}</td><td>${money(total)}</td><td>${last?.date||'—'}</td><td><button class="btn mini" data-supplier-edit="${s.id}">EDITAR</button></td></tr>`}))}`}
export function supplierModal(existing=null){const s=existing||{id:uid('s'),name:'',phone:'',email:'',active:true};const m=modal(existing?'EDITAR PROVEEDOR':'NUEVO PROVEEDOR',`<form id="sf"><label class="field">NOMBRE<input name="name" value="${esc(s.name)}" required></label><label class="field">TELÉFONO<input name="phone" value="${esc(s.phone||'')}"></label><label class="field">EMAIL<input name="email" value="${esc(s.email||'')}"></label><button class="btn primary">GUARDAR</button></form>`,true);m.querySelector('#sf').onsubmit=async e=>{e.preventDefault();const f=new FormData(e.currentTarget);await saveEntity('suppliers',{...s,name:upper(f.get('name')),phone:f.get('phone'),email:f.get('email'),active:true},'SUPPLIER_SAVE',Runtime.user);toast('PROVEEDOR GUARDADO','good');closeModal()}}

function purchaseLineRow(l={}){return `<tr><td><select class="puProd">${productOpts(l.productId)}</select></td><td><input class="puQty" type="number" step=".01" value="${Number(l.qty||0)}"></td><td><input class="puKg" type="number" step=".01" value="${Number(l.kgPerBox||0)}"></td><td><input class="puPrice" type="number" step=".01" value="${Number(l.price||0)}"></td><td><select class="puVat">${[0,4,10,21].map(v=>`<option value="${v}" ${Number(l.vat??4)===v?'selected':''}>${v}%</option>`).join('')}</select></td><td class="puBase money">—</td><td><button class="btn mini bad" type="button" data-pu-del>×</button></td></tr>`}
export function purchasesView(){const list=[...st().purchases].sort((a,b)=>String(b.date).localeCompare(String(a.date)));return `${section('COMPRAS','ENTRADA DE MERCANCÍA · TEXTO CHATGPT · ACTUALIZA STOCK Y COSTE',`<button class="btn primary" data-action="purchase-new">＋ COMPRA</button><button class="btn" data-action="purchase-import">PEGAR TEXTO CHATGPT</button><button class="btn" data-action="purchase-prompt">COPIAR INSTRUCCIÓN CHATGPT</button>`)}${table(['FECHA','PROVEEDOR','FACTURA','LÍNEAS','BASE','IVA','TRANSPORTE','TOTAL'],list.map(p=>`<tr><td>${p.date}</td><td>${esc(st().suppliers.find(s=>s.id===p.supplierId)?.name||p.supplierName||'')}</td><td>${esc(p.number||'')}</td><td>${p.lines?.length||0}</td><td>${money(p.base||0)}</td><td>${money(p.vatTotal||0)}</td><td>${money(p.transport||0)}</td><td><b>${money(p.total)}</b></td></tr>`))}`}
export function purchaseModal(preset=null){
  const seed=preset||{},seedLines=(seed.lines||[]).map(l=>({...l}));while(seedLines.length<5)seedLines.push({});
  const m=modal(seed.rawText?'REVISAR COMPRA IMPORTADA':'REGISTRAR COMPRA',`<form id="puf"><div class="form-grid"><label>PROVEEDOR<select name="supplierId">${supplierOpts(seed.supplierId||'')}</select></label><label>FECHA<input name="date" type="date" value="${seed.date||today()}"></label><label>Nº FACTURA<input name="number" value="${esc(seed.number||'')}"></label><label>TRANSPORTE / PORTES €<input name="transport" type="number" step=".01" value="${Number(seed.transport||0)}"></label><label>DESCUENTO %<input name="discount" type="number" step=".01" value="${Number(seed.discount||0)}"></label><label>TOTAL FACTURA ORIGEN €<input name="expectedTotal" type="number" step=".01" value="${Number(seed.expectedTotal||0)}"></label></div><div class="table-wrap"><table><thead><tr><th>PRODUCTO</th><th>CANT.</th><th>KG/CAJA</th><th>PRECIO COMPRA</th><th>IVA</th><th>BASE</th><th></th></tr></thead><tbody id="puRows">${seedLines.map(purchaseLineRow).join('')}</tbody></table></div><div id="puSummary"></div>${seed.rawText?'<details class="panel import-source"><summary>TEXTO ORIGINAL IMPORTADO</summary><pre>'+esc(seed.rawText)+'</pre></details>':''}<div class="actions" style="margin-top:10px"><button class="btn" type="button" id="puAdd">＋ LÍNEA</button><button class="btn primary">GUARDAR COMPRA</button></div></form>`);
  const supplierSelect=m.querySelector('[name=supplierId]');if(seed.supplierId)supplierSelect.value=seed.supplierId;
  const collect=()=>[...m.querySelectorAll('#puRows tr')].map(tr=>{const pid=tr.querySelector('.puProd').value;if(!pid)return null;const p=product(pid),qty=Number(tr.querySelector('.puQty').value||0),kg=Number(tr.querySelector('.puKg').value||0),price=Number(tr.querySelector('.puPrice').value||0),vat=Number(tr.querySelector('.puVat').value||0);return{productId:pid,code:p.code,name:p.name,mode:p.mode,qty,kgPerBox:kg,price,vat}}).filter(l=>l&&l.qty>0);
  const refresh=()=>{const t=purchaseCalculatedTotals(collect(),Number(m.querySelector('[name=transport]').value||0),Number(m.querySelector('[name=discount]').value||0));[...m.querySelectorAll('#puRows tr')].forEach((tr,i)=>{const pid=tr.querySelector('.puProd').value;if(!pid){tr.querySelector('.puBase').textContent='—';return;}const line=collect().find(l=>l.productId===pid&&Number(l.qty)===Number(tr.querySelector('.puQty').value||0));if(line){const one=purchaseCalculatedTotals([line],0,0);tr.querySelector('.puBase').textContent=money(one.productBase)}});const expected=Number(m.querySelector('[name=expectedTotal]').value||0),diff=expected?round2(t.total-expected):0;m.querySelector('#puSummary').innerHTML=`<div class="purchase-summary"><span>BASE <b>${money(t.base)}</b></span><span>IVA <b>${money(t.vat)}</b></span><span>TRANSPORTE <b>${money(t.transport)}</b></span><strong>TOTAL CALCULADO ${money(t.total)}</strong>${expected?`<span class="${Math.abs(diff)<=.05?'success-inline':'bad-inline'}">FACTURA ORIGEN ${money(expected)} · DIF. ${money(diff)}</span>`:''}</div>`;return t;};
  m.querySelector('#puAdd').onclick=()=>{m.querySelector('#puRows').insertAdjacentHTML('beforeend',purchaseLineRow());refresh()};
  m.addEventListener('click',e=>{if(e.target.matches('[data-pu-del]')){e.target.closest('tr').remove();refresh()}});
  m.addEventListener('change',e=>{if(e.target.matches('.puProd')){const p=product(e.target.value),tr=e.target.closest('tr');tr.querySelector('.puKg').value=Number(p?.kgPerBox||0);tr.querySelector('.puPrice').value=Number(p?.buyPrice||0);tr.querySelector('.puVat').value=Number(p?.vat||4)}refresh()});m.addEventListener('input',e=>{if(e.target.closest('#puf'))refresh()});
  m.querySelector('#puf').onsubmit=async e=>{e.preventDefault();try{const f=new FormData(e.currentTarget),lines=collect();if(!lines.length)throw new Error('AÑADE PRODUCTOS');const supplierId=f.get('supplierId'),number=upper(f.get('number'));if(number&&st().purchases.some(p=>p.supplierId===supplierId&&upper(p.number)===number))throw new Error('YA EXISTE UNA COMPRA CON ESE PROVEEDOR Y Nº DE FACTURA');const totals=purchaseCalculatedTotals(lines,Number(f.get('transport')||0),Number(f.get('discount')||0)),expected=Number(f.get('expectedTotal')||0);if(expected&&Math.abs(totals.total-expected)>.05&&!confirm(`EL TOTAL CALCULADO ${money(totals.total)} NO COINCIDE CON LA FACTURA ${money(expected)}. ¿GUARDAR IGUAL?`))return;const id=uid('pur'),supplier=st().suppliers.find(s=>s.id===supplierId);await saveEntity('purchases',{id,supplierId,supplierName:supplier?.name||seed.supplierName||'',date:f.get('date'),number,lines:totals.lines,productBase:totals.productBase,discount:Number(f.get('discount')||0),transport:totals.transport,base:totals.base,vatTotal:totals.vat,total:totals.total,expectedTotal:expected,sourceText:seed.rawText||''},'PURCHASE',Runtime.user);for(const l of totals.lines){await saveEntity('stockMoves',{id:uid('sm'),productId:l.productId,qty:l.stockQty,type:'purchase',location:'ALMACEN',sourceId:id,note:`COMPRA ${number}`,date:f.get('date'),createdAt:now()},'PURCHASE_STOCK',Runtime.user);const old=Number(product(l.productId)?.buyPrice||0);await saveEntity('products',{...product(l.productId),buyPrice:l.price},'COST_UPDATE',Runtime.user);await saveEntity('priceHistory',{id:uid('ph'),type:'cost',productId:l.productId,date:f.get('date'),oldPrice:old,newPrice:l.price,source:'COMPRA',purchaseId:id,at:now()},'COST_HISTORY',Runtime.user)}toast('COMPRA GUARDADA · STOCK Y COSTES ACTUALIZADOS','good');closeModal()}catch(err){toast(err.message,'bad')}};refresh();
}

export function purchaseImportModal(){
  const m=modal('PEGAR COMPRA DESDE CHATGPT',`<div class="grid2"><div><label class="field">PEGA AQUÍ ARW2026_COMPRA_V1<textarea id="purchaseImportText" class="import-text" placeholder="ARW2026_COMPRA_V1\nPROVEEDOR=...\nFACTURA=...\n..."></textarea></label><div class="actions"><button class="btn" id="pastePurchase" type="button">PEGAR PORTAPAPELES</button><button class="btn" id="previewPurchase" type="button">INTERPRETAR</button></div></div><div><h3>VISTA PREVIA</h3><div id="purchaseImportPreview" class="panel">PEGA EL TEXTO Y PULSA INTERPRETAR.</div></div></div><div class="modal-actions"><button class="btn primary" id="reviewPurchase" disabled>ABRIR REVISIÓN DE COMPRA</button></div>`);
  let parsed=null;const preview=()=>{parsed=parsePurchaseText(m.querySelector('#purchaseImportText').value,products(),suppliers());const t=purchaseCalculatedTotals(parsed.lines,parsed.transport,parsed.discount);const rows=parsed.lines.map(l=>`<tr><td>${esc(l.code)}</td><td><b>${esc(l.name)}</b></td><td>${l.qty}</td><td>${l.mode==='caja_kg'?`${l.kgPerBox} KG/CAJA`:upper(l.mode)}</td><td>${money(l.price)}</td><td>${l.vat}%</td></tr>`);m.querySelector('#purchaseImportPreview').innerHTML=`<p><b>PROVEEDOR:</b> ${esc(parsed.supplierName||'NO IDENTIFICADO')}</p><p><b>FACTURA:</b> ${esc(parsed.number||'')}</p>${table(['CÓD.','PRODUCTO','CANT.','MODO','PRECIO','IVA'],rows)}<div class="purchase-summary"><strong>TOTAL CALCULADO ${money(t.total)}</strong>${parsed.expectedTotal?`<span>FACTURA ORIGEN ${money(parsed.expectedTotal)}</span>`:''}</div>${parsed.unrecognized.length?`<div class="danger"><b>NO RECONOCIDOS:</b><br>${parsed.unrecognized.map(esc).join('<br>')}</div>`:'<div class="success">TODAS LAS LÍNEAS RECONOCIDAS</div>'}`;m.querySelector('#reviewPurchase').disabled=!parsed.lines.length;};
  m.querySelector('#previewPurchase').onclick=preview;m.querySelector('#pastePurchase').onclick=async()=>{try{m.querySelector('#purchaseImportText').value=await navigator.clipboard.readText();preview()}catch{toast('NO SE PUDO LEER EL PORTAPAPELES','bad')}};m.querySelector('#reviewPurchase').onclick=()=>{if(!parsed?.lines.length)return;closeModal();purchaseModal(parsed)};
}
export async function copyPurchasePrompt(){try{await navigator.clipboard.writeText(chatGptPurchaseInstruction());toast('INSTRUCCIÓN PARA CHATGPT COPIADA','good')}catch{const m=modal('INSTRUCCIÓN PARA CHATGPT',`<textarea class="import-text">${esc(chatGptPurchaseInstruction())}</textarea>`,true);m.querySelector('textarea').select()}}

export function exportProducts(){exportXlsx(products().map(p=>({CODIGO:p.code,PRODUCTO:p.name,ALIAS:p.aliases,MODO:p.mode,'KG_CAJA':p.kgPerBox,COMPRA:p.buyPrice,VENTA:p.sellPrice,RECOMENDADO:p.recommended,IVA:p.vat,PROVEEDOR:p.supplier})),'ARW2026_PRODUCTOS.xlsx')}
export function exportClients(){exportXlsx(clients().map(c=>({CLIENTE:c.name,NIF:c.nif,DIRECCION:c.address,RECARGO_EQUIVALENCIA:c.equivalenceSurcharge?'SI':'NO',TRANSPORTE:c.transportPercent,COMISION:c.commissionPercent,PAGO:c.paymentMethod,TELEFONO:c.phone,EMAIL:c.email})),'ARW2026_CLIENTES.xlsx')}
export function exportStock(){exportXlsx(products().map(p=>({CODIGO:p.code,PRODUCTO:p.name,STOCK:stockQuantity(st().stockMoves,p.id),MODO:p.mode,KG_CAJA:p.kgPerBox,VALOR:round2(stockQuantity(st().stockMoves,p.id)*Number(p.buyPrice||0))})),'ARW2026_STOCK.xlsx')}
