import {Runtime} from './runtime.js';
import {section,table,kpi,badge,modal,closeModal,toast,optionList,money,esc} from './ui.js';
import {newLine,calcInvoice,stockQuantity,stockText,round2,today,now,uid,upper} from './domain.js';
import {saveEntity,saveStockOperation,reopenMonthClosure} from './firebase.js';
import {invoiceModal} from './views-sales.js';
import {costAtDate} from './finance.js';
import {can} from './permissions.js';
const st=()=>Runtime.state,product=id=>Runtime.product(id),client=id=>Runtime.client(id);
const products=()=>st().products.filter(p=>p.active!==false&&!p.archived).sort((a,b)=>String(a.name).localeCompare(String(b.name)));
const clients=()=>st().clients.filter(c=>c.active!==false&&!c.archived).sort((a,b)=>String(a.name).localeCompare(String(b.name)));
const productOpts=(sel='')=>`<option value="">SELECCIONAR</option>${optionList(products(),sel,p=>`${p.code} · ${p.name}`)}`;
const clientOpts=(sel='')=>`<option value="">SELECCIONAR</option>${optionList(clients(),sel)}`;
const LOCATIONS=['ALMACEN','FURGONETA','SAN PABLO','SAN LESMES','SANTIAGO'];
function qtyToStock(p,qty){return p?.mode==='caja_kg'?round2(Number(qty||0)*Number(p.kgPerBox||0)):Number(qty||0)}
function requireStockOps(){if(can(Runtime.role,'stockOps'))return true;toast('SIN PERMISO PARA OPERACIONES DE STOCK','bad');return false}

export function warehouseOpsView(){const actions=can(Runtime.role,'stockOps')?`<button class="btn" data-action="transfer-new">TRASPASO</button><button class="btn bad" data-action="waste-new">MERMA</button><button class="btn" data-action="return-new">DEVOLUCIÓN</button><button class="btn primary" data-action="inventory-new">INVENTARIO</button>`:'';return `${section('OPERACIONES DE STOCK','TRASPASOS · MERMAS · DEVOLUCIONES · INVENTARIO FÍSICO',actions)}<div class="grid2"><div><h3>ÚLTIMOS TRASPASOS</h3>${table(['FECHA','PRODUCTO','ORIGEN','DESTINO','CANTIDAD'],st().transfers.slice(0,50).map(t=>`<tr><td>${t.date}</td><td>${esc(product(t.productId)?.name||'')}</td><td>${esc(t.from)}</td><td>${esc(t.to)}</td><td>${t.qty}</td></tr>`))}</div><div><h3>MERMAS / DEVOLUCIONES</h3>${table(['FECHA','TIPO','PRODUCTO','CANTIDAD','MOTIVO'],[...st().wastes.map(x=>({...x,kind:'MERMA'})),...st().returns.map(x=>({...x,kind:'DEVOLUCIÓN'}))].sort((a,b)=>String(b.date).localeCompare(String(a.date))).slice(0,50).map(x=>`<tr><td>${x.date}</td><td>${badge(x.kind,x.kind==='MERMA'?'bad':'good')}</td><td>${esc(product(x.productId)?.name||'')}</td><td>${x.qty}</td><td>${esc(x.reason||'')}</td></tr>`))}</div></div>`}

export function transferModal(){if(!requireStockOps())return;const m=modal('TRASPASO DE STOCK',`<form id="tf"><div class="form-grid"><label>PRODUCTO<select name="pid">${productOpts()}</select></label><label>CANTIDAD<input name="qty" type="number" step=".01"></label><label>ORIGEN<select name="from">${LOCATIONS.map(x=>`<option>${x}</option>`).join('')}</select></label><label>DESTINO<select name="to">${LOCATIONS.map(x=>`<option>${x}</option>`).join('')}</select></label></div><div class="muted">EN CAJA × KG, CANTIDAD SIGNIFICA CAJAS Y ARW2026 CONVIERTE A KG.</div><button class="btn primary">REGISTRAR</button></form>`,true);m.querySelector('[name=pid]').onchange=e=>m.querySelector('[name=qty]').step=product(e.target.value)?.mode?.startsWith('caja')?'1':'.01';m.querySelector('#tf').onsubmit=async e=>{e.preventDefault();try{const f=new FormData(e.currentTarget),p=product(f.get('pid')),input=Number(f.get('qty')||0),q=qtyToStock(p,input);if(!p||q<=0)throw new Error('REVISA PRODUCTO Y CANTIDAD');if(p.mode?.startsWith('caja')&&!Number.isInteger(input))throw new Error('LAS CAJAS DEBEN SER ENTERAS');if(f.get('from')===f.get('to'))throw new Error('ORIGEN Y DESTINO NO PUEDEN SER IGUALES');if(q>stockQuantity(st().stockMoves,p.id,f.get('from'))+.0001)throw new Error(`STOCK INSUFICIENTE EN ${f.get('from')}`);const id=uid('tr'),date=today();await saveStockOperation('transfers',{id,date,productId:p.id,qty:input,stockQty:q,from:f.get('from'),to:f.get('to')},[{productId:p.id,qty:-q,type:'transfer_out',location:f.get('from'),sourceId:id,date},{productId:p.id,qty:q,type:'transfer_in',location:f.get('to'),sourceId:id,date}],'TRANSFER',Runtime.user);toast('TRASPASO REGISTRADO ATÓMICAMENTE','good');closeModal()}catch(err){toast(err.message,'bad')}}}
export function wasteModal(){if(!requireStockOps())return;const m=modal('REGISTRAR MERMA',`<form id="wf"><div class="form-grid three"><label>PRODUCTO<select name="pid">${productOpts()}</select></label><label>CANTIDAD<input name="qty" type="number" step=".01"></label><label>UBICACIÓN<select name="location">${LOCATIONS.map(x=>`<option>${x}</option>`).join('')}</select></label></div><div class="muted">EN CAJA × KG, CANTIDAD SIGNIFICA CAJAS.</div><label class="field">MOTIVO<input name="reason" required></label><button class="btn bad">REGISTRAR MERMA</button></form>`,true);m.querySelector('[name=pid]').onchange=e=>m.querySelector('[name=qty]').step=product(e.target.value)?.mode?.startsWith('caja')?'1':'.01';m.querySelector('#wf').onsubmit=async e=>{e.preventDefault();try{const f=new FormData(e.currentTarget),p=product(f.get('pid')),input=Number(f.get('qty')||0),q=qtyToStock(p,input),id=uid('w');if(!p||q<=0)throw new Error('REVISA PRODUCTO Y CANTIDAD');if(p.mode?.startsWith('caja')&&!Number.isInteger(input))throw new Error('LAS CAJAS DEBEN SER ENTERAS');if(q>stockQuantity(st().stockMoves,p.id,f.get('location'))+.0001)throw new Error('LA MERMA SUPERA EL STOCK DE ESA UBICACIÓN');const date=today(),reason=upper(f.get('reason'));await saveStockOperation('wastes',{id,date,productId:p.id,qty:input,stockQty:q,location:f.get('location'),reason},[{productId:p.id,qty:-q,type:'waste',location:f.get('location'),sourceId:id,note:reason,date}],'WASTE',Runtime.user);toast('MERMA REGISTRADA ATÓMICAMENTE','good');closeModal()}catch(err){toast(err.message,'bad')}}}
export function returnModal(){if(!requireStockOps())return;const m=modal('DEVOLUCIÓN A STOCK',`<form id="retf"><div class="form-grid three"><label>PRODUCTO<select name="pid">${productOpts()}</select></label><label>CANTIDAD<input name="qty" type="number" step=".01"></label><label>UBICACIÓN<select name="location">${LOCATIONS.map(x=>`<option>${x}</option>`).join('')}</select></label></div><label class="field">MOTIVO<input name="reason" required></label><button class="btn primary">REGISTRAR DEVOLUCIÓN</button></form>`,true);m.querySelector('[name=pid]').onchange=e=>m.querySelector('[name=qty]').step=product(e.target.value)?.mode?.startsWith('caja')?'1':'.01';m.querySelector('#retf').onsubmit=async e=>{e.preventDefault();try{const f=new FormData(e.currentTarget),p=product(f.get('pid')),input=Number(f.get('qty')||0),q=qtyToStock(p,input),id=uid('ret');if(!p||q<=0)throw new Error('REVISA PRODUCTO Y CANTIDAD');if(p.mode?.startsWith('caja')&&!Number.isInteger(input))throw new Error('LAS CAJAS DEBEN SER ENTERAS');const date=today(),reason=upper(f.get('reason'));await saveStockOperation('returns',{id,date,productId:p.id,qty:input,stockQty:q,location:f.get('location'),reason},[{productId:p.id,qty:q,type:'return',location:f.get('location'),sourceId:id,note:reason,date}],'RETURN',Runtime.user);toast('DEVOLUCIÓN REGISTRADA ATÓMICAMENTE','good');closeModal()}catch(err){toast(err.message,'bad')}}}
export function inventoryModal(){if(!requireStockOps())return;const m=modal('INVENTARIO FÍSICO',`<div class="warning">INVENTARIO DE ALMACÉN. EN CAJA × KG INTRODUCE CAJAS.</div><div class="table-wrap"><table><thead><tr><th>PRODUCTO</th><th>SISTEMA</th><th>CONTADO</th><th>DIFERENCIA</th></tr></thead><tbody id="invCountRows">${products().map(p=>{const q=stockQuantity(st().stockMoves,p.id,'ALMACEN'),display=p.mode==='caja_kg'&&p.kgPerBox?round2(q/p.kgPerBox):q;return `<tr data-pid="${p.id}"><td>${esc(p.code)} · ${esc(p.name)}</td><td>${esc(stockText(p,q))}</td><td><input class="count" type="number" step="${p.mode?.startsWith('caja')?'1':'.01'}" value="${display}"></td><td class="diff">0</td></tr>`}).join('')}</tbody></table></div><button class="btn primary" id="saveInventory">AJUSTAR INVENTARIO</button>`);const refresh=()=>m.querySelectorAll('#invCountRows tr').forEach(tr=>{const p=product(tr.dataset.pid),sys=stockQuantity(st().stockMoves,p.id,'ALMACEN'),input=Number(tr.querySelector('.count').value||0),count=qtyToStock(p,input);tr.querySelector('.diff').textContent=round2(count-sys)});m.addEventListener('input',refresh);m.querySelector('#saveInventory').onclick=async()=>{try{if(!confirm('¿APLICAR LAS DIFERENCIAS DEL INVENTARIO AL STOCK?'))return;const id=uid('ic'),rows=[],moves=[],date=today();for(const tr of m.querySelectorAll('#invCountRows tr')){const p=product(tr.dataset.pid),input=Number(tr.querySelector('.count').value||0);if(p.mode?.startsWith('caja')&&!Number.isInteger(input))throw new Error(`${p.name}: LAS CAJAS DEBEN SER ENTERAS`);const sys=stockQuantity(st().stockMoves,p.id,'ALMACEN'),count=qtyToStock(p,input),diff=round2(count-sys);rows.push({productId:p.id,system:sys,count,diff});if(Math.abs(diff)>.0001)moves.push({productId:p.id,qty:diff,type:'inventory_adjust',location:'ALMACEN',sourceId:id,date})}await saveStockOperation('inventoryCounts',{id,date,location:'ALMACEN',rows},moves,'INVENTORY_COUNT',Runtime.user);toast('INVENTARIO AJUSTADO ATÓMICAMENTE','good');closeModal()}catch(err){toast(err.message,'bad')}};refresh()}

const docCollections={quote:'quotes',proforma:'proformas',delivery:'deliveryNotes'},docLabels={quote:'PRESUPUESTO',proforma:'PROFORMA',delivery:'ALBARÁN'};
function canDoc(kind){return kind==='delivery'?can(Runtime.role,'deliveryNoteWrite'):can(Runtime.role,'quoteWrite')}
export function documentsView(){const all=[...st().quotes.map(x=>({...x,kind:'quote'})),...st().proformas.map(x=>({...x,kind:'proforma'})),...st().deliveryNotes.map(x=>({...x,kind:'delivery'}))].sort((a,b)=>String(b.date).localeCompare(String(a.date))),actions=[can(Runtime.role,'quoteWrite')?'<button class="btn" data-action="doc-quote">＋ PRESUPUESTO</button><button class="btn" data-action="doc-proforma">＋ PROFORMA</button>':'',can(Runtime.role,'deliveryNoteWrite')?'<button class="btn primary" data-action="doc-delivery">＋ ALBARÁN</button>':''].join('');return `${section('DOCUMENTOS COMERCIALES','PRESUPUESTOS · PROFORMAS · ALBARANES → FACTURA',actions)}${table(['TIPO','FECHA','CLIENTE','LÍNEAS','TOTAL','ESTADO','ACCIONES'],all.map(d=>`<tr><td>${badge(docLabels[d.kind])}</td><td>${d.date}</td><td>${esc((client(d.clientId)||d.clientSnapshot||{}).name||'')}</td><td>${d.lines?.length||0}</td><td>${money(calcInvoice(d).total)}</td><td>${d.invoiceId?badge('FACTURADO','good'):badge('ABIERTO','warn')}</td><td>${d.invoiceId?'—':can(Runtime.role,'invoiceWrite')?`<button class="btn mini primary" data-doc-invoice="${d.kind}:${d.id}">CONVERTIR A FACTURA</button>`:'—'}</td></tr>`))}`}
function docLineRow(l={}){const p=product(l.productId),step=p?.mode?.startsWith('caja')?'1':'.01';return `<tr><td><select class="dProd">${productOpts(l.productId)}</select></td><td><input class="dQty" type="number" step="${step}" value="${Number(l.qty||0)}"></td><td><input class="dPrice" type="number" step=".01" value="${Number(l.price||0)}"></td><td><select class="dVat">${[0,4,10,21].map(v=>`<option value="${v}" ${Number(l.vat||4)===v?'selected':''}>${v}%</option>`).join('')}</select></td></tr>`}
export function documentModal(kind){if(!canDoc(kind))return toast('TU ROL NO PUEDE CREAR ESTE DOCUMENTO','bad');const label=docLabels[kind],m=modal(`NUEVO ${label}`,`<form id="df"><div class="form-grid three"><label>CLIENTE<select name="clientId">${clientOpts()}</select></label><label>FECHA<input name="date" type="date" value="${today()}"></label><label class="check"><input name="hidePrices" type="checkbox" ${kind==='delivery'?'checked':''}> SIN PRECIOS</label></div><div class="table-wrap"><table><thead><tr><th>PRODUCTO</th><th>CANTIDAD</th><th>PRECIO</th><th>IVA</th></tr></thead><tbody id="dRows">${Array.from({length:6},()=>docLineRow()).join('')}</tbody></table></div><button class="btn primary">GUARDAR ${label}</button></form>`);m.addEventListener('change',e=>{if(e.target.matches('.dProd')){const p=product(e.target.value),tr=e.target.closest('tr'),c=client(m.querySelector('[name=clientId]').value),l=newLine(p,c);tr.querySelector('.dPrice').value=l.price;tr.querySelector('.dVat').value=l.vat;tr.querySelector('.dQty').step=p?.mode?.startsWith('caja')?'1':'.01'}});m.querySelector('#df').onsubmit=async e=>{e.preventDefault();try{const f=new FormData(e.currentTarget),cid=f.get('clientId'),c=client(cid),lines=[...m.querySelectorAll('#dRows tr')].map(tr=>{const pid=tr.querySelector('.dProd').value;if(!pid)return null;const p=product(pid),qty=Number(tr.querySelector('.dQty').value||0);if(p?.mode?.startsWith('caja')&&!Number.isInteger(qty))throw new Error(`${p.name}: LAS CAJAS DEBEN SER ENTERAS`);return newLine(p,c,{qty,price:Number(tr.querySelector('.dPrice').value||0),vat:Number(tr.querySelector('.dVat').value||0)})}).filter(l=>l&&l.qty>0);if(!cid||!lines.length)throw new Error('CLIENTE Y PRODUCTOS OBLIGATORIOS');const id=uid('doc');await saveEntity(docCollections[kind],{id,clientId:cid,clientSnapshot:c?{name:c.name,nif:c.nif,address:c.address}:null,date:f.get('date'),hidePrices:!!f.get('hidePrices'),transportType:'fixed',transportValue:0,discount:0,lines},`DOC_${kind}`,Runtime.user);toast(`${label} GUARDADO`,'good');closeModal()}catch(err){toast(err.message,'bad')}}}
export function convertDocument(kind,id){if(!can(Runtime.role,'invoiceWrite'))return toast('SIN PERMISO PARA FACTURAR','bad');const d=st()[docCollections[kind]].find(x=>x.id===id);if(!d||d.invoiceId)return toast('DOCUMENTO YA FACTURADO O NO ENCONTRADO','bad');invoiceModal(null,{clientId:d.clientId,clientSnapshot:d.clientSnapshot,sourceDocument:{kind,id},lines:d.lines})}

function monthEnd(month){const [y,m]=month.split('-').map(Number),d=new Date(y,m,0);return `${y}-${String(m).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`}
function moveDate(m){return String(m.date||m.createdAt||'').slice(0,10)}
function stockAt(productId,end,location=null){return round2(st().stockMoves.filter(m=>m.productId===productId&&moveDate(m)<=end&&(!location||(m.location||'ALMACEN')===location)).reduce((s,m)=>s+Number(m.qty||0),0))}
function negativeAt(end){const locs=[...new Set([...LOCATIONS,...st().stockMoves.map(m=>m.location||'ALMACEN')])],out=[];for(const p of products())for(const location of locs){const q=stockAt(p.id,end,location);if(q<-.0001)out.push({p,location,q})}return out}
function closeNumbers(invs){const nums=invs.filter(i=>i.number).map(i=>i.number);return[...new Set(nums.filter((n,i)=>nums.indexOf(n)!==i))]}
export function closuresView(){const month=window.ARW_CLOSE_MONTH||today().slice(0,7),end=monthEnd(month),invs=st().invoices.filter(i=>i.date?.startsWith(month)),delivered=st().orders.filter(o=>o.date?.startsWith(month)&&o.status==='delivered'&&!o.invoiceId),neg=negativeAt(end),badBox=products().filter(p=>p.mode==='caja_kg'&&!Number(p.kgPerBox)),dups=closeNumbers(invs),drafts=invs.filter(i=>i.status==='draft'),closed=st().closures.find(c=>c.id===`close_${month}`),actions=closed?(Runtime.role==='owner'?'<button class="btn bad" id="reopenMonth">REABRIR MES</button>':''):'<button class="btn primary" data-action="close-month">CERRAR MES</button>';const html=`${section('CIERRE MENSUAL','CONTROL A FECHA DE FIN DE MES · AL CERRAR SE BLOQUEAN NUEVAS EMISIONES/COMPRAS',actions)}<div class="panel"><label class="field">MES<input id="closeMonth" type="month" value="${month}"></label></div><br><div class="kpis">${kpi('FACTURAS',String(invs.length))}${kpi('BORRADORES',String(drafts.length))}${kpi('ENTREGAS SIN FACTURA',String(delivered.length))}${kpi('STOCK NEGATIVO FIN MES',String(neg.length))}</div>${badBox.length?`<div class="danger">CAJA × KG SIN PESO: ${badBox.map(p=>esc(p.code)).join(', ')}</div>`:''}${dups.length?`<div class="danger">NÚMEROS DUPLICADOS: ${esc(dups.join(', '))}</div>`:''}${neg.length?`<div class="danger">NEGATIVOS A ${end}: ${neg.slice(0,12).map(x=>`${esc(x.p.code)} ${esc(x.location)} ${x.q}`).join(' · ')}</div>`:''}${closed?`<div class="success">CIERRE GUARDADO ${esc(closed.closedAt||'')} · STOCK VALORADO A FECHA ${end}</div>`:''}`;setTimeout(()=>{const b=document.querySelector('#reopenMonth');if(b)b.onclick=async()=>{if(!confirm(`¿REABRIR ${month}?`))return;try{await reopenMonthClosure(month,Runtime.user);toast('MES REABIERTO','good')}catch(e){toast(e.message,'bad')}}},0);return html}
export async function closeMonth(){if(!can(Runtime.role,'closeMonth'))return toast('SIN PERMISO PARA CERRAR','bad');const month=window.ARW_CLOSE_MONTH||today().slice(0,7),end=monthEnd(month),invs=st().invoices.filter(i=>i.date?.startsWith(month)),delivered=st().orders.filter(o=>o.date?.startsWith(month)&&o.status==='delivered'&&!o.invoiceId),neg=negativeAt(end),badBox=products().filter(p=>p.mode==='caja_kg'&&!Number(p.kgPerBox)),drafts=invs.filter(i=>i.status==='draft'),dups=closeNumbers(invs);if(delivered.length||neg.length||badBox.length||drafts.length||dups.length)return toast('RESUELVE TODAS LAS ALERTAS ANTES DE CERRAR','bad');if(!confirm(`¿CERRAR ${month}? EL STOCK SE CONGELARÁ A ${end}.`))return;const stockSnapshot=products().map(p=>{const qty=stockAt(p.id,end),cost=costAtDate(p.id,{date:end},{},products(),st().priceHistory).unitCost||Number(p.buyPrice||0);return{productId:p.id,qty,cost,value:round2(Math.max(0,qty)*cost)}});await saveEntity('closures',{id:`close_${month}`,month,endDate:end,closedAt:now(),stockSnapshot,invoiceCount:invs.filter(i=>i.status!=='draft').length},'MONTH_CLOSE',Runtime.user);toast('MES CERRADO CON STOCK A FECHA','good')}
