import {Runtime} from './runtime.js';
import {section,table,kpi,badge,modal,closeModal,toast,money,esc,optionList} from './ui.js';
import {today,now,uid,upper,round2} from './domain.js';
import {saveEntity} from './firebase.js';
const st=()=>Runtime.state,clients=()=>st().clients.filter(c=>c.active!==false&&!c.archived).sort((a,b)=>String(a.name).localeCompare(String(b.name)));
const clientOpts=(sel='')=>`<option value="">SELECCIONAR</option>${optionList(clients(),sel)}`;

function downloadText(text,name,type='application/json'){const blob=new Blob([text],{type}),a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),2000)}
export function backupView(){const keys=Object.keys(Runtime.state),counts=keys.map(k=>[k,Array.isArray(Runtime.state[k])?Runtime.state[k].length:0]);return `${section('BACKUP Y RECUPERACIÓN','COPIA LOCAL COMPLETA DEL ESTADO FIRESTORE VISIBLE PARA TU USUARIO',`<button class="btn primary" data-action="backup-download">DESCARGAR BACKUP JSON</button>${Runtime.role==='owner'?'<button class="btn bad" data-action="backup-restore">RESTAURAR / FUSIONAR BACKUP</button>':''}`)}<div class="warning">EL BACKUP NO SUSTITUYE LAS COPIAS NATIVAS DE FIREBASE. RESTAURAR ES UNA OPERACIÓN DE ADMINISTRACIÓN Y NO BORRA AUTOMÁTICAMENTE DOCUMENTOS QUE NO ESTÉN EN EL ARCHIVO.</div>${table(['COLECCIÓN','REGISTROS'],counts.map(([k,n])=>`<tr><td>${esc(k)}</td><td>${n}</td></tr>`))}`}
export function downloadBackup(){const payload={format:'ARW2026_BACKUP_V4',createdAt:now(),user:Runtime.user?.email||'',role:Runtime.role,settings:Runtime.settings(),state:Runtime.state};downloadText(JSON.stringify(payload,null,2),`ARW2026_BACKUP_${today()}_${Date.now()}.json`);toast('BACKUP DESCARGADO','good')}
export function restoreBackupModal(){if(Runtime.role!=='owner')return toast('SOLO PROPIETARIO','bad');const m=modal('RESTAURAR / FUSIONAR BACKUP',`<div class="danger"><b>OPERACIÓN SENSIBLE.</b> SE FUSIONARÁN LOS DOCUMENTOS DEL BACKUP CON FIRESTORE. NO SE RESTAURA AUDITORÍA NI USUARIOS.</div><input id="backupFile" type="file" accept="application/json,.json"><div id="backupPreview" class="panel" style="margin-top:12px">SELECCIONA UN ARCHIVO.</div><div class="modal-actions"><button class="btn bad" id="backupApply" disabled>RESTAURAR</button></div>`);let parsed=null;m.querySelector('#backupFile').onchange=async e=>{try{parsed=JSON.parse(await e.target.files?.[0]?.text());if(parsed?.format!=='ARW2026_BACKUP_V4')throw new Error('FORMATO DE BACKUP NO VÁLIDO');const counts=Object.entries(parsed.state||{}).filter(([,v])=>Array.isArray(v)).map(([k,v])=>`${k}: ${v.length}`).join('<br>');m.querySelector('#backupPreview').innerHTML=`<b>${esc(parsed.createdAt||'')}</b><br>${counts}`;m.querySelector('#backupApply').disabled=false}catch(err){parsed=null;m.querySelector('#backupPreview').innerHTML=`<div class="danger">${esc(err.message)}</div>`}};m.querySelector('#backupApply').onclick=async()=>{if(!parsed)return;const typed=prompt('ESCRIBE RESTAURAR ARW2026 PARA CONFIRMAR');if(upper(typed)!=='RESTAURAR ARW2026')return;try{const skip=new Set(['audit','members']);let n=0;for(const [name,items] of Object.entries(parsed.state||{})){if(skip.has(name)||!Array.isArray(items))continue;for(const obj of items){if(!obj?.id)continue;await saveEntity(name,obj,'RESTORE',null);n++}}await saveEntity('audit',{id:uid('a'),action:'BACKUP_RESTORE',entity:'system',entityId:'backup',count:n,userEmail:Runtime.user?.email||'',userUid:Runtime.user?.uid||'',at:now()},'BACKUP_RESTORE',null);toast(`${n} DOCUMENTOS FUSIONADOS`,'good');closeModal()}catch(err){toast(err.message,'bad')}}}

export function membersView(){const list=[...st().members].sort((a,b)=>String(a.email||a.id).localeCompare(String(b.email||b.id)));return `${section('USUARIOS Y ROLES','EL USUARIO DEBE EXISTIR PRIMERO EN FIREBASE AUTHENTICATION',Runtime.role==='owner'?'<button class="btn primary" data-action="member-new">＋ USUARIO / ROL</button>':'')}<div class="panel"><p>ROLES: OWNER · ADMIN · MANAGER · BILLING · WAREHOUSE · DELIVERY.</p><p class="muted">AQUÍ SE ASIGNA EL UID DE FIREBASE AUTHENTICATION. ARW2026 NO CREA CONTRASEÑAS NI CUENTAS AUTH DESDE EL NAVEGADOR.</p></div><br>${table(['EMAIL','UID','ROL','ACTIVO','ACCIONES'],list.map(x=>`<tr><td>${esc(x.email||'')}</td><td><small>${esc(x.id)}</small></td><td>${badge(x.role||'')}</td><td>${x.active!==false?badge('SÍ','good'):badge('NO','bad')}</td><td>${Runtime.role==='owner'?`<button class="btn mini" data-member-edit="${x.id}">EDITAR</button>`:'—'}</td></tr>`))}`}
export function memberModal(existing=null){if(Runtime.role!=='owner')return toast('SOLO PROPIETARIO','bad');const x=existing||{id:'',email:'',role:'billing',active:true};const m=modal(existing?'EDITAR USUARIO':'ASIGNAR USUARIO / ROL',`<form id="mf"><label class="field">UID FIREBASE<input name="uid" value="${esc(x.id||'')}" ${existing?'readonly':''} required></label><label class="field">EMAIL<input name="email" type="email" value="${esc(x.email||'')}"></label><label class="field">ROL<select name="role"><option value="admin">ADMIN</option><option value="manager">MANAGER</option><option value="billing">FACTURACIÓN</option><option value="warehouse">ALMACÉN</option><option value="delivery">REPARTO</option></select></label><label class="check"><input name="active" type="checkbox" ${x.active!==false?'checked':''}> ACTIVO</label><button class="btn primary">GUARDAR</button></form>`,true);m.querySelector('[name=role]').value=x.role||'billing';m.querySelector('#mf').onsubmit=async e=>{e.preventDefault();try{const f=new FormData(e.currentTarget),id=String(f.get('uid')||'').trim();if(!id)throw new Error('UID OBLIGATORIO');await saveEntity('members',{id,email:String(f.get('email')||'').trim().toLowerCase(),role:f.get('role'),active:f.get('active')==='on'},'MEMBER_SAVE',Runtime.user);toast('ROL GUARDADO','good');closeModal()}catch(err){toast(err.message,'bad')}}}

function movementBalance(list){return round2(list.reduce((s,x)=>s+(x.direction==='out'?-1:1)*Number(x.amount||0),0))}
export function cashBankView(){const cash=[...st().cashMovements].sort((a,b)=>String(b.createdAt||b.date).localeCompare(String(a.createdAt||a.date))),bank=[...st().bankMovements].sort((a,b)=>String(b.createdAt||b.date).localeCompare(String(a.createdAt||a.date))),cashBal=movementBalance(cash),bankBal=movementBalance(bank);return `${section('CAJA Y BANCOS','MOVIMIENTOS MANUALES · ENTRADAS · SALIDAS · SALDO',`<button class="btn primary" data-action="cash-new">＋ MOVIMIENTO CAJA</button><button class="btn" data-action="bank-new">＋ MOVIMIENTO BANCO</button>`)}<div class="kpis">${kpi('SALDO CAJA',money(cashBal))}${kpi('SALDO BANCO',money(bankBal))}${kpi('MOV. CAJA',String(cash.length))}${kpi('MOV. BANCO',String(bank.length))}</div><div class="grid2"><div><h3>CAJA</h3>${table(['FECHA','TIPO','CONCEPTO','IMPORTE'],cash.slice(0,100).map(x=>`<tr><td>${x.date}</td><td>${badge(x.direction==='out'?'SALIDA':'ENTRADA',x.direction==='out'?'bad':'good')}</td><td>${esc(x.concept||'')}</td><td>${money(x.amount)}</td></tr>`))}</div><div><h3>BANCO</h3>${table(['FECHA','TIPO','CONCEPTO','IMPORTE'],bank.slice(0,100).map(x=>`<tr><td>${x.date}</td><td>${badge(x.direction==='out'?'SALIDA':'ENTRADA',x.direction==='out'?'bad':'good')}</td><td>${esc(x.concept||'')}</td><td>${money(x.amount)}</td></tr>`))}</div></div>`}
export function moneyMovementModal(kind='cash'){const collection=kind==='bank'?'bankMovements':'cashMovements',m=modal(kind==='bank'?'MOVIMIENTO BANCO':'MOVIMIENTO CAJA',`<form id="mmf"><div class="form-grid three"><label>FECHA<input name="date" type="date" value="${today()}"></label><label>TIPO<select name="direction"><option value="in">ENTRADA</option><option value="out">SALIDA</option></select></label><label>IMPORTE<input name="amount" type="number" min="0" step=".01"></label></div><label class="field">CONCEPTO<input name="concept" required></label><button class="btn primary">GUARDAR</button></form>`,true);m.querySelector('#mmf').onsubmit=async e=>{e.preventDefault();try{const f=new FormData(e.currentTarget),amount=Number(f.get('amount')||0);if(amount<=0)throw new Error('IMPORTE INVÁLIDO');await saveEntity(collection,{id:uid(kind==='bank'?'bm':'cm'),date:f.get('date'),direction:f.get('direction'),amount,concept:upper(f.get('concept')),createdAt:now()},'MONEY_MOVE',Runtime.user);toast('MOVIMIENTO GUARDADO','good');closeModal()}catch(err){toast(err.message,'bad')}}}

export function containersView(){const list=[...st().containers].sort((a,b)=>String(b.createdAt||b.date).localeCompare(String(a.createdAt||a.date))),balances=new Map();for(const x of list){const key=`${x.clientId}:${upper(x.containerType||'CAJA')}`,old=balances.get(key)||{clientId:x.clientId,type:upper(x.containerType||'CAJA'),qty:0};old.qty=round2(old.qty+Number(x.qty||0));balances.set(key,old)}return `${section('ENVASES / CAJAS RETORNABLES','SALDO POR CLIENTE Y TIPO',`<button class="btn primary" data-action="container-new">＋ MOVIMIENTO ENVASE</button>`)}${table(['CLIENTE','TIPO','SALDO'],[...balances.values()].sort((a,b)=>String(clients().find(c=>c.id===a.clientId)?.name).localeCompare(String(clients().find(c=>c.id===b.clientId)?.name))).map(x=>`<tr><td>${esc(clients().find(c=>c.id===x.clientId)?.name||x.clientId)}</td><td>${esc(x.type)}</td><td class="${x.qty<0?'neg':'pos'}"><b>${x.qty}</b></td></tr>`))}<br><h3>ÚLTIMOS MOVIMIENTOS</h3>${table(['FECHA','CLIENTE','TIPO','CANTIDAD','NOTA'],list.slice(0,100).map(x=>`<tr><td>${x.date}</td><td>${esc(clients().find(c=>c.id===x.clientId)?.name||'')}</td><td>${esc(x.containerType||'CAJA')}</td><td>${x.qty>0?'+':''}${x.qty}</td><td>${esc(x.note||'')}</td></tr>`))}`}
export function containerModal(){const m=modal('MOVIMIENTO DE ENVASE',`<form id="ctf"><div class="form-grid three"><label>CLIENTE<select name="clientId">${clientOpts()}</select></label><label>TIPO<input name="type" value="CAJA"></label><label>CANTIDAD (+ENTREGA / -DEVOLUCIÓN)<input name="qty" type="number" step="1"></label></div><label class="field">NOTA<input name="note"></label><button class="btn primary">GUARDAR</button></form>`,true);m.querySelector('#ctf').onsubmit=async e=>{e.preventDefault();try{const f=new FormData(e.currentTarget),qty=Number(f.get('qty')||0);if(!f.get('clientId')||!qty)throw new Error('CLIENTE Y CANTIDAD OBLIGATORIOS');await saveEntity('containers',{id:uid('ct'),clientId:f.get('clientId'),containerType:upper(f.get('type')||'CAJA'),qty,date:today(),note:upper(f.get('note')),createdAt:now()},'CONTAINER_MOVE',Runtime.user);toast('ENVASE ACTUALIZADO','good');closeModal()}catch(err){toast(err.message,'bad')}}}
