import {n,round2,uid,nowISO,daysBetween,ageBucket} from './utils.js';
export const MODES={caja_kg:'CAJA × KG',caja_fija:'CAJA FIJA',kg:'KG',ud:'UD',manojo:'MANOJO'};
export function lineFromProduct(p,c=null){const cp=c?.prices?.[p.id];return {id:uid('line'),productId:p.id,code:p.code||'',product:p.name||'',mode:p.mode||'kg',qty:0,kgPerBox:n(p.kgPerBox),gross:0,tare:0,net:0,unit:p.unit||'kg',price:n(cp?.price??p.sellPrice),vat:n(p.vat??4),discount:0,buyPriceSnapshot:n(p.buyPrice),priceSource:cp?'CLIENTE':'GENERAL',base:0,vatAmount:0,total:0}}
export function calcLine(x){const l={...x};const q=n(l.qty),kg=n(l.kgPerBox),gross=n(l.gross),tare=n(l.tare);let bill=0;if(l.mode==='caja_kg'){l.net=gross>0?round2(Math.max(0,gross-tare)):round2(q*kg);bill=l.net;l.unit='kg'}else if(l.mode==='caja_fija'){l.net=q;bill=q;l.unit='caja'}else{l.net=q;bill=q;l.unit=l.mode==='ud'?'ud':l.mode==='manojo'?'manojo':'kg'}const before=round2(bill*n(l.price));const discount=round2(before*n(l.discount)/100);l.base=round2(before-discount);l.vatAmount=round2(l.base*n(l.vat)/100);l.total=round2(l.base+l.vatAmount);return l}
export function calcInvoice(x){const inv={...x};let lines=(inv.lines||[]).map(calcLine).filter(l=>l.productId&&n(l.qty)>0);const sign=inv.type==='credit'?-1:1;const raw=round2(lines.reduce((s,l)=>s+n(l.base),0));const transport=inv.transportType==='percent'?round2(raw*n(inv.transportValue)/100):round2(n(inv.transportValue));const discount=round2(raw*n(inv.discount)/100);const factor=raw?(raw-discount+transport)/raw:1;const vats={};for(const l of lines){const r=n(l.vat);vats[r]??={rate:r,base:0,vat:0};vats[r].base=round2(vats[r].base+l.base*factor);vats[r].vat=round2(vats[r].vat+l.base*factor*r/100)}let vatBreakdown=Object.values(vats).sort((a,b)=>a.rate-b.rate).map(v=>({rate:v.rate,base:round2(v.base*sign),vat:round2(v.vat*sign)}));if(sign<0)lines=lines.map(l=>({...l,base:-Math.abs(l.base),vatAmount:-Math.abs(l.vatAmount),total:-Math.abs(l.total)}));const base=round2(vatBreakdown.reduce((s,v)=>s+v.base,0)),vatTotal=round2(vatBreakdown.reduce((s,v)=>s+v.vat,0)),total=round2(base+vatTotal),paid=sign<0?0:round2(n(inv.paid)),pending=sign<0?total:round2(Math.max(0,total-paid));return {...inv,lines,productBase:round2(raw*sign),transportBase:round2(transport*sign),globalDiscount:round2(discount*sign),vatBreakdown,base,vatTotal,total,paid,pending,paymentStatus:sign<0?'credited':paid<=0?'pending':paid+0.009>=total?'paid':'partial'}}
export function invoiceStatus(inv){if(inv.type==='credit')return'RECTIFICATIVA';if(inv.status==='void')return'ANULADA';if(inv.status==='draft')return'BORRADOR';const x=calcInvoice(inv);if(x.paymentStatus==='paid')return'PAGADA';if(x.paymentStatus==='partial')return'PARCIAL';if(inv.dueDate&&daysBetween(inv.dueDate)>0)return'VENCIDA';return'PENDIENTE'}
export function stockQty(state,productId,location='ALL'){return round2((state.stockMovements||[]).filter(m=>m.productId===productId&&(location==='ALL'||m.location===location)).reduce((s,m)=>s+n(m.qty),0))}
export function reservedQty(state,productId){const p=(state.products||[]).find(x=>x.id===productId);return round2((state.orders||[]).filter(o=>!['delivered','cancelled','invoiced'].includes(o.status)).flatMap(o=>o.lines||[]).filter(l=>l.productId===productId).reduce((s,l)=>s+(p?.mode==='caja_kg'?n(l.requestedQty||l.qty)*n(p.kgPerBox):n(l.requestedQty||l.qty)),0))}
export function stockForProduct(state,productId,location='ALL'){const physical=stockQty(state,productId,location),reserved=location==='ALL'?reservedQty(state,productId):0;return {physical,reserved,available:round2(physical-reserved)}}
export function stockDisplay(p,qty){if(p.mode==='caja_kg'&&n(p.kgPerBox)>0)return `${round2(n(qty)/n(p.kgPerBox))} CAJAS · ${round2(qty)} KG`;return `${round2(qty)} ${String(p.unit||p.mode).toUpperCase()}`}
export function clientBalance(state,id){return round2((state.invoices||[]).filter(i=>i.clientId===id&&!['void','draft'].includes(i.status)).reduce((s,i)=>s+calcInvoice(i).pending,0))}
export function clientAging(state,id){const out={'0-7':0,'8-15':0,'16-30':0,'31-60':0,'61-90':0,'+90':0};(state.invoices||[]).filter(i=>i.clientId===id&&!['void','draft'].includes(i.status)).map(calcInvoice).filter(i=>i.pending>0).forEach(i=>out[ageBucket(i.dueDate||i.date)]+=i.pending);return Object.fromEntries(Object.entries(out).map(([k,v])=>[k,round2(v)]))}
export function marginLine(l){const x=calcLine(l);const q=x.mode==='caja_kg'?n(x.net):n(x.qty);const cost=round2(q*n(x.buyPriceSnapshot));return {revenue:x.base,cost,profit:round2(x.base-cost),margin:x.base?round2((x.base-cost)/x.base*100):0}}
export const stockMove=(productId,qty,type,location='ALMACEN',sourceId='',note='',lotId='')=>({id:uid('mov'),productId,qty:round2(qty),type,location,sourceId,note,lotId,date:new Date().toISOString().slice(0,10),createdAt:nowISO()});
export const nextInvoiceNo=s=>`${s.invoiceSeries||'FA'}-${String(n(s.nextInvoiceNumber||1)).padStart(n(s.invoiceDigits||5),'0')}`;
export function invoiceValidation(inv,state){const errors=[],warnings=[];const x=calcInvoice(inv);if(!inv.clientId)errors.push('FALTA CLIENTE');if(!x.lines.length)errors.push('NO HAY LÍNEAS FACTURABLES');for(const l of x.lines){if(l.mode==='caja_kg'&&!n(l.kgPerBox))errors.push(`${l.product}: FALTA KG/CAJA`);if(![0,4,10,21].includes(n(l.vat)))warnings.push(`${l.product}: IVA ${l.vat}% NO ESTÁ ENTRE LOS TIPOS HABITUALES`);if(n(l.price)<n(l.buyPriceSnapshot))warnings.push(`${l.product}: PRECIO POR DEBAJO DEL COSTE`);const prev=[...(state.invoices||[])].filter(i=>i.id!==inv.id&&i.clientId===inv.clientId&&!['draft','void'].includes(i.status)).sort((a,b)=>String(b.date).localeCompare(String(a.date))).map(i=>(i.lines||[]).find(z=>z.productId===l.productId)).find(Boolean);if(prev&&n(l.price)+0.001<n(prev.price))warnings.push(`${l.product}: PRECIO ${l.price} MENOR QUE ÚLTIMO ${prev.price}`)}if(inv.sourceOrderId){const o=state.orders.find(o=>o.id===inv.sourceOrderId);if(o)for(const l of x.lines){const ol=(o.lines||[]).find(a=>a.productId===l.productId);if(ol&&n(l.qty)>n(ol.deliveredQty))warnings.push(`${l.product}: FACTURAS ${l.qty} Y SE ENTREGARON ${ol.deliveredQty}`)}}const c=(state.clients||[]).find(c=>c.id===inv.clientId);if(c&&n(c.creditLimit)>0){const existing=clientBalance(state,c.id),projected=round2(existing+x.pending);if(projected>n(c.creditLimit))warnings.push(`LÍMITE DE CRÉDITO: ${projected.toFixed(2)} € > ${n(c.creditLimit).toFixed(2)} €`)}return {errors,warnings,invoice:x}}
