import {Store} from './store.js';
import {calcInvoice,invoiceStatus,MODES,clientBalance} from './domain.js';
import {upper,money,num} from './utils.js';
const fmtDate=d=>d?new Intl.DateTimeFormat('es-ES').format(new Date(`${d}T12:00:00`)):'';
const jsPDF=()=>window.jspdf?.jsPDF;
async function dataUrl(url){if(!url)return'';try{const r=await fetch(url);const b=await r.blob();return await new Promise((res,rej)=>{const fr=new FileReader();fr.onload=()=>res(fr.result);fr.onerror=rej;fr.readAsDataURL(b)})}catch{return''}}
async function qrData(text){try{return await window.QRCode.toDataURL(text,{margin:0,width:180})}catch{return''}}
function fileName(inv,c){const p=inv.type==='credit'?'FACTURA_RECTIFICATIVA':'FACTURA';return `${p}_${upper(c?.name||'CLIENTE').replace(/[^A-Z0-9]+/g,'_')}_${inv.date||''}_${inv.number||'BORRADOR'}.pdf`}
export async function invoicePdf(inv,client,{blob=false,internal=false,previousBalance=null}={}){const C=jsPDF();if(!C)throw new Error('MOTOR PDF NO DISPONIBLE');const x=calcInvoice(inv),s=Store.state.settings,credit=x.type==='credit';const doc=new C({unit:'mm',format:'a4'});doc.setProperties({title:`${credit?'FACTURA RECTIFICATIVA':'FACTURA'} ${x.number||'BORRADOR'}`,author:upper(s.companyName),subject:'ARW2026'});const logo=await dataUrl(s.logoUrl);if(logo)try{doc.addImage(logo,'PNG',14,10,28,18)}catch{}doc.setFont('helvetica','bold');doc.setFontSize(credit?17:22);doc.text(credit?'FACTURA RECTIFICATIVA':'FACTURA',logo?48:14,17);doc.setFontSize(9);doc.text(upper(x.number||'BORRADOR'),196,13,{align:'right'});doc.setFont('helvetica','normal');doc.text(`FECHA: ${fmtDate(x.date)}`,196,18,{align:'right'});doc.text(`ESTADO: ${invoiceStatus(x)}`,196,23,{align:'right'});if(x.status==='draft'||x.status==='void'){doc.setTextColor(220,38,38);doc.setFontSize(40);doc.text(x.status==='draft'?'BORRADOR':'ANULADA',105,145,{align:'center',angle:35});doc.setTextColor(0)}doc.setDrawColor(210);doc.line(14,30,196,30);
doc.setFont('helvetica','bold');doc.setFontSize(9);doc.text('PROVEEDOR',14,37);doc.text('CLIENTE',110,37);doc.setFont('helvetica','normal');doc.setFontSize(8.4);const left=[upper(s.companyName),`NIF: ${upper(s.companyNif)}`,upper(s.companyAddress),`${s.companyPhone||''}${s.companyEmail?` · ${s.companyEmail}`:''}`];const right=[upper(client?.name||''),client?.nif?`NIF: ${upper(client.nif)}`:'',upper(client?.address||''),client?.phone||''].filter(Boolean);left.forEach((v,i)=>doc.text(v,14,43+i*4.4));right.forEach((v,i)=>doc.text(v,110,43+i*4.4));if(credit&&x.originalInvoiceNumber){doc.setFont('helvetica','bold');doc.text(`RECTIFICA: ${upper(x.originalInvoiceNumber)}`,14,61)}
const compact=s.invoiceTemplate==='compact'&&!internal;const body=x.lines.map(l=>{let row=compact?[upper(l.code),upper(l.product),l.mode==='caja_kg'?`${num(l.qty)} CAJ. / ${num(l.net)} KG`:`${num(l.qty)} ${upper(l.unit)}`,`${num(l.price)} €`,`${num(l.vat)}%`,money(l.base)]:[upper(l.code),upper(l.product),upper(MODES[l.mode]||l.mode),l.mode==='caja_kg'?`${num(l.qty)} CAJ.`:`${num(l.qty)} ${upper(l.unit)}`,l.mode==='caja_kg'?num(l.kgPerBox):'—',l.mode==='caja_kg'&&Number(l.gross)>0?num(l.gross):'—',l.mode==='caja_kg'&&Number(l.tare)>0?num(l.tare):'—',l.mode==='caja_kg'?`${num(l.net)} KG`:num(l.net),`${num(l.price)} €`,`${num(l.vat)}%`,money(l.base)];if(internal)row.push(`${num(l.buyPriceSnapshot)} €`,`${num(l.base-(l.mode==='caja_kg'?l.net:l.qty)*l.buyPriceSnapshot)} €`);return row});const head=compact?['CÓD.','PRODUCTO','CANT./NETO','PRECIO','IVA','IMPORTE']:['CÓD.','PRODUCTO','MODO','CANT.','KG/CAJA','BRUTO','TARA','NETO','PRECIO','IVA','IMPORTE'];if(internal)head.push('COSTE','MARGEN');doc.autoTable({startY:65,head:[head],body,theme:'grid',styles:{font:'helvetica',fontSize:internal?5.5:compact?7.5:6.2,cellPadding:1.25},headStyles:{fillColor:[11,18,32],textColor:255,fontStyle:'bold'},didDrawPage:()=>{doc.setFontSize(7);doc.setTextColor(100);doc.text(`${upper(x.number||'BORRADOR')} · ${upper(client?.name||'')} · PÁGINA ${doc.internal.getNumberOfPages()}`,196,290,{align:'right'});doc.setTextColor(0)}});
let y=doc.lastAutoTable.finalY+7;if(y>235){doc.addPage();y=20}doc.setFontSize(8.5);const rows=[['SUBTOTAL PRODUCTOS',x.productBase],['TRANSPORTE',x.transportBase],['DESCUENTO',-x.globalDiscount],['BASE IMPONIBLE',x.base]];for(const [k,v] of rows){if(k==='DESCUENTO'&&!v)continue;doc.text(k,132,y);doc.text(money(v),196,y,{align:'right'});y+=4.6}for(const v of x.vatBreakdown){doc.text(`IVA ${v.rate}% · BASE ${money(v.base)}`,132,y);doc.text(money(v.vat),196,y,{align:'right'});y+=4.6}doc.setDrawColor(30);doc.line(132,y,196,y);y+=6;doc.setFont('helvetica','bold');doc.setFontSize(13);doc.text(credit?'TOTAL RECTIFICACIÓN':'TOTAL FACTURA',132,y);doc.text(money(x.total),196,y,{align:'right'});y+=7;doc.setFont('helvetica','normal');doc.setFontSize(8.5);if(!credit){doc.text(`PAGADO: ${money(x.paid)}`,132,y);doc.text(`PENDIENTE: ${money(x.pending)}`,196,y,{align:'right'});y+=5;doc.text(`FORMA DE PAGO: ${upper(x.paymentMethod||client?.paymentMethod||'PENDIENTE')}`,132,y);if(x.dueDate){y+=5;doc.text(`VENCIMIENTO: ${fmtDate(x.dueDate)}`,132,y)}if((x.showPreviousBalance??s.showPreviousBalance)&&previousBalance!=null){y+=5;doc.setFont('helvetica','bold');doc.text(`SALDO ANTERIOR: ${money(previousBalance)}`,132,y);doc.text(`SALDO TOTAL: ${money(previousBalance+x.pending)}`,196,y,{align:'right'});doc.setFont('helvetica','normal')}}if(s.iban){y+=6;doc.text(`IBAN: ${upper(s.iban)}`,132,y)}if(x.notes){y+=8;doc.setFont('helvetica','bold');doc.text('OBSERVACIONES',14,y);doc.setFont('helvetica','normal');doc.text(doc.splitTextToSize(upper(x.notes),110),14,y+5)}if(x.reason){y+=8;doc.setFont('helvetica','bold');doc.text('MOTIVO DE RECTIFICACIÓN',14,y);doc.setFont('helvetica','normal');doc.text(doc.splitTextToSize(upper(x.reason),110),14,y+5)}const qr=await qrData(`ARW2026|${x.id}|${x.number||'BORRADOR'}|${x.total}`);if(qr)try{doc.addImage(qr,'PNG',14,258,22,22);doc.setFontSize(6.5);doc.text('IDENTIFICADOR INTERNO ARW2026',14,284)}catch{}return blob?doc.output('blob'):(doc.save(fileName(x,client)),doc)}
export async function invoicesZip(list,clients,date){const zip=new JSZip();for(const inv of list){const c=clients.find(x=>x.id===inv.clientId);zip.file(fileName(inv,c),await invoicePdf(inv,c,{blob:true}))}return {blob:await zip.generateAsync({type:'blob'}),name:`FACTURAS_${date}.zip`}}
export function summaryPdf(title,headers,rows,name='INFORME.pdf'){const C=jsPDF();const doc=new C();doc.setFont('helvetica','bold');doc.setFontSize(18);doc.text(upper(title),14,18);doc.autoTable({startY:25,head:[headers.map(upper)],body:rows,styles:{fontSize:7.5},headStyles:{fillColor:[11,18,32]}});doc.save(name)}
export function paymentReceipt(payment,client,invoice=null){const C=jsPDF();const doc=new C();doc.setFont('helvetica','bold');doc.setFontSize(18);doc.text('JUSTIFICANTE DE COBRO',14,18);doc.setFontSize(10);doc.text(upper(client?.name||''),14,32);doc.setFont('helvetica','normal');doc.text(`FECHA: ${fmtDate(payment.date)}`,14,40);doc.text(`IMPORTE: ${money(payment.amount)}`,14,47);doc.text(`MÉTODO: ${upper(payment.method||'')}`,14,54);if(invoice)doc.text(`FACTURA: ${upper(invoice.number||'')}`,14,61);if(payment.note)doc.text(`NOTA: ${upper(payment.note)}`,14,68);doc.save(`COBRO_${upper(client?.name||'CLIENTE').replace(/\W+/g,'_')}_${payment.date}.pdf`)}
export function statementPdf(client,invoices,payments){const C=jsPDF();const doc=new C();doc.setFont('helvetica','bold');doc.setFontSize(17);doc.text('ESTADO DE CUENTA',14,18);doc.setFontSize(10);doc.text(upper(client.name),14,27);const rows=[];for(const i of invoices){const x=calcInvoice(i);rows.push([i.date,i.number||'',invoiceStatus(i),money(x.total),money(x.paid),money(x.pending)])}doc.autoTable({startY:34,head:[['FECHA','DOCUMENTO','ESTADO','TOTAL','PAGADO','PENDIENTE']],body:rows,styles:{fontSize:8},headStyles:{fillColor:[11,18,32]}});const bal=invoices.filter(i=>!['draft','void'].includes(i.status)).reduce((s,i)=>s+calcInvoice(i).pending,0);doc.setFont('helvetica','bold');doc.text(`SALDO ACTUAL: ${money(bal)}`,196,doc.lastAutoTable.finalY+10,{align:'right'});doc.save(`ESTADO_CUENTA_${upper(client.name).replace(/\W+/g,'_')}.pdf`)}
export function routePdf(route,clients,orders){const C=jsPDF();const doc=new C();doc.setFont('helvetica','bold');doc.setFontSize(17);doc.text(`RUTA · ${upper(route.name||route.date||'')}`,14,18);const rows=(route.stops||[]).map((s,i)=>{const c=clients.find(x=>x.id===s.clientId),o=orders.find(x=>x.id===s.orderId);return [i+1,upper(c?.name||''),upper(c?.address||''),c?.phone||'',upper(o?.status||''),s.note||'']});doc.autoTable({startY:26,head:[['#','CLIENTE','DIRECCIÓN','TELÉFONO','ESTADO','NOTA']],body:rows,styles:{fontSize:7.5},headStyles:{fillColor:[11,18,32]}});doc.save(`RUTA_${route.date||''}.pdf`)}
