import {Store} from './store.js';
import {toast} from './utils.js';
const KEY='arw2026_v2_device_pin',UNLOCK='arw2026_v2_unlocked';const enc=new TextEncoder();
async function hash(pin,salt){const b=await crypto.subtle.digest('SHA-256',enc.encode(`${salt}:${pin}`));return [...new Uint8Array(b)].map(x=>x.toString(16).padStart(2,'0')).join('')}
function cfg(){try{return JSON.parse(localStorage.getItem(KEY)||'null')}catch{return null}}
function salt(){return [...crypto.getRandomValues(new Uint8Array(16))].map(x=>x.toString(16).padStart(2,'0')).join('')}
export async function setupPin(){const p=prompt('CREA UN PIN DE 4 A 8 DÍGITOS');if(!/^\d{4,8}$/.test(p||''))return toast('PIN NO VÁLIDO','bad');const p2=prompt('REPITE EL PIN');if(p!==p2)return toast('LOS PIN NO COINCIDEN','bad');const s=salt();localStorage.setItem(KEY,JSON.stringify({salt:s,hash:await hash(p,s)}));sessionStorage.setItem(UNLOCK,'1');toast('PIN RÁPIDO ACTIVADO','ok')}
export function removePin(){if(confirm('¿DESACTIVAR PIN RÁPIDO?')){localStorage.removeItem(KEY);sessionStorage.removeItem(UNLOCK);toast('PIN DESACTIVADO')}}
export function lockNow(){if(!cfg())return toast('PRIMERO ACTIVA UN PIN','bad');sessionStorage.removeItem(UNLOCK);showLock()}
export function showLock(){const c=cfg();if(!c||!Store.user||sessionStorage.getItem(UNLOCK)==='1'||document.getElementById('arwPinLock'))return;const d=document.createElement('div');d.id='arwPinLock';d.className='modal-backdrop';d.innerHTML='<div class="modal small"><div class="modal-body center"><div style="font-size:40px">🔐</div><h2>ARW2026</h2><p>INTRODUCE EL PIN DE ESTE DISPOSITIVO</p><input id="arwPinInput" type="password" inputmode="numeric" maxlength="8" style="font-size:24px;text-align:center"><button id="arwPinGo" class="btn primary full">DESBLOQUEAR</button><button id="arwPinLogout" class="btn full">CERRAR SESIÓN</button><p id="arwPinError" class="danger hidden"></p></div></div>';document.body.appendChild(d);const attempt=async()=>{const ok=await hash(d.querySelector('#arwPinInput').value,c.salt)===c.hash;if(ok){sessionStorage.setItem(UNLOCK,'1');d.remove()}else{const e=d.querySelector('#arwPinError');e.textContent='PIN INCORRECTO';e.classList.remove('hidden')}};d.querySelector('#arwPinGo').onclick=attempt;d.querySelector('#arwPinInput').onkeydown=e=>e.key==='Enter'&&attempt();d.querySelector('#arwPinLogout').onclick=()=>{d.remove();Store.logout()};setTimeout(()=>d.querySelector('#arwPinInput').focus(),50)}
Store.subscribe(()=>setTimeout(showLock,0));
