import {ARW} from '../../firebase-config.js';
import {Auth,col,ref,settingsRef,readCollection,DB,Storage,db} from './firebase.js';
import {uid,nowISO,isoDate,monthKey} from './utils.js';

export const COLLECTIONS=['clients','products','suppliers','orders','orderTemplates','routes','deliveries','invoices','payments','purchases','supplierPayments','stockMovements','lots','transfers','wastes','returns','inventoryCounts','expenses','cashMovements','bankAccounts','bankMovements','quotes','proformas','deliveryNotes','priceHistory','priceChanges','communications','attachments','closures','audit','members','containers','notifications','backups','businessUnits','series'];
const defaults={id:'main',appName:'ARW2026',companyName:'MOHAMMAD ARSLAN WARIS',tradeName:'ARW2026',companyNif:'X6389988J',companyAddress:'CALLE SAN PABLO 17, 09003 BURGOS',companyPhone:'631 667 893',companyEmail:ARW.ownerEmail,iban:'',logoUrl:'',invoiceSeries:'FA',nextInvoiceNumber:1,invoiceDigits:5,defaultVat:4,defaultTransport:10,defaultDueDays:0,currency:'EUR',invoiceTemplate:'professional',showPreviousBalance:false,minMargin:15,locations:['ALMACEN','FURGONETA','SAN PABLO','SAN LESMES','SANTIAGO'],lockedPeriods:[],features:{googleLogin:true,storage:true,verifactu:false,webhooks:false,push:false},version:ARW.version};
const blank=()=>Object.fromEntries([['settings',{...defaults}],...COLLECTIONS.map(c=>[c,[]])]);
let state=blank(),user=null,role='none',ready=false,online=navigator.onLine,lastError='',syncing=false;
const listeners=new Set();const cacheKey='arw2026_v2_cache';
function emit(){listeners.forEach(fn=>fn(state,{user,role,ready,online,lastError,syncing}))}
function cache(){try{localStorage.setItem(cacheKey,JSON.stringify(state))}catch{}}
try{const cached=JSON.parse(localStorage.getItem(cacheKey)||'null');if(cached)state={...blank(),...cached,settings:{...defaults,...cached.settings}}}catch{}
function isOwner(){return !!user&&(user.uid===ARW.ownerUid||String(user.email||'').toLowerCase()===ARW.ownerEmail.toLowerCase())}
function arr(name){if(!Array.isArray(state[name]))state[name]=[];return state[name]}
function localUpsert(name,obj){const a=arr(name),i=a.findIndex(x=>x.id===obj.id);if(i<0)a.unshift(obj);else a[i]={...a[i],...obj};cache();emit()}
async function audit(action,entity,entityId,details={}){if(!user)return;const a={id:uid('audit'),action,entity,entityId,details,userUid:user.uid,userEmail:user.email,at:nowISO()};try{await DB.setDoc(ref('audit',a.id),a)}catch{}if(['owner','admin','manager'].includes(role))arr('audit').unshift(a)}
function ensureCanWrite(name){if(['owner','admin','manager'].includes(role))return true;const map={billing:['clients','orders','orderTemplates','deliveries','invoices','payments','quotes','proformas','deliveryNotes','priceHistory','priceChanges','communications','attachments','cashMovements','bankMovements','lots'],warehouse:['products','suppliers','purchases','supplierPayments','stockMovements','lots','transfers','wastes','returns','inventoryCounts','containers','attachments'],delivery:['orders','routes','deliveries','communications','attachments','containers']};if(map[role]?.includes(name))return true;throw new Error(`SIN PERMISO PARA ${name.toUpperCase()}`)}
function invoiceMutationAllowed(old,next,action){if(!old||old.status==='draft')return true;if(['mark_sent','payment_status','void','rectify_link','audit_fix'].includes(action))return true;const stable=['lines','clientId','date','number','base','vatTotal','total','transportType','transportValue','discount','type'];return stable.every(k=>JSON.stringify(old[k])===JSON.stringify(next[k]))}
async function save(name,obj,action='update',details={}){ensureCanWrite(name);const next={...obj,id:obj.id||uid(name.slice(0,3)),updatedAt:nowISO()};if(name==='invoices'){const old=arr(name).find(x=>x.id===next.id);if(!invoiceMutationAllowed(old,next,action))throw new Error('FACTURA EMITIDA BLOQUEADA: USA RECTIFICATIVA O ANULACIÓN')}localUpsert(name,next);if(user){try{await DB.setDoc(ref(name,next.id),next,{merge:true});online=navigator.onLine;lastError='';await audit(action,name,next.id,details)}catch(e){lastError=e.code||e.message;online=navigator.onLine;emit();throw e}}return next}
async function remove(name,id,action='delete'){ensureCanWrite(name);const old=arr(name).find(x=>x.id===id);if(name==='invoices'&&old?.status!=='draft')throw new Error('SOLO SE PUEDEN BORRAR BORRADORES');state[name]=arr(name).filter(x=>x.id!==id);cache();emit();if(user){await DB.deleteDoc(ref(name,id));await audit(action,name,id)}}
async function bulkSave(name,items,action='bulk_update'){ensureCanWrite(name);if(!items.length)return[];const batch=DB.writeBatch(db);for(const item0 of items){const item={...item0,id:item0.id||uid(name.slice(0,3)),updatedAt:nowISO()};batch.set(ref(name,item.id),item,{merge:true});localUpsert(name,item)}await batch.commit();await audit(action,name,'multiple',{count:items.length});return items}
async function saveSettings(patch){if(!['owner','admin','manager'].includes(role))throw new Error('SOLO ADMINISTRACIÓN');state.settings={...state.settings,...patch,id:'main',updatedAt:nowISO()};cache();emit();await DB.setDoc(settingsRef(),state.settings,{merge:true});await audit('settings','settings','main',{keys:Object.keys(patch)});return state.settings}
async function ensureMember(){if(isOwner()){role='owner';const m={id:user.uid,email:user.email||ARW.ownerEmail,name:'ADMINISTRADOR',role:'owner',active:true,updatedAt:nowISO()};try{await DB.setDoc(ref('members',user.uid),m,{merge:true})}catch{}return}const s=await DB.getDoc(ref('members',user.uid));if(s.exists()&&s.data().active)role=s.data().role||'viewer';else role='none'}
async function seed(){if(state.products.length)return;const P=(code,name,mode,unit,kgPerBox,buy,sell,vat,minStock=0,barcode='')=>({id:uid('prod'),code,name,mode,unit,kgPerBox,buyPrice:buy,sellPrice:sell,vat,minStock,barcode,active:true,createdAt:nowISO()});const products=[P('MM','MACHO MADURO','caja_kg','kg',22,1.60,1.90,4,44),P('MV','MACHO VERDE','caja_kg','kg',22,1.25,1.55,4,44),P('BN','BANANA','caja_kg','kg',19,1,1.30,4,38),P('GU','GUINEO','caja_kg','kg',20,1.20,1.50,4,40),P('YU','YUCA','caja_kg','kg',18,1.40,1.80,4,36),P('NM','ÑAME','caja_kg','kg',20,1.99,2.40,4,20),P('ML','MALANGA','caja_kg','kg',12,3.25,3.80,4,12),P('YT','YAUTÍA','caja_kg','kg',10,3.25,3.80,4,10),P('LM','LIMA','caja_fija','caja',0,10,12.50,4,2),P('CL','CILANTRO','manojo','manojo',0,.40,.60,10,50),P('NZ','NARANJA ZUMO','kg','kg',0,.75,.99,4,20),P('CR','CEBOLLA ROJA','caja_kg','kg',10,1,1.30,4,20),P('TD','TOMATE DANIELA','caja_kg','kg',8,1.50,2.20,4,16)];for(const p of products)await save('products',p,'seed').catch(()=>{});if(!state.businessUnits.length)await save('businessUnits',{id:'main',name:'ARW2026',active:true,series:'FA'},'seed').catch(()=>{});if(!state.series.length)await save('series',{id:'FA',name:'FACTURAS',prefix:'FA',next:1,digits:5,active:true},'seed').catch(()=>{})}
function canReadCollection(name){if(['owner','admin','manager'].includes(role))return true;const map={billing:['clients','products','orders','orderTemplates','deliveries','invoices','payments','quotes','proformas','deliveryNotes','priceHistory','priceChanges','communications','attachments','closures','series','businessUnits','cashMovements','bankAccounts','bankMovements','expenses','notifications','lots'],warehouse:['products','suppliers','purchases','supplierPayments','stockMovements','lots','transfers','wastes','returns','inventoryCounts','containers','attachments','orders','businessUnits','notifications'],delivery:['clients','products','orders','routes','deliveries','communications','attachments','containers','notifications'],viewer:['clients','products']};return map[role]?.includes(name)||false}
async function load(){const ss=await DB.getDoc(settingsRef());if(ss.exists())state.settings={...defaults,...ss.data()};else if(['owner','admin','manager'].includes(role))await DB.setDoc(settingsRef(),state.settings,{merge:true});for(const c of COLLECTIONS){if(!canReadCollection(c)){state[c]=[];continue}try{state[c]=await readCollection(c)}catch(e){state[c]=[];if(!['audit','members'].includes(c))throw e}}if(['owner','admin','manager','warehouse'].includes(role))await seed();cache();online=navigator.onLine;lastError='';emit()}
async function reserveInvoiceNumber(seriesId=''){if(!user)throw new Error('SIN SESIÓN');const sid=seriesId||state.settings.invoiceSeries||'FA',localSeries=state.series.find(x=>x.id===sid),useSeries=!!localSeries,sref=useSeries?ref('series',sid):settingsRef();return DB.runTransaction(db,async tx=>{const snap=await tx.get(sref),data=snap.exists()?snap.data():{},next=Number(useSeries?data.next:data.nextInvoiceNumber)||1,prefix=useSeries?(data.prefix||sid):(data.invoiceSeries||'FA'),digits=Number(useSeries?data.digits:data.invoiceDigits)||5;tx.set(sref,useSeries?{next:next+1,updatedAt:nowISO()}:{nextInvoiceNumber:next+1,updatedAt:nowISO()},{merge:true});if(useSeries)localSeries.next=next+1;else state.settings.nextInvoiceNumber=next+1;cache();return `${prefix}-${String(next).padStart(digits,'0')}`})}
async function uploadAttachment(folder,entityId,file){ensureCanWrite('attachments');const key=`${folder}/${entityId}/${Date.now()}_${String(file.name).replace(/[^a-zA-Z0-9._-]/g,'_')}`;const up=await Storage.upload(key,file);const a={id:uid('att'),entityType:folder,entityId,name:file.name,path:up.path,url:up.url,type:file.type,size:file.size,createdAt:nowISO()};await save('attachments',a,'attachment');return a}
async function backupRemote(){const blob=new Blob([JSON.stringify(state)],{type:'application/json'});const file=new File([blob],`ARW2026_${nowISO().replace(/[:.]/g,'-')}.json`,{type:'application/json'});const up=await Storage.upload(`backups/${file.name}`,file);const meta={id:uid('bak'),date:isoDate(),month:monthKey(),url:up.url,path:up.path,size:up.size,createdAt:nowISO()};await save('backups',meta,'backup');return meta}
function onAuth(u){user=u;ready=false;lastError='';emit();if(!u){role='none';ready=true;emit();return}queueMicrotask(async()=>{try{await ensureMember();if(role==='none')throw new Error('SIN PERMISO PARA ARW2026');await load()}catch(e){lastError=e.code||e.message||String(e);if(isOwner())role='owner';console.error(e)}finally{ready=true;emit()}})}
export const Store={get state(){return state},get user(){return user},get role(){return role},get ready(){return ready},get online(){return online},get lastError(){return lastError},subscribe(fn){listeners.add(fn);fn(state,{user,role,ready,online,lastError,syncing});return()=>listeners.delete(fn)},login:Auth.email,loginGoogle:Auth.google,logout:Auth.logout,save,remove,bulkSave,saveSettings,audit,load,reserveInvoiceNumber,uploadAttachment,backupRemote,uid,isoDate,can(scope){return['owner','admin','manager'].includes(role)||role===scope},async waitSync(){syncing=true;emit();try{await DB.waitForPendingWrites(db)}finally{syncing=false;emit()}}};
// Register auth only after Store has been fully initialized: avoids temporal-dead-zone/circular startup bugs on Safari/iOS.
queueMicrotask(()=>{Auth.on(onAuth);Auth.redirect().catch(()=>{})});
addEventListener('online',()=>{online=true;emit()});addEventListener('offline',()=>{online=false;emit()});
