import https from 'node:https';
import {initializeApp} from 'firebase-admin/app';
import {getFirestore,FieldValue} from 'firebase-admin/firestore';
import {defineSecret} from 'firebase-functions/params';
import {onCall,HttpsError} from 'firebase-functions/v2/https';
import {onSchedule} from 'firebase-functions/v2/scheduler';

initializeApp();const db=getFirestore(),PFX=defineSecret('VERIFACTU_PFX_BASE64'),PFX_PASSWORD=defineSecret('VERIFACTU_PFX_PASSWORD');
const OWNER_UID='o6rMhcEyUXUstmb7ptClXSv8ejQ2',ROOT='companies/arw2026';
const TEST='https://prewww1.aeat.es/wlpl/TIKE-CONT/ws/SistemaFacturacion/VerifactuSOAP',PROD='https://www1.agenciatributaria.gob.es/wlpl/TIKE-CONT/ws/SistemaFacturacion/VerifactuSOAP';
const esc=v=>String(v??'').replace(/&/g,'&amp;').replace(/</g,'&lt;').replace(/>/g,'&gt;').replace(/"/g,'&quot;').replace(/'/g,'&apos;');
async function role(uid){if(uid===OWNER_UID)return'owner';const s=await db.doc(`${ROOT}/members/${uid}`).get();return s.exists&&s.data().active!==false?s.data().role:'none'}
function allowed(r){return['owner','admin','manager','billing'].includes(r)}
function systemXml(s){return `<sf:SistemaInformatico><sf:NombreRazon>${esc(s.producerName)}</sf:NombreRazon><sf:NIF>${esc(s.producerNif)}</sf:NIF><sf:NombreSistemaInformatico>${esc(s.name)}</sf:NombreSistemaInformatico><sf:IdSistemaInformatico>${esc(s.id)}</sf:IdSistemaInformatico><sf:Version>${esc(s.version)}</sf:Version><sf:NumeroInstalacion>${esc(s.installation)}</sf:NumeroInstalacion><sf:TipoUsoPosibleSoloVerifactu>S</sf:TipoUsoPosibleSoloVerifactu><sf:TipoUsoPosibleMultiOT>N</sf:TipoUsoPosibleMultiOT><sf:IndicadorMultiplesOT>N</sf:IndicadorMultiplesOT></sf:SistemaInformatico>`}
function previousXml(r,idTag='IDEmisorFactura'){if(!r.previousHash)return'<sf:PrimerRegistro>S</sf:PrimerRegistro>';return `<sf:RegistroAnterior><sf:${idTag}>${esc(r.issuerNif)}</sf:${idTag}><sf:NumSerieFactura>${esc(r.previousInvoiceNumber)}</sf:NumSerieFactura><sf:FechaExpedicionFactura>${esc(r.previousInvoiceDate)}</sf:FechaExpedicionFactura><sf:Huella>${esc(r.previousHash)}</sf:Huella></sf:RegistroAnterior>`}
function breakdownXml(r){return (r.breakdown||[]).map(v=>`<sf:DetalleDesglose><sf:Impuesto>${esc(v.tax||'01')}</sf:Impuesto><sf:ClaveRegimen>${esc(v.regime||'01')}</sf:ClaveRegimen><sf:CalificacionOperacion>${esc(v.qualification||'S1')}</sf:CalificacionOperacion><sf:TipoImpositivo>${Number(v.rate||0).toFixed(2)}</sf:TipoImpositivo><sf:BaseImponibleOimporteNoSujeto>${Number(v.base||0).toFixed(2)}</sf:BaseImponibleOimporteNoSujeto><sf:CuotaRepercutida>${Number(v.vat||0).toFixed(2)}</sf:CuotaRepercutida>${Number(v.reRate||0)?`<sf:TipoRecargoEquivalencia>${Number(v.reRate).toFixed(2)}</sf:TipoRecargoEquivalencia><sf:CuotaRecargoEquivalencia>${Number(v.re||0).toFixed(2)}</sf:CuotaRecargoEquivalencia>`:''}</sf:DetalleDesglose>`).join('')}
function header(r){return `<sfLR:Cabecera><sf:ObligadoEmision><sf:NombreRazon>${esc(r.issuerName||'')}</sf:NombreRazon><sf:NIF>${esc(r.issuerNif)}</sf:NIF></sf:ObligadoEmision></sfLR:Cabecera>`}
function altaXml(r){const dest=r.clientNif?`<sf:Destinatarios><sf:IDDestinatario><sf:NombreRazon>${esc(r.clientName||'CLIENTE')}</sf:NombreRazon><sf:NIF>${esc(r.clientNif)}</sf:NIF></sf:IDDestinatario></sf:Destinatarios>`:'',rect=String(r.invoiceType||'').startsWith('R')?`<sf:TipoRectificativa>${esc(r.rectificationType||'I')}</sf:TipoRectificativa>`:'';return `<sfLR:RegistroFactura><sf:RegistroAlta><sf:IDVersion>1.0</sf:IDVersion><sf:IDFactura><sf:IDEmisorFactura>${esc(r.issuerNif)}</sf:IDEmisorFactura><sf:NumSerieFactura>${esc(r.invoiceNumber)}</sf:NumSerieFactura><sf:FechaExpedicionFactura>${esc(r.invoiceDate)}</sf:FechaExpedicionFactura></sf:IDFactura><sf:NombreRazonEmisor>${esc(r.issuerName||'')}</sf:NombreRazonEmisor><sf:TipoFactura>${esc(r.invoiceType||'F1')}</sf:TipoFactura>${rect}<sf:DescripcionOperacion>${esc(r.description||'VENTA DE MERCANCÍAS')}</sf:DescripcionOperacion>${dest}<sf:Desglose>${breakdownXml(r)}</sf:Desglose><sf:CuotaTotal>${esc(r.vatTotalText)}</sf:CuotaTotal><sf:ImporteTotal>${esc(r.totalText)}</sf:ImporteTotal><sf:Encadenamiento>${previousXml(r)}</sf:Encadenamiento>${systemXml(r.system||{})}<sf:FechaHoraHusoGenRegistro>${esc(r.generatedAt)}</sf:FechaHoraHusoGenRegistro><sf:TipoHuella>01</sf:TipoHuella><sf:Huella>${esc(r.hash)}</sf:Huella></sf:RegistroAlta></sfLR:RegistroFactura>`}
function anulXml(r){const chain=r.previousHash?`<sf:RegistroAnterior><sf:IDEmisorFactura>${esc(r.issuerNif)}</sf:IDEmisorFactura><sf:NumSerieFactura>${esc(r.previousInvoiceNumber)}</sf:NumSerieFactura><sf:FechaExpedicionFactura>${esc(r.previousInvoiceDate)}</sf:FechaExpedicionFactura><sf:Huella>${esc(r.previousHash)}</sf:Huella></sf:RegistroAnterior>`:'<sf:PrimerRegistro>S</sf:PrimerRegistro>';return `<sfLR:RegistroFactura><sf:RegistroAnulacion><sf:IDVersion>1.0</sf:IDVersion><sf:IDFactura><sf:IDEmisorFacturaAnulada>${esc(r.issuerNif)}</sf:IDEmisorFacturaAnulada><sf:NumSerieFacturaAnulada>${esc(r.invoiceNumber)}</sf:NumSerieFacturaAnulada><sf:FechaExpedicionFacturaAnulada>${esc(r.invoiceDate)}</sf:FechaExpedicionFacturaAnulada></sf:IDFactura><sf:Encadenamiento>${chain}</sf:Encadenamiento>${systemXml(r.system||{})}<sf:FechaHoraHusoGenRegistro>${esc(r.generatedAt)}</sf:FechaHoraHusoGenRegistro><sf:TipoHuella>01</sf:TipoHuella><sf:Huella>${esc(r.hash)}</sf:Huella></sf:RegistroAnulacion></sfLR:RegistroFactura>`}
function envelope(r){return `<?xml version="1.0" encoding="UTF-8"?><soapenv:Envelope xmlns:soapenv="http://schemas.xmlsoap.org/soap/envelope/" xmlns:sfLR="https://www2.agenciatributaria.gob.es/static_files/common/internet/dep/aplicaciones/es/aeat/tike/cont/ws/SuministroLR.xsd" xmlns:sf="https://www2.agenciatributaria.gob.es/static_files/common/internet/dep/aplicaciones/es/aeat/tike/cont/ws/SuministroInformacion.xsd"><soapenv:Header/><soapenv:Body><sfLR:RegFactuSistemaFacturacion>${header(r)}${r.kind==='anulacion'?anulXml(r):altaXml(r)}</sfLR:RegFactuSistemaFacturacion></soapenv:Body></soapenv:Envelope>`}
function extract(xml,tag){const m=String(xml).match(new RegExp(`<[^>]*${tag}[^>]*>([\\s\\S]*?)<\\/[^>]*${tag}>`,'i'));return m?m[1].replace(/<[^>]+>/g,'').trim():''}
function postXml(url,xml,pfx,passphrase){return new Promise((resolve,reject)=>{const u=new URL(url),req=https.request({protocol:u.protocol,hostname:u.hostname,path:u.pathname+u.search,method:'POST',pfx,passphrase,rejectUnauthorized:true,headers:{'Content-Type':'text/xml; charset=utf-8','Content-Length':Buffer.byteLength(xml),'SOAPAction':'""'}},res=>{let body='';res.setEncoding('utf8');res.on('data',d=>body+=d);res.on('end',()=>resolve({statusCode:res.statusCode||0,body}))});req.on('error',reject);req.setTimeout(30000,()=>req.destroy(new Error('TIMEOUT AEAT')));req.write(xml);req.end()})}

export const submitVerifactu=onCall({region:'europe-west1',secrets:[PFX,PFX_PASSWORD],timeoutSeconds:60,memory:'256MiB'},async req=>{if(!req.auth)throw new HttpsError('unauthenticated','LOGIN REQUERIDO');const r=await role(req.auth.uid);if(!allowed(r))throw new HttpsError('permission-denied','ROL SIN PERMISO');const id=String(req.data?.recordId||'');if(!id)throw new HttpsError('invalid-argument','recordId requerido');const ref=db.doc(`${ROOT}/fiscalRecords/${id}`),snap=await ref.get();if(!snap.exists)throw new HttpsError('not-found','Registro fiscal no encontrado');const record=snap.data();if(!['prepared','pending_submission','retry'].includes(record.status))return{ok:true,alreadyProcessed:true,status:record.status};const settings=(await db.doc(`${ROOT}/settings/main`).get()).data()||{},environment=settings.verifactuEnvironment||'test';if(environment==='production'&&!settings.verifactuProductionConfirmed)throw new HttpsError('failed-precondition','Producción no confirmada');const pfxText=PFX.value();if(!pfxText)throw new HttpsError('failed-precondition','Certificado no configurado');const xml=envelope(record),resp=await postXml(environment==='production'?PROD:TEST,xml,Buffer.from(pfxText,'base64'),PFX_PASSWORD.value()),estado=extract(resp.body,'EstadoRegistro')||extract(resp.body,'EstadoEnvio')||'',code=extract(resp.body,'CodigoErrorRegistro')||'',desc=extract(resp.body,'DescripcionErrorRegistro')||'',accepted=/Correcto|Aceptado/i.test(estado)&&!/Rechazado/i.test(estado),status=accepted?'accepted':(/Aceptado/i.test(estado)?'accepted_with_errors':'rejected');await ref.update({status,aeatStatus:estado,aeatCode:code,aeatDescription:desc,aeatHttpStatus:resp.statusCode,submittedAt:FieldValue.serverTimestamp(),updatedAt:FieldValue.serverTimestamp()});if(record.invoiceId)await db.doc(`${ROOT}/invoices/${record.invoiceId}`).set({verifactuStatus:status,verifactuAeatStatus:estado,verifactuAeatCode:code,verifactuAeatDescription:desc,verifactuSubmittedAt:FieldValue.serverTimestamp()},{merge:true});return{ok:accepted,status,estado,code,description:desc,httpStatus:resp.statusCode}});

export const verifactuBackendStatus=onCall({region:'europe-west1',secrets:[PFX,PFX_PASSWORD]},async req=>{if(!req.auth)throw new HttpsError('unauthenticated','LOGIN REQUERIDO');const r=await role(req.auth.uid);if(!allowed(r))throw new HttpsError('permission-denied','ROL SIN PERMISO');return{backendReady:true,certificateReady:Boolean(PFX.value()),project:'aw999-71828',region:'europe-west1'}});


export const retryPendingVerifactu=onSchedule({region:'europe-west1',schedule:'every 60 minutes',timeZone:'Europe/Madrid',secrets:[PFX,PFX_PASSWORD],timeoutSeconds:300,memory:'256MiB'},async()=>{
  const settings=(await db.doc(`${ROOT}/settings/main`).get()).data()||{};
  if(!settings.verifactuEnabled||!settings.verifactuBackendReady)return;
  const pfxText=PFX.value();if(!pfxText)return;
  const snap=await db.collection(`${ROOT}/fiscalRecords`).where('status','in',['prepared','pending_submission','retry']).limit(100).get();
  const docs=[...snap.docs].sort((a,b)=>String(a.data().createdAt||a.data().generatedAt||'').localeCompare(String(b.data().createdAt||b.data().generatedAt||'')));
  let waitSeconds=0;
  for(const d of docs){
    if(waitSeconds>0)await new Promise(resolve=>setTimeout(resolve,Math.min(waitSeconds,60)*1000));
    const ref=d.ref,record=d.data(),environment=settings.verifactuEnvironment||'test';
    try{
      if(environment==='production'&&!settings.verifactuProductionConfirmed)throw new Error('Producción no confirmada');
      const xml=envelope(record),resp=await postXml(environment==='production'?PROD:TEST,xml,Buffer.from(pfxText,'base64'),PFX_PASSWORD.value());
      const estado=extract(resp.body,'EstadoRegistro')||extract(resp.body,'EstadoEnvio')||'',code=extract(resp.body,'CodigoErrorRegistro')||'',desc=extract(resp.body,'DescripcionErrorRegistro')||'',wait=Number(extract(resp.body,'TiempoEsperaEnvio')||0);
      const accepted=/Correcto|Aceptado/i.test(estado)&&!/Rechazado/i.test(estado),status=accepted?'accepted':(/Aceptado/i.test(estado)?'accepted_with_errors':'rejected');
      await ref.update({status,aeatStatus:estado,aeatCode:code,aeatDescription:desc,aeatHttpStatus:resp.statusCode,aeatWaitSeconds:wait,submittedAt:FieldValue.serverTimestamp(),updatedAt:FieldValue.serverTimestamp()});
      if(record.invoiceId)await db.doc(`${ROOT}/invoices/${record.invoiceId}`).set({verifactuStatus:status,verifactuAeatStatus:estado,verifactuAeatCode:code,verifactuAeatDescription:desc,verifactuSubmittedAt:FieldValue.serverTimestamp()},{merge:true});
      waitSeconds=wait;
    }catch(error){
      await ref.set({status:'retry',lastError:String(error?.message||error).slice(0,1000),lastRetryAt:FieldValue.serverTimestamp(),updatedAt:FieldValue.serverTimestamp()},{merge:true});
      waitSeconds=0;
    }
  }
});
