from pathlib import Path
import re

ROOT=Path('.')

def read(path): return (ROOT/path).read_text()
def write(path,text): (ROOT/path).write_text(text)
def rep(path,old,new,count=1):
    text=read(path)
    if old not in text: raise SystemExit(f'PATRON NO ENCONTRADO {path}: {old[:100]!r}')
    text=text.replace(old,new,count)
    write(path,text)
def sub(path,pattern,repl,count=1,flags=re.S):
    text=read(path)
    out,n=re.subn(pattern,repl,text,count=count,flags=flags)
    if n!=count: raise SystemExit(f'REGEX {path}: esperado {count}, obtenido {n}: {pattern[:100]}')
    write(path,out)

# ---------------- app.js: capabilities / guards ----------------
rep('js/app.js',"import {financialView,exportFinancial,zeroStockFully} from './views-finance.js';", "import {financialView,exportFinancial,zeroStockFully} from './views-finance.js';\nimport {can,canAction} from './permissions.js';")
rep('js/app.js','Runtime.render=render;','Runtime.render=render;\nfunction requireCap(cap){if(can(Runtime.role,cap))return true;toast(\'TU ROL NO TIENE PERMISO PARA ESTA ACCIÓN\',\'bad\');return false;}')
rep('js/app.js','bindDynamic();if(focusId)',"bindDynamic();const quickInvoice=document.querySelector('[data-go=\"invoice-new\"]');if(quickInvoice)quickInvoice.hidden=!can(Runtime.role,'invoiceWrite');if(focusId)")
rep('js/app.js',"if(a?.dataset.go==='invoice-new')invoiceModal()", "if(a?.dataset.go==='invoice-new'){if(!requireCap('invoiceWrite'))return;invoiceModal()}")
rep('js/app.js',"content.querySelectorAll('[data-order-edit]').forEach(b=>b.onclick=()=>orderModal(stFind('orders',b.dataset.orderEdit)))", "content.querySelectorAll('[data-order-edit]').forEach(b=>b.onclick=()=>requireCap('orderWrite')&&orderModal(stFind('orders',b.dataset.orderEdit)))")
rep('js/app.js',"content.querySelectorAll('[data-order-invoice]').forEach(b=>b.onclick=()=>invoiceFromOrder(stFind('orders',b.dataset.orderInvoice)))", "content.querySelectorAll('[data-order-invoice]').forEach(b=>b.onclick=()=>requireCap('invoiceWrite')&&invoiceFromOrder(stFind('orders',b.dataset.orderInvoice)))")
rep('js/app.js',"content.querySelectorAll('[data-inv-rect]').forEach(b=>b.onclick=()=>rectificationModal(selectedInvoice(b.dataset.invRect)))", "content.querySelectorAll('[data-inv-rect]').forEach(b=>b.onclick=()=>requireCap('invoiceWrite')&&rectificationModal(selectedInvoice(b.dataset.invRect)))")
rep('js/app.js',"content.querySelectorAll('[data-inv-void]').forEach(b=>b.onclick=()=>handleVoid(selectedInvoice(b.dataset.invVoid)))", "content.querySelectorAll('[data-inv-void]').forEach(b=>b.onclick=()=>requireCap('invoiceWrite')&&handleVoid(selectedInvoice(b.dataset.invVoid)))")
rep('js/app.js',"content.querySelectorAll('[data-product-edit]').forEach(b=>b.onclick=()=>productModal(Runtime.product(b.dataset.productEdit)))", "content.querySelectorAll('[data-product-edit]').forEach(b=>b.onclick=()=>requireCap('productWrite')&&productModal(Runtime.product(b.dataset.productEdit)))")
rep('js/app.js',"content.querySelectorAll('[data-client-edit]').forEach(b=>b.onclick=()=>clientModal(Runtime.client(b.dataset.clientEdit)))", "content.querySelectorAll('[data-client-edit]').forEach(b=>b.onclick=()=>requireCap('clientWrite')&&clientModal(Runtime.client(b.dataset.clientEdit)))")
rep('js/app.js',"content.querySelectorAll('[data-supplier-edit]').forEach(b=>b.onclick=()=>supplierModal(Runtime.supplier(b.dataset.supplierEdit)))", "content.querySelectorAll('[data-supplier-edit]').forEach(b=>b.onclick=()=>requireCap('supplierWrite')&&supplierModal(Runtime.supplier(b.dataset.supplierEdit)))")
rep('js/app.js',"content.querySelectorAll('[data-mass-product]').forEach(b=>b.onclick=()=>massPriceModal(b.dataset.massProduct))", "content.querySelectorAll('[data-mass-product]').forEach(b=>b.onclick=()=>requireCap('priceWrite')&&massPriceModal(b.dataset.massProduct))")
rep('js/app.js',"content.querySelectorAll('[data-doc-invoice]').forEach(b=>b.onclick=()=>{const[kind,id]=b.dataset.docInvoice.split(':');convertDocument(kind,id)})", "content.querySelectorAll('[data-doc-invoice]').forEach(b=>b.onclick=()=>{if(!requireCap('invoiceWrite'))return;const[kind,id]=b.dataset.docInvoice.split(':');convertDocument(kind,id)})")
rep('js/app.js',"content.querySelectorAll('[data-member-edit]').forEach(b=>b.onclick=()=>memberModal(stFind('members',b.dataset.memberEdit)))", "content.querySelectorAll('[data-member-edit]').forEach(b=>b.onclick=()=>requireCap('memberAdmin')&&memberModal(stFind('members',b.dataset.memberEdit)))")
rep('js/app.js',"content.querySelectorAll('[data-mark-sent]').forEach(b=>b.onclick=async()=>{const i=selectedInvoice(b.dataset.markSent);", "content.querySelectorAll('[data-mark-sent]').forEach(b=>b.onclick=async()=>{if(!requireCap('invoiceWrite'))return;const i=selectedInvoice(b.dataset.markSent);")
rep('js/app.js','async function action(name){switch(name){',"async function action(name){if(!canAction(Runtime.role,name))return toast('TU ROL NO TIENE PERMISO PARA ESTA ACCIÓN','bad');switch(name){")

# ---------------- firebase.js: role alignment + snapshots + atomic ops ----------------
rep('js/firebase.js',"warehouse:['products','suppliers','purchases','orders','routes','transfers','wastes','returns','inventoryCounts','containers','notifications','stockMoves','settings','priceHistory']", "warehouse:['products','suppliers','purchases','orders','routes','transfers','wastes','returns','inventoryCounts','containers','notifications','stockMoves','settings','priceHistory']")

emit_fn="""export async function emitInvoice(invoice,user){
  if(!navigator.onLine)throw new Error('PARA EMITIR UNA FACTURA DEBES TENER CONEXIÓN A INTERNET');
  const checked=validateInvoice(invoice);if(checked.errors.length)throw new Error(checked.errors.join(' · '));
  const invoiceId=invoice.id||uid('inv'),sid=invoice.seriesId||'FA';
  return runTransaction(db,async tx=>{
    await assertMonthOpenTx(tx,invoice.date);
    const iref=ref('invoices',invoiceId),existing=await tx.get(iref),sref=ref('series',sid),ss=await tx.get(sref);
    if(existing.exists()&&existing.data().status!=='draft')throw new Error('ESTA FACTURA YA FUE EMITIDA');
    const unique=[...new Set((checked.invoice.lines||[]).map(l=>l.productId).filter(Boolean))],productSnaps=new Map();
    for(const pid of unique)productSnaps.set(pid,await tx.get(ref('products',pid)));
    const lines=(checked.invoice.lines||[]).map(l=>{const ps=productSnaps.get(l.productId),p=ps?.exists()?ps.data():null;return{...l,buyPriceSnapshot:Number(l.buyPriceSnapshot??p?.buyPrice??0)}});
    const calc=calcInvoice({...checked.invoice,lines}),s=ss.exists()?ss.data():{prefix:sid,next:1,digits:5},next=Number(s.next||1),number=`${s.prefix||sid}-${String(next).padStart(Number(s.digits||5),'0')}`,stamp=now();
    const emitted={...calc,id:invoiceId,number,status:'issued',issuedAt:stamp,createdAt:existing.exists()?existing.data().createdAt||stamp:stamp,updatedAt:stamp,issuerSnapshot:invoice.issuerSnapshot||invoice.settingsSnapshot||null,clientSnapshot:invoice.clientSnapshot||null};
    tx.set(iref,emitted,{merge:false});tx.set(sref,{...s,id:sid,next:next+1,updatedAt:stamp},{merge:true});
    for(const line of emitted.lines){const qty=stockMovementQty(line);if(qty<=0)continue;const mid=uid('sm');tx.set(ref('stockMoves',mid),{id:mid,productId:line.productId,qty:-qty,type:'sale',location:invoice.stockLocation||'ALMACEN',sourceId:invoiceId,note:`FACTURA ${number}`,date:invoice.date,createdAt:stamp})}
    for(const orderId of invoice.sourceOrderIds||[])tx.set(ref('orders',orderId),{status:'invoiced',invoiceId,updatedAt:stamp},{merge:true});
    const docMap={quote:'quotes',proforma:'proformas',delivery:'deliveryNotes'};if(invoice.sourceDocument?.kind&&invoice.sourceDocument?.id&&docMap[invoice.sourceDocument.kind])tx.set(ref(docMap[invoice.sourceDocument.kind],invoice.sourceDocument.id),{invoiceId,status:'invoiced',updatedAt:stamp},{merge:true});
    if(Number(emitted.paid||0)>0){const pid=uid('pay');tx.set(ref('payments',pid),{id:pid,clientId:invoice.clientId,date:invoice.date,amount:Number(emitted.paid),method:invoice.paymentMethod||'efectivo',allocations:[{invoiceId,amount:Number(emitted.paid)}],createdAt:stamp})}
    const aid=uid('a');tx.set(ref('audit',aid),{id:aid,action:'INVOICE_ISSUE',entity:'invoices',entityId:invoiceId,number,userEmail:user?.email||'',userUid:user?.uid||'',at:stamp});return emitted;
  });
}
"""
sub('js/firebase.js',r'export async function emitInvoice\(invoice,user\)\{.*?\nexport async function recordPayment',emit_fn+'export async function recordPayment')

atomic_ops="""
export async function saveStockOperation(collectionName,record,moves=[],action='STOCK_OPERATION',user=null){
  const id=record.id||uid(collectionName.slice(0,3)),stamp=now(),batch=writeBatch(db);
  batch.set(ref(collectionName,id),{...record,id,updatedAt:stamp},{merge:false});
  for(const raw of moves){const mid=raw.id||uid('sm');batch.set(ref('stockMoves',mid),{...raw,id:mid,sourceId:raw.sourceId||id,createdAt:raw.createdAt||stamp},{merge:false})}
  if(user){const aid=uid('a');batch.set(ref('audit',aid),{id:aid,action,entity:collectionName,entityId:id,userEmail:user.email||'',userUid:user.uid||'',at:stamp})}
  await batch.commit();return id;
}
export async function reopenMonthClosure(month,user){if(!isOwner(user))throw new Error('SOLO EL PROPIETARIO PUEDE REABRIR UN MES');const id=`close_${month}`,snap=await getDoc(ref('closures',id));if(!snap.exists())throw new Error('EL MES NO ESTÁ CERRADO');const batch=writeBatch(db);batch.delete(ref('closures',id));const aid=uid('a');batch.set(ref('audit',aid),{id:aid,action:'MONTH_REOPEN',entity:'closures',entityId:id,userEmail:user.email||'',userUid:user.uid||'',at:now()});await batch.commit();}
"""
rep('js/firebase.js','export async function zeroAllStockCloud',atomic_ops+'\nexport async function zeroAllStockCloud')

# ---------------- enhancements: role-aware actions + better negative visibility + box validation ----------------
rep('js/enhancements.js',"import {operationalResetAt,operationalWeekStart,invoiceAfterReset,orderAfterReset,paymentAfterReset,resetLabel} from './period.js';", "import {operationalResetAt,operationalWeekStart,invoiceAfterReset,orderAfterReset,paymentAfterReset,resetLabel} from './period.js';\nimport {can} from './permissions.js';")

dashboard="""export function enhancedDashboardView(){
  const issued=st().invoices.filter(i=>invoiceAfterReset(i)&&!['draft','void'].includes(i.status)).map(calcInvoice),billed=round2(issued.reduce((s,i)=>s+i.total,0)),pending=round2(issued.reduce((s,i)=>s+i.pending,0)),paid=round2(st().payments.filter(paymentAfterReset).reduce((s,p)=>s+Number(p.amount||0),0)),delivered=st().orders.filter(o=>orderAfterReset(o)&&o.status==='delivered'&&!o.invoiceId).length;
  const badBoxes=products().filter(p=>p.mode==='caja_kg'&&!Number(p.kgPerBox)),zeroPrices=products().filter(p=>Number(p.sellPrice||0)<=0).length,alerts=[];if(delivered)alerts.push(`${delivered} ENTREGAS SIN FACTURAR`);if(badBoxes.length)alerts.push(`${badBoxes.length} PRODUCTOS CAJA × KG SIN PESO`);if(zeroPrices)alerts.push(`${zeroPrices} PRODUCTOS SIN PRECIO DE VENTA`);
  const actions=[can(Runtime.role,'invoiceWrite')?'<button class="btn primary" data-action="invoice-new">＋ FACTURA</button>':'',can(Runtime.role,'orderWrite')?'<button class="btn" data-action="paste-order">PEGAR PEDIDO</button>':'',can(Runtime.role,'invoiceWrite')?'<button class="btn" data-action="invoice-all-delivered">⚡ FACTURAR TODA LA RUTA</button>':'',can(Runtime.role,'weekReset')?'<button class="btn" data-action="week-reset">↻ PONER CONTADORES A 0</button>':''].join('');
  return `${section('CENTRO DE CONTROL',`PERIODO OPERATIVO DESDE ${resetLabel()} · PEDIDO → REPARTO REAL → FACTURA → COBRO`,actions)}<div class="kpis">${kpi('FACTURADO PERIODO',money(billed))}${kpi('COBRADO PERIODO',money(paid))}${kpi('DEUDA PERIODO',money(pending))}${kpi('ENTREGAS SIN FACTURA',String(delivered))}</div><div class="grid2"><div class="panel"><h3>REQUIERE ATENCIÓN</h3>${alerts.length?alerts.map(a=>`<div class="warning">⚠ ${esc(a)}</div>`).join(''):'<div class="success">TODO EN ORDEN</div>'}</div><div class="panel week-panel"><h3>PERIODO OPERATIVO</h3><p>CORTE: <b>${esc(resetLabel())}</b></p><p>FACTURAS NUEVAS: <b>${issued.length}</b></p><p>COBROS NUEVOS: <b>${st().payments.filter(paymentAfterReset).length}</b></p><p>EL RESET NO BORRA HISTÓRICO NI REINICIA NUMERACIÓN.</p>${can(Runtime.role,'invoiceRead')?'<button class="btn" data-action="invoice-history-toggle">VER HISTÓRICO</button>':''}</div></div>`;
}
"""
sub('js/enhancements.js',r'export function enhancedDashboardView\(\)\{.*?\n\}\n\nexport function enhancedOrdersView',dashboard+'\nexport function enhancedOrdersView')

orders="""export function enhancedOrdersView(){
  const all=[...st().orders].sort((a,b)=>String(b.date).localeCompare(String(a.date))),list=window.ARW_ORDER_HISTORY?all:all.filter(orderAfterReset),actions=[can(Runtime.role,'orderWrite')?'<button class="btn primary" data-action="order-new">＋ PEDIDO</button><button class="btn" data-action="paste-order">PEGAR PEDIDO</button><button class="btn" data-action="paste-multi-orders">PEGAR VARIOS CLIENTES</button><button class="btn good" data-action="quick-delivery">MODO REPARTO RÁPIDO</button>':'',can(Runtime.role,'invoiceWrite')?'<button class="btn primary" data-action="invoice-all-delivered">FACTURAR TODA LA RUTA</button>':'',can(Runtime.role,'orderWrite')?`<button class="btn" data-action="order-history-toggle">${window.ARW_ORDER_HISTORY?'SOLO PERIODO':'VER HISTÓRICO'}</button>`:''].join('');
  return `${section('PEDIDOS Y REPARTO',window.ARW_ORDER_HISTORY?'MOSTRANDO HISTÓRICO COMPLETO':`PERIODO DESDE ${resetLabel()}`,actions)}${table(['FECHA','CLIENTE','ESTADO','PRODUCTOS','PEDIDO','ENTREGADO','FACTURA','ACCIONES'],list.map(o=>{const c=client(o.clientId)||o.clientSnapshot||{},rq=(o.lines||[]).reduce((s,l)=>s+Number(l.requestedQty||0),0),dl=(o.lines||[]).reduce((s,l)=>s+Number(l.deliveredQty||0),0);return `<tr><td>${esc(o.date)}</td><td><b>${esc(c.name||'')}</b></td><td>${badge(o.status,o.status==='delivered'?'good':'')}</td><td>${o.lines?.length||0}</td><td>${rq}</td><td>${dl}</td><td>${o.invoiceId?badge('FACTURADO','good'):'—'}</td><td>${can(Runtime.role,'orderWrite')?`<button class="btn mini" data-order-edit="${o.id}">ABRIR</button>`:'—'}${!o.invoiceId&&can(Runtime.role,'invoiceWrite')?` <button class="btn mini good" data-order-invoice="${o.id}">FACTURAR ENTREGADO</button>`:''}</td></tr>`}))}`;
}
"""
sub('js/enhancements.js',r'export function enhancedOrdersView\(\)\{.*?\n\}\n\nexport function enhancedInvoicesView',orders+'\nexport function enhancedInvoicesView')

# Hide owner-only reset in invoice and stock views
rep('js/enhancements.js','<button class="btn" data-action="week-reset">↻ PONER CONTADORES A 0</button>',"${can(Runtime.role,'weekReset')?'<button class=\"btn\" data-action=\"week-reset\">↻ PONER CONTADORES A 0</button>':''}")
rep('js/enhancements.js','<button class="btn" data-action="stock-zero-all">PONER TODO A 0</button>',"${can(Runtime.role,'stockReset')?'<button class=\"btn\" data-action=\"stock-zero-all\">PONER TODO A 0</button>':''}")
# Stock card/negative count must inspect locations, not only product total
rep('js/enhancements.js',"negative=list.filter(x=>x.qty<0).length;", "negative=list.filter(({p})=>locations.some(l=>stockQuantity(st().stockMoves,p.id,l)<-.0001)).length;")
rep('js/enhancements.js',"status=qty<0?'stock-bad':qty===0?'stock-zero':'stock-ok'", "hasNeg=locations.some(l=>stockQuantity(st().stockMoves,p.id,l)<-.0001),status=hasNeg?'stock-bad':qty===0?'stock-zero':'stock-ok'")
# Direct typing in quick delivery must validate boxes
rep('js/enhancements.js',"const lines=(o.lines||[]).map((l,i)=>({...l,deliveredQty:Number(sec.querySelector(`[data-qdel=\"${i}\"]`).value||0)}));await saveEntity('orders'", "const lines=(o.lines||[]).map((l,i)=>({...l,deliveredQty:Number(sec.querySelector(`[data-qdel=\"${i}\"]`).value||0)}));for(const l of lines){const p=product(l.productId);if(p?.mode?.startsWith('caja')&&!Number.isInteger(Number(l.deliveredQty||0)))return toast(`${p.name}: LAS CAJAS DEBEN SER ENTERAS`,'bad')}await saveEntity('orders'")

# ---------------- views-sales: guards, locked controls, transport on rectification, net debt ----------------
rep('js/views-sales.js',"import {invoiceAfterReset,paymentAfterReset,resetLabel} from './period.js';", "import {invoiceAfterReset,paymentAfterReset,resetLabel} from './period.js';\nimport {can} from './permissions.js';\nimport {clientNetDebt} from './health.js';")
rep('js/views-sales.js',"if(locked){m.querySelector('#pdfClient').onclick", "if(locked){m.querySelectorAll('#invoiceRows input,#invoiceRows select,#invoiceRows button').forEach(el=>el.disabled=true);m.querySelector('#pdfClient').onclick")
# Rectification quantity should credit transport consistently
old="const r=await createRectification(inv,lines,m.querySelector('#rReason').value,Runtime.user,'credit',{returnStock:m.querySelector('#rStock').checked,discount:Number(inv.discount||0)});"
new="const rectMerch=calcInvoice({...inv,type:'invoice',transportType:'fixed',transportValue:0,lines}).netMerchandise,origMerch=Math.max(.000001,Number(x.netMerchandise||0)),transportType=inv.transportType==='percent'?'percent':'fixed',transportValue=transportType==='percent'?Number(inv.transportValue||0):round2(Number(x.transport||0)*(rectMerch/origMerch));const r=await createRectification(inv,lines,m.querySelector('#rReason').value,Runtime.user,'credit',{returnStock:m.querySelector('#rStock').checked,discount:Number(inv.discount||0),transportType,transportValue});"
rep('js/views-sales.js',old,new)
# Debtor count aggregate net by client
rep('js/views-sales.js',"String(new Set(invoices.filter(i=>calcInvoice(i).pending>0).map(i=>i.clientId)).size)", "String(new Set(invoices.map(i=>i.clientId).filter(cid=>clientNetDebt(invoices,cid)>.01)).size)")
# Payment modal net cap
rep('js/views-sales.js',"const cid=m.querySelector('#payClient').value,invs=st().invoices.filter(i=>i.clientId===cid&&!['draft','void'].includes(i.status)&&calcInvoice(i).pending>0).sort", "const cid=m.querySelector('#payClient').value,allClient=st().invoices.filter(i=>i.clientId===cid&&!['draft','void'].includes(i.status)),netDebt=clientNetDebt(allClient,cid),invs=allClient.filter(i=>calcInvoice(i).pending>0).sort")
rep('js/views-sales.js',"m.querySelector('#payInvoices').innerHTML=`<div class=\"form-grid three\">", "if(netDebt<=.01){m.querySelector('#payInvoices').innerHTML='<div class=\"success\">EL CLIENTE NO TIENE DEUDA NETA PENDIENTE.</div>';return}m.querySelector('#payInvoices').innerHTML=`<div class=\"success\"><b>DEUDA NETA: ${money(netDebt)}</b> · LOS ABONOS/RECTIFICATIVAS YA ESTÁN DESCONTADOS.</div><div class=\"form-grid three\">")
rep('js/views-sales.js',"if(amount<=0)throw new Error('INDICA EL IMPORTE RECIBIDO');", "if(amount<=0)throw new Error('INDICA EL IMPORTE RECIBIDO');if(amount>netDebt+.01)throw new Error(`EL COBRO ${money(amount)} SUPERA LA DEUDA NETA ${money(netDebt)}`);")

# ---------------- views-master: role-aware editing and box UX ----------------
rep('js/views-master.js',"import {invoiceAfterReset, resetLabel} from './period.js';", "import {invoiceAfterReset, resetLabel} from './period.js';\nimport {can} from './permissions.js';")
rep('js/views-master.js','  const list = products();\n  const dupeNames',"  const list = products();\n  const editable = can(Runtime.role,'productWrite');\n  const dupeNames")
rep('js/views-master.js','<button class="btn mini" data-product-edit="${p.id}">EDITAR</button>\n        <button class="btn mini" data-product-360="${p.id}">360º</button>',"${editable?`<button class=\"btn mini\" data-product-edit=\"${p.id}\">EDITAR</button>`:''}\n        <button class=\"btn mini\" data-product-360=\"${p.id}\">360º</button>")
rep('js/views-master.js',"'<button class=\"btn primary\" data-action=\"product-new\">＋ PRODUCTO</button><button class=\"btn\" data-action=\"products-export\">EXPORTAR EXCEL</button>'", "`${editable?'<button class=\"btn primary\" data-action=\"product-new\">＋ PRODUCTO</button>':''}<button class=\"btn\" data-action=\"products-export\">EXPORTAR EXCEL</button>`")
rep('js/views-master.js','export function productModal(existing = null) {',"export function productModal(existing = null) {\n  if(!can(Runtime.role,'productWrite'))return toast('TU ROL SOLO PUEDE CONSULTAR PRODUCTOS','bad');")
rep('js/views-master.js','  const list = clients();\n\n  const rows',"  const list = clients();\n  const editable = can(Runtime.role,'clientWrite');\n\n  const rows")
rep('js/views-master.js','<button class="btn mini" data-client-edit="${c.id}">EDITAR</button>\n        <button class="btn mini primary" data-client-360="${c.id}">360º</button>',"${editable?`<button class=\"btn mini\" data-client-edit=\"${c.id}\">EDITAR</button>`:''}\n        <button class=\"btn mini primary\" data-client-360=\"${c.id}\">360º</button>")
rep('js/views-master.js',"'<button class=\"btn primary\" data-action=\"client-new\">＋ CLIENTE</button><button class=\"btn\" data-action=\"clients-export\">EXPORTAR EXCEL</button>'", "`${editable?'<button class=\"btn primary\" data-action=\"client-new\">＋ CLIENTE</button>':''}<button class=\"btn\" data-action=\"clients-export\">EXPORTAR EXCEL</button>`")
rep('js/views-master.js','export function clientModal(existing = null) {',"export function clientModal(existing = null) {\n  if(!can(Runtime.role,'clientWrite'))return toast('TU ROL SOLO PUEDE CONSULTAR CLIENTES','bad');")
rep('js/views-master.js','export function client360(c) {',"export function client360(c) {\n  const canEditClient=can(Runtime.role,'clientWrite');")
rep('js/views-master.js','<button class="btn primary" id="newSpecial">＋ PRECIO ESPECIAL</button>',"${canEditClient?'<button class=\"btn primary\" id=\"newSpecial\">＋ PRECIO ESPECIAL</button>':''}")
rep('js/views-master.js','<td><button class="btn mini" data-price-edit="${pid}">EDITAR</button></td>',"<td>${canEditClient?`<button class=\"btn mini\" data-price-edit=\"${pid}\">EDITAR</button>`:'—'}</td>")
rep('js/views-master.js',"  m.querySelector('#newSpecial').onclick = () => specialPriceModal(c);", "  if(m.querySelector('#newSpecial'))m.querySelector('#newSpecial').onclick = () => specialPriceModal(c);")
rep('js/views-master.js','function specialPriceModal(c, pid = \'\') {',"function specialPriceModal(c, pid = '') {\n  if(!can(Runtime.role,'clientWrite'))return toast('TU ROL NO PUEDE CAMBIAR TARIFAS','bad');")
rep('js/views-master.js','export function stockAdjustModal() {',"export function stockAdjustModal() {\n  if(!can(Runtime.role,'stockAdjust'))return toast('SIN PERMISO PARA AJUSTAR STOCK','bad');")
rep('js/views-master.js','export function supplierModal(existing = null) {',"export function supplierModal(existing = null) {\n  if(!can(Runtime.role,'supplierWrite'))return toast('SIN PERMISO PARA EDITAR PROVEEDORES','bad');")
rep('js/views-master.js','export function purchaseModal(preset = null) {',"export function purchaseModal(preset = null) {\n  if(!can(Runtime.role,'purchaseWrite'))return toast('SIN PERMISO PARA REGISTRAR COMPRAS','bad');")
rep('js/views-master.js','export function purchaseImportModal() {',"export function purchaseImportModal() {\n  if(!can(Runtime.role,'purchaseWrite'))return toast('SIN PERMISO PARA IMPORTAR COMPRAS','bad');")
rep('js/views-master.js','<td><input class="puQty" type="number" step=".01" value="${Number(l.qty || 0)}"></td>',"<td><input class=\"puQty\" type=\"number\" step=\"${String(l.mode||'').startsWith('caja')?'1':'.01'}\" value=\"${Number(l.qty || 0)}\"></td>")
rep('js/views-master.js',"tr.querySelector('.puKg').value = Number(p?.kgPerBox || 0);", "tr.querySelector('.puKg').value = Number(p?.kgPerBox || 0);\n      tr.querySelector('.puQty').step=p?.mode?.startsWith('caja')?'1':'.01';")

# ---------------- Rewrite views-ops.js cleanly: atomic stock, role gates, as-of close ----------------
views_ops=r'''import {Runtime} from './runtime.js';
import {section,table,kpi,badge,modal,closeModal,toast,optionList,money,esc} from './ui.js';
import {newLine,calcInvoice,stockQuantity,stockText,round2,today,now,uid,upper} from './domain.js';
import {saveEntity,saveStockOperation,reopenMonthClosure} from './firebase.js';
import {invoiceModal} from './views-sales.js';
import {costAtDate} from './finance.js';
import {can} from './permissions.js';
const st=()=>Runtime.state,product=id=>Runtime.product(id),client=id=>Runtime.client(id);
const products=()=>st().products.filter(p=>p.active!==false&&!p.archived).sort((a,b)=>String(a.name).localeCompare(String(b.name)));
const clients=()=>st().clients.filter(c=>c.active!==false&&!c.archived).sort((a,b)=>String(a.name).localeCompare(String(b.name)));
const productOpts=(sel='')=>`<option value="">SELECCIONAR</option>${optionList(products(),sel,p=>`${p.code} · ${p.name}`)}`;
const clientOpts=(sel='')=>`<option value="">SELECCIONAR</option>${optionList(clients(),sel)}`;
const LOCATIONS=['ALMACEN','FURGONETA','SAN PABLO','SAN LESMES','SANTIAGO'];
function qtyToStock(p,qty){return p?.mode==='caja_kg'?round2(Number(qty||0)*Number(p.kgPerBox||0)):Number(qty||0)}
function requireStockOps(){if(can(Runtime.role,'stockOps'))return true;toast('SIN PERMISO PARA OPERACIONES DE STOCK','bad');return false}

export function warehouseOpsView(){const actions=can(Runtime.role,'stockOps')?`<button class="btn" data-action="transfer-new">TRASPASO</button><button class="btn bad" data-action="waste-new">MERMA</button><button class="btn" data-action="return-new">DEVOLUCIÓN</button><button class="btn primary" data-action="inventory-new">INVENTARIO</button>`:'';return `${section('OPERACIONES DE STOCK','TRASPASOS · MERMAS · DEVOLUCIONES · INVENTARIO FÍSICO',actions)}<div class="grid2"><div><h3>ÚLTIMOS TRASPASOS</h3>${table(['FECHA','PRODUCTO','ORIGEN','DESTINO','CANTIDAD'],st().transfers.slice(0,50).map(t=>`<tr><td>${t.date}</td><td>${esc(product(t.productId)?.name||'')}</td><td>${esc(t.from)}</td><td>${esc(t.to)}</td><td>${t.qty}</td></tr>`))}</div><div><h3>MERMAS / DEVOLUCIONES</h3>${table(['FECHA','TIPO','PRODUCTO','CANTIDAD','MOTIVO'],[...st().wastes.map(x=>({...x,kind:'MERMA'})),...st().returns.map(x=>({...x,kind:'DEVOLUCIÓN'}))].sort((a,b)=>String(b.date).localeCompare(String(a.date))).slice(0,50).map(x=>`<tr><td>${x.date}</td><td>${badge(x.kind,x.kind==='MERMA'?'bad':'good')}</td><td>${esc(product(x.productId)?.name||'')}</td><td>${x.qty}</td><td>${esc(x.reason||'')}</td></tr>`))}</div></div>`}

export function transferModal(){if(!requireStockOps())return;const m=modal('TRASPASO DE STOCK',`<form id="tf"><div class="form-grid"><label>PRODUCTO<select name="pid">${productOpts()}</select></label><label>CANTIDAD<input name="qty" type="number" step=".01"></label><label>ORIGEN<select name="from">${LOCATIONS.map(x=>`<option>${x}</option>`).join('')}</select></label><label>DESTINO<select name="to">${LOCATIONS.map(x=>`<option>${x}</option>`).join('')}</select></label></div><div class="muted">EN CAJA × KG, CANTIDAD SIGNIFICA CAJAS Y ARW2026 CONVIERTE A KG.</div><button class="btn primary">REGISTRAR</button></form>`,true);m.querySelector('[name=pid]').onchange=e=>m.querySelector('[name=qty]').step=product(e.target.value)?.mode?.startsWith('caja')?'1':'.01';m.querySelector('#tf').onsubmit=async e=>{e.preventDefault();try{const f=new FormData(e.currentTarget),p=product(f.get('pid')),input=Number(f.get('qty')||0),q=qtyToStock(p,input);if(!p||q<=0)throw new Error('REVISA PRODUCTO Y CANTIDAD');if(p.mode?.startsWith('caja')&&!Number.isInteger(input))throw new Error('LAS CAJAS DEBEN SER ENTERAS');if(f.get('from')===f.get('to'))throw new Error('ORIGEN Y DESTINO NO PUEDEN SER IGUALES');if(q>stockQuantity(st().stockMoves,p.id,f.get('from'))+.0001)throw new Error(`STOCK INSUFICIENTE EN ${f.get('from')}`);const id=uid('tr'),date=today();await saveStockOperation('transfers',{id,date,productId:p.id,qty:input,stockQty:q,from:f.get('from'),to:f.get('to')},[{productId:p.id,qty:-q,type:'transfer_out',location:f.get('from'),sourceId:id,date},{productId:p.id,qty:q,type:'transfer_in',location:f.get('to'),sourceId:id,date}],'TRANSFER',Runtime.user);toast('TRASPASO REGISTRADO ATÓMICAMENTE','good');closeModal()}catch(err){toast(err.message,'bad')}}}
export function wasteModal(){if(!requireStockOps())return;const m=modal('REGISTRAR MERMA',`<form id="wf"><div class="form-grid three"><label>PRODUCTO<select name="pid">${productOpts()}</select></label><label>CANTIDAD<input name="qty" type="number" step=".01"></label><label>UBICACIÓN<select name="location">${LOCATIONS.map(x=>`<option>${x}</option>`).join('')}</select></label></div><div class="muted">EN CAJA × KG, CANTIDAD SIGNIFICA CAJAS.</div><label class="field">MOTIVO<input name="reason" required></label><button class="btn bad">REGISTRAR MERMA</button></form>`,true);m.querySelector('[name=pid]').onchange=e=>m.querySelector('[name=qty]').step=product(e.target.value)?.mode?.startsWith('caja')?'1':'.01';m.querySelector('#wf').onsubmit=async e=>{e.preventDefault();try{const f=new FormData(e.currentTarget),p=product(f.get('pid')),input=Number(f.get('qty')||0),q=qtyToStock(p,input),id=uid('w');if(!p||q<=0)throw new Error('REVISA PRODUCTO Y CANTIDAD');if(p.mode?.startsWith('caja')&&!Number.isInteger(input))throw new Error('LAS CAJAS DEBEN SER ENTERAS');if(q>stockQuantity(st().stockMoves,p.id,f.get('location'))+.0001)throw new Error('LA MERMA SUPERA EL STOCK DE ESA UBICACIÓN');const date=today(),reason=upper(f.get('reason'));await saveStockOperation('wastes',{id,date,productId:p.id,qty:input,stockQty:q,location:f.get('location'),reason},[{productId:p.id,qty:-q,type:'waste',location:f.get('location'),sourceId:id,note:reason,date}],'WASTE',Runtime.user);toast('MERMA REGISTRADA ATÓMICAMENTE','good');closeModal()}catch(err){toast(err.message,'bad')}}}
export function returnModal(){if(!requireStockOps())return;const m=modal('DEVOLUCIÓN A STOCK',`<form id="retf"><div class="form-grid three"><label>PRODUCTO<select name="pid">${productOpts()}</select></label><label>CANTIDAD<input name="qty" type="number" step=".01"></label><label>UBICACIÓN<select name="location">${LOCATIONS.map(x=>`<option>${x}</option>`).join('')}</select></label></div><label class="field">MOTIVO<input name="reason" required></label><button class="btn primary">REGISTRAR DEVOLUCIÓN</button></form>`,true);m.querySelector('[name=pid]').onchange=e=>m.querySelector('[name=qty]').step=product(e.target.value)?.mode?.startsWith('caja')?'1':'.01';m.querySelector('#retf').onsubmit=async e=>{e.preventDefault();try{const f=new FormData(e.currentTarget),p=product(f.get('pid')),input=Number(f.get('qty')||0),q=qtyToStock(p,input),id=uid('ret');if(!p||q<=0)throw new Error('REVISA PRODUCTO Y CANTIDAD');if(p.mode?.startsWith('caja')&&!Number.isInteger(input))throw new Error('LAS CAJAS DEBEN SER ENTERAS');const date=today(),reason=upper(f.get('reason'));await saveStockOperation('returns',{id,date,productId:p.id,qty:input,stockQty:q,location:f.get('location'),reason},[{productId:p.id,qty:q,type:'return',location:f.get('location'),sourceId:id,note:reason,date}],'RETURN',Runtime.user);toast('DEVOLUCIÓN REGISTRADA ATÓMICAMENTE','good');closeModal()}catch(err){toast(err.message,'bad')}}}
export function inventoryModal(){if(!requireStockOps())return;const m=modal('INVENTARIO FÍSICO',`<div class="warning">INVENTARIO DE ALMACÉN. EN CAJA × KG INTRODUCE CAJAS.</div><div class="table-wrap"><table><thead><tr><th>PRODUCTO</th><th>SISTEMA</th><th>CONTADO</th><th>DIFERENCIA</th></tr></thead><tbody id="invCountRows">${products().map(p=>{const q=stockQuantity(st().stockMoves,p.id,'ALMACEN'),display=p.mode==='caja_kg'&&p.kgPerBox?round2(q/p.kgPerBox):q;return `<tr data-pid="${p.id}"><td>${esc(p.code)} · ${esc(p.name)}</td><td>${esc(stockText(p,q))}</td><td><input class="count" type="number" step="${p.mode?.startsWith('caja')?'1':'.01'}" value="${display}"></td><td class="diff">0</td></tr>`}).join('')}</tbody></table></div><button class="btn primary" id="saveInventory">AJUSTAR INVENTARIO</button>`);const refresh=()=>m.querySelectorAll('#invCountRows tr').forEach(tr=>{const p=product(tr.dataset.pid),sys=stockQuantity(st().stockMoves,p.id,'ALMACEN'),input=Number(tr.querySelector('.count').value||0),count=qtyToStock(p,input);tr.querySelector('.diff').textContent=round2(count-sys)});m.addEventListener('input',refresh);m.querySelector('#saveInventory').onclick=async()=>{try{if(!confirm('¿APLICAR LAS DIFERENCIAS DEL INVENTARIO AL STOCK?'))return;const id=uid('ic'),rows=[],moves=[],date=today();for(const tr of m.querySelectorAll('#invCountRows tr')){const p=product(tr.dataset.pid),input=Number(tr.querySelector('.count').value||0);if(p.mode?.startsWith('caja')&&!Number.isInteger(input))throw new Error(`${p.name}: LAS CAJAS DEBEN SER ENTERAS`);const sys=stockQuantity(st().stockMoves,p.id,'ALMACEN'),count=qtyToStock(p,input),diff=round2(count-sys);rows.push({productId:p.id,system:sys,count,diff});if(Math.abs(diff)>.0001)moves.push({productId:p.id,qty:diff,type:'inventory_adjust',location:'ALMACEN',sourceId:id,date})}await saveStockOperation('inventoryCounts',{id,date,location:'ALMACEN',rows},moves,'INVENTORY_COUNT',Runtime.user);toast('INVENTARIO AJUSTADO ATÓMICAMENTE','good');closeModal()}catch(err){toast(err.message,'bad')}};refresh()}

const docCollections={quote:'quotes',proforma:'proformas',delivery:'deliveryNotes'},docLabels={quote:'PRESUPUESTO',proforma:'PROFORMA',delivery:'ALBARÁN'};
function canDoc(kind){return kind==='delivery'?can(Runtime.role,'deliveryNoteWrite'):can(Runtime.role,'quoteWrite')}
export function documentsView(){const all=[...st().quotes.map(x=>({...x,kind:'quote'})),...st().proformas.map(x=>({...x,kind:'proforma'})),...st().deliveryNotes.map(x=>({...x,kind:'delivery'}))].sort((a,b)=>String(b.date).localeCompare(String(a.date))),actions=[can(Runtime.role,'quoteWrite')?'<button class="btn" data-action="doc-quote">＋ PRESUPUESTO</button><button class="btn" data-action="doc-proforma">＋ PROFORMA</button>':'',can(Runtime.role,'deliveryNoteWrite')?'<button class="btn primary" data-action="doc-delivery">＋ ALBARÁN</button>':''].join('');return `${section('DOCUMENTOS COMERCIALES','PRESUPUESTOS · PROFORMAS · ALBARANES → FACTURA',actions)}${table(['TIPO','FECHA','CLIENTE','LÍNEAS','TOTAL','ESTADO','ACCIONES'],all.map(d=>`<tr><td>${badge(docLabels[d.kind])}</td><td>${d.date}</td><td>${esc((client(d.clientId)||d.clientSnapshot||{}).name||'')}</td><td>${d.lines?.length||0}</td><td>${money(calcInvoice(d).total)}</td><td>${d.invoiceId?badge('FACTURADO','good'):badge('ABIERTO','warn')}</td><td>${d.invoiceId?'—':can(Runtime.role,'invoiceWrite')?`<button class="btn mini primary" data-doc-invoice="${d.kind}:${d.id}">CONVERTIR A FACTURA</button>`:'—'}</td></tr>`))}`}
function docLineRow(l={}){const p=product(l.productId),step=p?.mode?.startsWith('caja')?'1':'.01';return `<tr><td><select class="dProd">${productOpts(l.productId)}</select></td><td><input class="dQty" type="number" step="${step}" value="${Number(l.qty||0)}"></td><td><input class="dPrice" type="number" step=".01" value="${Number(l.price||0)}"></td><td><select class="dVat">${[0,4,10,21].map(v=>`<option value="${v}" ${Number(l.vat||4)===v?'selected':''}>${v}%</option>`).join('')}</select></td></tr>`}
export function documentModal(kind){if(!canDoc(kind))return toast('TU ROL NO PUEDE CREAR ESTE DOCUMENTO','bad');const label=docLabels[kind],m=modal(`NUEVO ${label}`,`<form id="df"><div class="form-grid three"><label>CLIENTE<select name="clientId">${clientOpts()}</select></label><label>FECHA<input name="date" type="date" value="${today()}"></label><label class="check"><input name="hidePrices" type="checkbox" ${kind==='delivery'?'checked':''}> SIN PRECIOS</label></div><div class="table-wrap"><table><thead><tr><th>PRODUCTO</th><th>CANTIDAD</th><th>PRECIO</th><th>IVA</th></tr></thead><tbody id="dRows">${Array.from({length:6},()=>docLineRow()).join('')}</tbody></table></div><button class="btn primary">GUARDAR ${label}</button></form>`);m.addEventListener('change',e=>{if(e.target.matches('.dProd')){const p=product(e.target.value),tr=e.target.closest('tr'),c=client(m.querySelector('[name=clientId]').value),l=newLine(p,c);tr.querySelector('.dPrice').value=l.price;tr.querySelector('.dVat').value=l.vat;tr.querySelector('.dQty').step=p?.mode?.startsWith('caja')?'1':'.01'}});m.querySelector('#df').onsubmit=async e=>{e.preventDefault();try{const f=new FormData(e.currentTarget),cid=f.get('clientId'),c=client(cid),lines=[...m.querySelectorAll('#dRows tr')].map(tr=>{const pid=tr.querySelector('.dProd').value;if(!pid)return null;const p=product(pid),qty=Number(tr.querySelector('.dQty').value||0);if(p?.mode?.startsWith('caja')&&!Number.isInteger(qty))throw new Error(`${p.name}: LAS CAJAS DEBEN SER ENTERAS`);return newLine(p,c,{qty,price:Number(tr.querySelector('.dPrice').value||0),vat:Number(tr.querySelector('.dVat').value||0)})}).filter(l=>l&&l.qty>0);if(!cid||!lines.length)throw new Error('CLIENTE Y PRODUCTOS OBLIGATORIOS');const id=uid('doc');await saveEntity(docCollections[kind],{id,clientId:cid,clientSnapshot:c?{name:c.name,nif:c.nif,address:c.address}:null,date:f.get('date'),hidePrices:!!f.get('hidePrices'),transportType:'fixed',transportValue:0,discount:0,lines},`DOC_${kind}`,Runtime.user);toast(`${label} GUARDADO`,'good');closeModal()}catch(err){toast(err.message,'bad')}}}
export function convertDocument(kind,id){if(!can(Runtime.role,'invoiceWrite'))return toast('SIN PERMISO PARA FACTURAR','bad');const d=st()[docCollections[kind]].find(x=>x.id===id);if(!d||d.invoiceId)return toast('DOCUMENTO YA FACTURADO O NO ENCONTRADO','bad');invoiceModal(null,{clientId:d.clientId,clientSnapshot:d.clientSnapshot,sourceDocument:{kind,id},lines:d.lines})}

function monthEnd(month){const [y,m]=month.split('-').map(Number),d=new Date(y,m,0);return `${y}-${String(m).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`}
function moveDate(m){return String(m.date||m.createdAt||'').slice(0,10)}
function stockAt(productId,end,location=null){return round2(st().stockMoves.filter(m=>m.productId===productId&&moveDate(m)<=end&&(!location||(m.location||'ALMACEN')===location)).reduce((s,m)=>s+Number(m.qty||0),0))}
function negativeAt(end){const locs=[...new Set([...LOCATIONS,...st().stockMoves.map(m=>m.location||'ALMACEN')])],out=[];for(const p of products())for(const location of locs){const q=stockAt(p.id,end,location);if(q<-.0001)out.push({p,location,q})}return out}
function closeNumbers(invs){const nums=invs.filter(i=>i.number).map(i=>i.number);return[...new Set(nums.filter((n,i)=>nums.indexOf(n)!==i))]}
export function closuresView(){const month=window.ARW_CLOSE_MONTH||today().slice(0,7),end=monthEnd(month),invs=st().invoices.filter(i=>i.date?.startsWith(month)),delivered=st().orders.filter(o=>o.date?.startsWith(month)&&o.status==='delivered'&&!o.invoiceId),neg=negativeAt(end),badBox=products().filter(p=>p.mode==='caja_kg'&&!Number(p.kgPerBox)),dups=closeNumbers(invs),drafts=invs.filter(i=>i.status==='draft'),closed=st().closures.find(c=>c.id===`close_${month}`),actions=closed?(Runtime.role==='owner'?'<button class="btn bad" id="reopenMonth">REABRIR MES</button>':''):'<button class="btn primary" data-action="close-month">CERRAR MES</button>';const html=`${section('CIERRE MENSUAL','CONTROL A FECHA DE FIN DE MES · AL CERRAR SE BLOQUEAN NUEVAS EMISIONES/COMPRAS',actions)}<div class="panel"><label class="field">MES<input id="closeMonth" type="month" value="${month}"></label></div><br><div class="kpis">${kpi('FACTURAS',String(invs.length))}${kpi('BORRADORES',String(drafts.length))}${kpi('ENTREGAS SIN FACTURA',String(delivered.length))}${kpi('STOCK NEGATIVO FIN MES',String(neg.length))}</div>${badBox.length?`<div class="danger">CAJA × KG SIN PESO: ${badBox.map(p=>esc(p.code)).join(', ')}</div>`:''}${dups.length?`<div class="danger">NÚMEROS DUPLICADOS: ${esc(dups.join(', '))}</div>`:''}${neg.length?`<div class="danger">NEGATIVOS A ${end}: ${neg.slice(0,12).map(x=>`${esc(x.p.code)} ${esc(x.location)} ${x.q}`).join(' · ')}</div>`:''}${closed?`<div class="success">CIERRE GUARDADO ${esc(closed.closedAt||'')} · STOCK VALORADO A FECHA ${end}</div>`:''}`;setTimeout(()=>{const b=document.querySelector('#reopenMonth');if(b)b.onclick=async()=>{if(!confirm(`¿REABRIR ${month}?`))return;try{await reopenMonthClosure(month,Runtime.user);toast('MES REABIERTO','good')}catch(e){toast(e.message,'bad')}}},0);return html}
export async function closeMonth(){if(!can(Runtime.role,'closeMonth'))return toast('SIN PERMISO PARA CERRAR','bad');const month=window.ARW_CLOSE_MONTH||today().slice(0,7),end=monthEnd(month),invs=st().invoices.filter(i=>i.date?.startsWith(month)),delivered=st().orders.filter(o=>o.date?.startsWith(month)&&o.status==='delivered'&&!o.invoiceId),neg=negativeAt(end),badBox=products().filter(p=>p.mode==='caja_kg'&&!Number(p.kgPerBox)),drafts=invs.filter(i=>i.status==='draft'),dups=closeNumbers(invs);if(delivered.length||neg.length||badBox.length||drafts.length||dups.length)return toast('RESUELVE TODAS LAS ALERTAS ANTES DE CERRAR','bad');if(!confirm(`¿CERRAR ${month}? EL STOCK SE CONGELARÁ A ${end}.`))return;const stockSnapshot=products().map(p=>{const qty=stockAt(p.id,end),cost=costAtDate(p.id,{date:end},{},products(),st().priceHistory).unitCost||Number(p.buyPrice||0);return{productId:p.id,qty,cost,value:round2(Math.max(0,qty)*cost)}});await saveEntity('closures',{id:`close_${month}`,month,endDate:end,closedAt:now(),stockSnapshot,invoiceCount:invs.filter(i=>i.status!=='draft').length},'MONTH_CLOSE',Runtime.user);toast('MES CERRADO CON STOCK A FECHA','good')}
'''
write('js/views-ops.js',views_ops)

# ---------------- views-admin: health panel + guards ----------------
rep('js/views-admin.js',"import {saveEntity,forceMasterData} from './firebase.js';", "import {saveEntity,forceMasterData} from './firebase.js';\nimport {systemHealth} from './health.js';\nimport {can} from './permissions.js';")
rep('js/views-admin.js','export function expenseModal(){',"export function expenseModal(){if(!can(Runtime.role,'expenseWrite'))return toast('SIN PERMISO PARA REGISTRAR GASTOS','bad');")
rep('js/views-admin.js','export function massPriceModal(pid=\'\'){',"export function massPriceModal(pid=''){if(!can(Runtime.role,'priceWrite'))return toast('SIN PERMISO PARA CAMBIAR TARIFAS','bad');")
rep('js/views-admin.js','export function routeModal(){',"export function routeModal(){if(!can(Runtime.role,'routeWrite'))return toast('SIN PERMISO PARA EDITAR RUTAS','bad');")
audit="""export function auditView(){const h=systemHealth(st());const sev=x=>x.severity==='error'?badge('ERROR','bad'):x.severity==='warning'?badge('AVISO','warn'):badge('INFO');return `${section('AUDITORÍA Y SALUD DEL SISTEMA','INTEGRIDAD DE DATOS · REFERENCIAS · NUMERACIÓN · STOCK · COSTES')}<div class="kpis">${kpi('ERRORES',String(h.counts.error))}${kpi('AVISOS',String(h.counts.warning))}${kpi('FACTURAS REVISADAS',String(h.checked.invoices))}${kpi('MOV. STOCK',String(h.checked.stockMoves))}</div>${h.ok?'<div class="success"><b>DIAGNÓSTICO CRÍTICO: OK.</b> NO SE HAN DETECTADO ERRORES DE INTEGRIDAD.</div>':'<div class="danger"><b>HAY ERRORES DE INTEGRIDAD QUE REQUIEREN REVISIÓN.</b></div>'}<br>${table(['NIVEL','CÓDIGO','DETALLE'],h.issues.slice(0,200).map(x=>`<tr><td>${sev(x)}</td><td><small>${esc(x.code)}</small></td><td>${esc(x.message)}</td></tr>`))}<br><h3>TRAZA DE AUDITORÍA</h3>${table(['FECHA/HORA','USUARIO','ACCIÓN','ENTIDAD','ID'],st().audit.slice(0,300).map(a=>`<tr><td>${String(a.at||'').slice(0,19).replace('T',' ')}</td><td>${esc(a.userEmail||'')}</td><td>${esc(a.action||'')}</td><td>${esc(a.entity||'')}</td><td>${esc(a.entityId||'')}</td></tr>`))}`}
"""
sub('js/views-admin.js',r'export function auditView\(\)\{.*?\}\nexport function settingsView',audit+'export function settingsView')
rep('js/views-admin.js','VERSIÓN: <b>4.0.0</b>','VERSIÓN: <b>6.0.0</b>')

# ---------------- firestore.rules: draft editing, issued immutability, warehouse workflow writes ----------------
rules=read('firestore.rules')
rules=rules.replace("allow update: if manager() || (billing() && request.resource.data.diff(resource.data).affectedKeys().hasOnly(['status','voidReason','voidedAt','rectificationIds','paid','sentAt','updatedAt']));", "allow update: if billing() && (resource.data.status == 'draft' || request.resource.data.diff(resource.data).affectedKeys().hasOnly(['status','voidReason','voidedAt','rectificationIds','paid','sentAt','updatedAt']));")
rules=rules.replace("(warehouse() && collection in ['products','suppliers','purchases','transfers','wastes','returns','inventoryCounts','containers','priceHistory'])", "(warehouse() && collection in ['products','suppliers','purchases','orders','routes','transfers','wastes','returns','inventoryCounts','containers','priceHistory'])")
write('firestore.rules',rules)

# ---------------- version/cache ----------------
rep('service-worker.js',"const CACHE='arw2026-v11-20260816-finance';", "const CACHE='arw2026-v12-20260816-audit-v6';")
rep('service-worker.js',"'./js/finance.js','./js/views-finance.js'", "'./js/finance.js','./js/views-finance.js','./js/permissions.js','./js/health.js'")
rep('firebase-config.js','version: "4.0.0"','version: "6.0.0"')
idx=read('index.html').replace('?v=4.0.0','?v=6.0.0').replace('<small>v4</small>','<small>v6</small>')
write('index.html',idx)

print('ARW2026 AUDIT V6 PATCH APPLIED')
