import {Store} from '../core/store.js';
import {n,round2,upper,esc,money,isoDate,monthKey,toast,download} from '../core/utils.js';
import {kpi,table,section,badge} from '../core/ui.js';
import {calcInvoice,invoiceStatus,stockForProduct} from '../core/domain.js';
import {summaryPdf} from '../core/pdf.js';
const st=()=>Store.state,client=id=>st().clients.find(x=>x.id===id),product=id=>st().products.find(x=>x.id===id);
function periodInvoices(period){return st().invoices.filter(i=>i.date?.startsWith(period)&&!['draft','void'].includes(i.status)).map(calcInvoice)}
function vatSummary(list){const vat={};for(const i of list)for(const v of i.vatBreakdown){vat[v.rate]??={base:0,vat:0};vat[v.rate].base+=n(v.base);vat[v.rate].vat+=n(v.vat)}return vat}
export function reportsView(){const period=window.ARW_REPORT_MONTH||monthKey(),list=periodInvoices(period),vat=vatSummary(list),purchases=st().purchases.filter(p=>p.date?.startsWith(period)&&p.status==='received'),expenses=st().expenses.filter(e=>e.date?.startsWith(period)),purchaseVat=purchases.reduce((s,p)=>s+n(p.vatTotal),0)+expenses.reduce((s,e)=>s+n(e.vatAmount),0),salesVat=list.reduce((s,i)=>s+n(i.vatTotal),0);return `${section('REPORTES / IVA','MENSUAL · TRIMESTRAL · ANUAL · LIBROS · RENTABILIDAD · STOCK',[['PDF MES','reportMonth','primary'],['PDF TRIMESTRE','reportQuarter'],['PDF AÑO','reportYear'],['EXCEL VENTAS','salesBook'],['EXCEL COMPRAS','purchaseBook']])}<section class="panel"><label>MES<input id="reportMonth" type="month" value="${period}"></label></section><br><div class="kpis">${kpi('FACTURADO',money(list.reduce((s,i)=>s+i.total,0)))}${kpi('BASE',money(list.reduce((s,i)=>s+i.base,0)))}${kpi('IVA REPERCUTIDO',money(salesVat))}${kpi('IVA SOPORTADO EST.',money(purchaseVat))}</div><div class="grid2"><section class="panel"><h3>IVA POR TIPO</h3>${table(['IVA','BASE','CUOTA'],Object.entries(vat).map(([r,x])=>`<tr><td>${r}%</td><td>${money(x.base)}</td><td>${money(x.vat)}</td></tr>`))}</section><section class="panel"><h3>COBROS</h3><p>COBRADO: <b>${money(list.reduce((s,i)=>s+i.paid,0))}</b></p><p>PENDIENTE: <b>${money(list.reduce((s,i)=>s+i.pending,0))}</b></p><p>FACTURAS: <b>${list.length}</b></p><p>RECTIFICATIVAS: <b>${list.filter(i=>i.type==='credit').length}</b></p></section></div><br>${table(['Nº','FECHA','CLIENTE','BASE','IVA','TOTAL','COBRADO','PENDIENTE','ESTADO'],list.map(i=>`<tr><td>${esc(i.number||'')}</td><td>${i.date}</td><td>${esc(client(i.clientId)?.name||'')}</td><td>${money(i.base)}</td><td>${money(i.vatTotal)}</td><td>${money(i.total)}</td><td>${money(i.paid)}</td><td>${money(i.pending)}</td><td>${invoiceStatus(i)}</td></tr>`))}`}
function periodRows(list){return list.map(i=>[i.number||'',i.date||'',upper(client(i.clientId)?.name||''),money(i.base),money(i.vatTotal),money(i.total),money(i.paid),money(i.pending)])}
export function reportMonth(period=window.ARW_REPORT_MONTH||monthKey()){const list=periodInvoices(period);summaryPdf(`REPORTE MENSUAL ${period}`,['Nº','FECHA','CLIENTE','BASE','IVA','TOTAL','COBRADO','PENDIENTE'],periodRows(list),`REPORTE_${period}.pdf`)}
export function reportQuarter(){const base=window.ARW_REPORT_MONTH||monthKey(),[y,m]=base.split('-').map(Number),q=Math.floor((m-1)/3)+1,months=[(q-1)*3+1,(q-1)*3+2,(q-1)*3+3].map(x=>`${y}-${String(x).padStart(2,'0')}`),list=st().invoices.filter(i=>months.some(mm=>i.date?.startsWith(mm))&&!['draft','void'].includes(i.status)).map(calcInvoice);summaryPdf(`REPORTE ${y} T${q}`,['Nº','FECHA','CLIENTE','BASE','IVA','TOTAL','COBRADO','PENDIENTE'],periodRows(list),`REPORTE_${y}_T${q}.pdf`)}
export function reportYear(){const y=(window.ARW_REPORT_MONTH||monthKey()).slice(0,4),list=st().invoices.filter(i=>i.date?.startsWith(y)&&!['draft','void'].includes(i.status)).map(calcInvoice);summaryPdf(`REPORTE ANUAL ${y}`,['Nº','FECHA','CLIENTE','BASE','IVA','TOTAL','COBRADO','PENDIENTE'],periodRows(list),`REPORTE_ANUAL_${y}.pdf`)}
function saveXlsx(rows,name,sheet){const ws=XLSX.utils.json_to_sheet(rows),wb=XLSX.utils.book_new();XLSX.utils.book_append_sheet(wb,ws,sheet);XLSX.writeFile(wb,name)}
export function salesBook(period=window.ARW_REPORT_MONTH||monthKey()){saveXlsx(periodInvoices(period).map(i=>({NUMERO:i.number,FECHA:i.date,CLIENTE:client(i.clientId)?.name||'',NIF:client(i.clientId)?.nif||'',BASE:i.base,IVA:i.vatTotal,TOTAL:i.total,COBRADO:i.paid,PENDIENTE:i.pending,TIPO:i.type==='credit'?'RECTIFICATIVA':'FACTURA',ESTADO:invoiceStatus(i)})),`LIBRO_VENTAS_${period}.xlsx`,'LIBRO VENTAS')}
export function purchaseBook(period=window.ARW_REPORT_MONTH||monthKey()){saveXlsx(st().purchases.filter(x=>x.date?.startsWith(period)).map(x=>({FECHA:x.date,PROVEEDOR:st().suppliers.find(s=>s.id===x.supplierId)?.name||'',NIF:st().suppliers.find(s=>s.id===x.supplierId)?.nif||'',FACTURA:x.number||'',BASE:n(x.base),IVA:n(x.vatTotal),TOTAL:n(x.total),ESTADO:x.status})),`LIBRO_COMPRAS_${period}.xlsx`,'LIBRO COMPRAS')}
export function profitabilityView(){const clients=st().clients.map(c=>{const inv=st().invoices.filter(i=>i.clientId===c.id&&!['draft','void'].includes(i.status)).map(calcInvoice),sales=inv.reduce((s,i)=>s+i.base,0),cost=inv.flatMap(i=>i.lines).reduce((s,l)=>s+(l.mode==='caja_kg'?n(l.net):n(l.qty))*n(l.buyPriceSnapshot),0),profit=round2(sales-cost);return{c,sales,cost,profit,margin:sales?round2(profit/sales*100):0}}).filter(x=>x.sales).sort((a,b)=>b.profit-a.profit);const products=st().products.map(p=>{const lines=st().invoices.filter(i=>!['draft','void'].includes(i.status)).map(calcInvoice).flatMap(i=>i.lines).filter(l=>l.productId===p.id),sales=lines.reduce((s,l)=>s+n(l.base),0),cost=lines.reduce((s,l)=>s+(l.mode==='caja_kg'?n(l.net):n(l.qty))*n(l.buyPriceSnapshot),0),profit=round2(sales-cost);return{p,sales,cost,profit,margin:sales?round2(profit/sales*100):0}}).filter(x=>x.sales).sort((a,b)=>b.profit-a.profit);return `${section('RENTABILIDAD','CLIENTE · PRODUCTO · RUTA · COSTE REAL')}<div class="grid2"><section class="panel"><h3>POR CLIENTE</h3>${table(['CLIENTE','VENTA','COSTE','BENEFICIO','MARGEN'],clients.slice(0,30).map(x=>`<tr><td>${esc(x.c.name)}</td><td>${money(x.sales)}</td><td>${money(x.cost)}</td><td>${money(x.profit)}</td><td>${x.margin}%</td></tr>`))}</section><section class="panel"><h3>POR PRODUCTO</h3>${table(['PRODUCTO','VENTA','COSTE','BENEFICIO','MARGEN'],products.slice(0,30).map(x=>`<tr><td>${esc(x.p.name)}</td><td>${money(x.sales)}</td><td>${money(x.cost)}</td><td>${money(x.profit)}</td><td>${x.margin}%</td></tr>`))}</section></div>`}
export function stockSnapshotExport(){const rows=st().products.map(p=>{const q=stockForProduct(st(),p.id).physical;return{CODIGO:p.code,PRODUCTO:p.name,STOCK:q,CAJAS:p.mode==='caja_kg'&&n(p.kgPerBox)?q/n(p.kgPerBox):'',KG_CAJA:n(p.kgPerBox),COSTE:n(p.buyPrice),VALOR:round2(q*n(p.buyPrice)),IVA:n(p.vat)}});saveXlsx(rows,`STOCK_${isoDate()}.xlsx`,'STOCK')}
